
#pragma once

#include "globalBase.h"

// Default layers for 3D objects:
#define SHAPE_LAYER             0x0001
#define JOINT_LAYER             0x0002
#define DUMMY_LAYER             0x0004
#define PROXIMITY_SENSOR_LAYER  0x0008
#define VISION_SENSOR_LAYER     0x0008
#define MILL_LAYER              0x0008
#define FORCE_SENSOR_LAYER      0x0008
#define CAMERA_LIGHT_LAYER      0x0010
#define GRAPH_LAYER             0x0020
#define PATH_LAYER              0x0020
#define OCTREE_LAYER            0x0040
#define POINTCLOUD_LAYER        0x0040
#define ENVIRONMENT_LAYER       0x0080

// General serialization tags. Never change an entry!! (values are serialized!)
#define SER_SHAPE                       "SHP"
#define SER_JOINT                       "JNT"
#define SER_CAMERA                      "CMA"
#define SER_LIGHT                       "LGT"
#define SER_MIRROR                      "MIR"
#define SER_DUMMY                       "DMY"
#define SER_GRAPH                       "GRH"
#define SER_PROXIMITYSENSOR             "SNR"
#define SER_VISIONSENSOR                "RSN"
#define SER_OCTREE                      "OCT"
#define SER_POINTCLOUD                  "PTC"
#define SER_VERSATILE_OLD               "VRE"
//#define SER_GEOMETRIC_OLD             "GEO" // RESERVED TAG
#define SER_TEXTURE                     "TEX"
#define SER_DYNMATERIAL                 "DMA"
#define SER_COLLECTION                  "GRP"
#define SER_ENVIRONMENT                 "ENV"
#define SER_GHOSTS                      "GHO"
#define SER_FORWARD_COMPATIBILITY       "BCK"
#define SER_IK                          "IKO"
#define SER_VIEWS                       "VEW"
#define SER_COLLISION                   "COL"
#define SER_DISTANCE                    "DST"
#define SER_PATH                        "PAT"
#define SER_MILL                        "MIL"
#define SER_FORCESENSOR                 "FSE"
#define SER_PATH_PLANNING               "PPL"
#define SER_MOTION_PLANNING             "MPL"
#define SER_SETTINGS                    "SET"
#define SER_DYNAMICS                    "DYN"
#define SER_BUTTON_BLOCK                "BBK"
#define SER_LUA_SCRIPT                  "LST"
#define SER_SCENE_CUSTOM_DATA           "CDS"
#define SER_OBJECT_CUSTOM_DATA          "CDO"
#define SER_GEOMETRIC_CONSTRAINT_OBJECT "GCO"
#define SER_SIMULATION                  "SIM"
#define SER_MODEL_ACKNOWLEDGEMENTOLD_20100714       "MAC"
#define SER_MODEL_THUMBNAIL_OLD_COMPATIBILITY_2012_03_06                "MTB" // for backward compatibility
#define SER_MODEL_THUMBNAIL             "MTC"
#define SER_MODEL_THUMBNAIL_INFO        "BBC"
#define SER_VERTICESINDICESNORMALSEDGES "VIN"


#define IK_DIVISION_FACTOR 100.0f // needed for better stability of resolutions!
#define SELECTION_BUFFER_SIZE 100000    // Specifies how many objects can be selected at the (from 10000 to 100000 on 14/6/2011)

#define NON_OBJECT_PICKING_ID_BANNER_START SIM_IDSTART_COLLECTION
#define NON_OBJECT_PICKING_ID_BANNER_END (NON_OBJECT_PICKING_ID_BANNER_START+10000)
#define NON_OBJECT_PICKING_ID_PATH_PTS_START (NON_OBJECT_PICKING_ID_BANNER_END+1)

#define BUTTON_MIN_X_SIZE 2         // In pixels
#define BUTTON_MIN_Y_SIZE 2         // In pixels
#define BUTTON_SLIDER_X_SIZE 0.2f   // Percentage of button x-size
#define BUTTON_SLIDER_Y_SIZE 0.8f   // Percentage of button y-size
#define MAX_X_BUTTONS 256           // Maximum number of buttons in a block (x)
#define MAX_Y_BUTTONS 256           // Maximum number of buttons in a block (y)
#define BROWSER_HIERARCHY_TITLE_BAR_HEIGHT 16
#define BROWSER_HIERARCHY_TITLE_BAR_CLOSING_BUTTON_WIDTH 16
#define BROWSER_HIERARCHY_MAIN_RENDERING_WINDOW_SEPARATION_WIDTH 2
#define HIERARCHY_SCROLLBAR_WIDTH (BROWSER_HIERARCHY_TITLE_BAR_CLOSING_BUTTON_WIDTH+2)

enum {
    GENERAL_PROPERTIES_DLG=0,
    SHAPE_DLG,
    SHAPE_DYN_DLG,
    CAMERA_DLG,
    JOINT_DLG,
    JOINT_DYN_DLG,
    SETTINGS_DLG,
    SELECTION_DLG,
    ENVIRONMENT_DLG,
    COLLISION_DLG,
    PROXIMITY_SENSOR_DLG,
    DETECTION_VOLUME_DLG,
    VISION_SENSOR_DLG,
    VISION_SENSOR_FILTER_DLG,
    MILL_DLG,
    SHAPE_EDITION_DLG,
    OBJECT_DLG,
    CALCULATION_DLG,
    FORCE_SENSOR_DLG,
    GRAPH_DLG,
    BUTTON_DLG,
    CUSTOM_UI_DLG,
    TRANSLATION_ROTATION_DLG,
    LUA_SCRIPT_DLG,
    COLLECTION_DLG,
    DISTANCE_DLG,
    HIERARCHY_DLG,
    BROWSER_DLG,
    IK_DLG,
    DUMMY_DLG,
    LAYERS_DLG,
    DYNAMICS_DLG,
    PATH_DLG,
    PATH_PLANNING_DLG,
    MOTION_PLANNING_DLG,
    CONSTRAINT_SOLVER_DLG,
    SIMULATION_DLG,
    INTERACTIVE_IK_DLG,
    FOG_DLG,
    MATERIAL_DLG,
    LIGHTMATERIAL_DLG,
    COLOR_DLG,
    PATH_SHAPING_DLG,
    PATH_EDITION_DLG,
    AVI_RECORDER_DLG,
    LIGHT_DLG,
    MIRROR_DLG,
    TEXTURE_DLG,
    GEOMETRY_DLG,
    MULTISHAPE_EDITION_DLG,
    GRAPH2DAND3DCURVES_DLG,
    IKELEMENT_DLG,
};

enum {
    FILE_FORMAT_OBJ=0,
    FILE_FORMAT_DXF,
    FILE_FORMAT_3DS,
    FILE_FORMAT_ASCII_STL,
    FILE_FORMAT_BINARY_STL,
    FILE_FORMAT_COLLADA,
    FILE_FORMAT_ANY_STL,
};

enum { // CURSORS:
    sim_cursor_arrow=0,
    sim_cursor_finger,
    sim_cursor_all_directions,
    sim_cursor_horizontal_directions,
    sim_cursor_vertical_directions,
    sim_cursor_slash_directions,
    sim_cursor_backslash_directions,
    sim_cursor_cross,
    sim_cursor_open_hand,
    sim_cursor_closed_hand,
};

enum { // DATA STREAM TRANSFORMATIONS:
    DATA_STREAM_ORIGINAL=0,
    DATA_STREAM_DERIVATIVE,
    DATA_STREAM_INTEGRAL,
    DATA_STREAM_CUMULATIVE,
};

enum { // RENDERING MODES:
    RENDERING_MODE_SOLID=0,
    RENDERING_MODE_WIREFRAME_EDGES,
    RENDERING_MODE_WIREFRAME_TRIANGLES,
};

enum { // catch elements:
    sim_left_button     =0x0001,
    sim_middle_button   =0x0002,
    sim_right_button    =0x0004,
    sim_focus           =0x0008,
};

// Specific camera orientations:
enum {
    NO_SPECIFIC_VIEW=0,
    POSITIVE_X_VIEW,
    NEGATIVE_X_VIEW,
    POSITIVE_Y_VIEW,
    NEGATIVE_Y_VIEW,
    POSITIVE_Z_VIEW,
    NEGATIVE_Z_VIEW
};

enum {
    NOSELECTION=0,
    CTRLSELECTION,
    SHIFTSELECTION,
};

enum {
    CONSTANT_ATTENUATION=0,
    LINEAR_ATTENUATION,
    QUADRATIC_ATTENUATION
};

// Serialization types. Never delete an entry or change order!! (values are serialized!)
enum {
    SINGLE_VIEW=0,
    FOUR_VIEWS,
    SIX_VIEWS_OLD,
    RESERVED_AND_PLACE_HOLDER1,
    HORIZONTALLY_DIVIDED,
    VERTICALLY_DIVIDED,
    HORIZONTALLY_DIVIDED_3,
    VERTICALLY_DIVIDED_3,
    HORIZONTAL_1_PLUS_3_VIEWS,
    VERTICAL_1_PLUS_3_VIEWS,
    HORIZONTAL_1_PLUS_4_VIEWS,
    VERTICAL_1_PLUS_4_VIEWS,
    SIX_VIEWS,
    EIGHT_VIEWS,
    CLOSING_VIEW_ITEM
};

// View selection modes:
enum {
    NO_VIEW_SELECT_MODE=0,
    CAMERA_VIEW_SELECT_MODE,
    GRAPH_VIEW_SELECT_MODE,
    VISIONSENSOR_VIEW_SELECT_MODE,
    VIEWABLE_VIEW_SELECT_MODE
};

enum {
    NO_EDIT_MODE=0,
    TRIANGLE_EDIT_MODE=1,
    VERTEX_EDIT_MODE=2,
    EDGE_EDIT_MODE=4,
    SHAPE_EDIT_MODE=TRIANGLE_EDIT_MODE|VERTEX_EDIT_MODE|EDGE_EDIT_MODE,
    PATH_EDIT_MODE=8,
    BUTTON_EDIT_MODE=16,
    MULTISHAPE_EDIT_MODE=32,
    SHAPE_OR_PATH_EDIT_MODE=SHAPE_EDIT_MODE|PATH_EDIT_MODE|MULTISHAPE_EDIT_MODE // Edit mode when regular objects can't be selected
};

// Group types:
enum {
    GROUP_LOOSE=0,
    GROUP_FROM_BASE_INCLUDED,
    GROUP_FROM_BASE_EXCLUDED,
    GROUP_FROM_TIP_INCLUDED,
    GROUP_FROM_TIP_EXCLUDED,
    GROUP_EVERYTHING
};


// Graphing objects. Never remove an element!! (instead replace it with an dummy name
// (RESERVED0)). These values are serialized!
// When changing something here, don't forget to change the 
// performeObjectLoadingMapping-
// performCollectionLoadingMapping-
// performCollisionLoadingMapping-
// ...
// announceObjectWillBeErased-
// announceCollectionWillBeErased-
// announceCollisionWillBeErased-
// ...
// routines in CGraphData!!!!!
// and the getCyclicAndRange function in graph!!!!!!!!!!!!
// and the adjustDataToUserMetric function graph!!!!!!!!
enum {
    GRAPH_3DOBJECT_START=0,         // From here, streams associated with a 3DObject ID:
    GRAPH_3DOBJECT_ALL_X_ABS,
    GRAPH_3DOBJECT_ALL_Y_ABS,
    GRAPH_3DOBJECT_ALL_Z_ABS,
    GRAPH_3DOBJECT_ALL_X_REL,
    GRAPH_3DOBJECT_ALL_Y_REL,
    GRAPH_3DOBJECT_ALL_Z_REL,
    GRAPH_3DOBJECT_ALL_ALPHA_ABS,
    GRAPH_3DOBJECT_ALL_BETA_ABS,
    GRAPH_3DOBJECT_ALL_GAMMA_ABS,
    GRAPH_3DOBJECT_ALL_ALPHA_REL,
    GRAPH_3DOBJECT_ALL_BETA_REL,
    GRAPH_3DOBJECT_ALL_GAMMA_REL,

    GRAPH_3DOBJECT_ALL_XVEL_ABS,
    GRAPH_3DOBJECT_ALL_YVEL_ABS,
    GRAPH_3DOBJECT_ALL_ZVEL_ABS,
    GRAPH_3DOBJECT_ALL_VEL_ABS,
    GRAPH_3DOBJECT_ALL_ANGULAR_VEL_ABS,

    GRAPH_3DOBJECT_PROXSENSOR_SUBSTART=500,         // sub-start
    GRAPH_3DOBJECT_PROXSENSOR_X_ABS,
    GRAPH_3DOBJECT_PROXSENSOR_Y_ABS,
    GRAPH_3DOBJECT_PROXSENSOR_Z_ABS,
    GRAPH_3DOBJECT_PROXSENSOR_X_REL,
    GRAPH_3DOBJECT_PROXSENSOR_Y_REL,
    GRAPH_3DOBJECT_PROXSENSOR_Z_REL,
    GRAPH_3DOBJECT_PROXSENSOR_X_REL_TO_SENSOR,
    GRAPH_3DOBJECT_PROXSENSOR_Y_REL_TO_SENSOR,
    GRAPH_3DOBJECT_PROXSENSOR_Z_REL_TO_SENSOR,
    GRAPH_3DOBJECT_PROXSENSOR_DIST,
    GRAPH_3DOBJECT_PROXSENSOR_AZIMUTH,
    GRAPH_3DOBJECT_PROXSENSOR_ELEVATION,
    GRAPH_3DOBJECT_PROXSENSOR_DETECTION_STATE,
    GRAPH_3DOBJECT_PROXSENSOR_CALCULATION_TIME,
    GRAPH_3DOBJECT_PROXSENSOR_SUBEND=550,               // sub-end
    GRAPH_3DOBJECT_VISIONSENSOR_SUBSTART=551,       // sub-start
    GRAPH_3DOBJECT_VISIONSENSOR_MIN_RED,
    GRAPH_3DOBJECT_VISIONSENSOR_MAX_RED,
    GRAPH_3DOBJECT_VISIONSENSOR_AVG_RED,
    GRAPH_3DOBJECT_VISIONSENSOR_MIN_GREEN,
    GRAPH_3DOBJECT_VISIONSENSOR_MAX_GREEN,
    GRAPH_3DOBJECT_VISIONSENSOR_AVG_GREEN,
    GRAPH_3DOBJECT_VISIONSENSOR_MIN_BLUE,
    GRAPH_3DOBJECT_VISIONSENSOR_MAX_BLUE,
    GRAPH_3DOBJECT_VISIONSENSOR_AVG_BLUE,
    GRAPH_3DOBJECT_VISIONSENSOR_MIN_INTENSITY,
    GRAPH_3DOBJECT_VISIONSENSOR_MAX_INTENSITY,
    GRAPH_3DOBJECT_VISIONSENSOR_AVG_INTENSITY,
    GRAPH_3DOBJECT_VISIONSENSOR_MIN_DEPTH,
    GRAPH_3DOBJECT_VISIONSENSOR_MAX_DEPTH,
    GRAPH_3DOBJECT_VISIONSENSOR_AVG_DEPTH,
    GRAPH_3DOBJECT_VISIONSENSOR_DETECTION_STATE,
    GRAPH_3DOBJECT_VISIONSENSOR_CALCULATION_TIME,
    GRAPH_3DOBJECT_VISIONSENSOR_SUBEND=650,             // sub-end
    GRAPH_3DOBJECT_JOINT_SUBSTART=651,                  // sub-start
    GRAPH_3DOBJECT_JOINT_POSITION,
    GRAPH_3DOBJECT_JOINT_DYN_POSITION_ERROR,
    GRAPH_3DOBJECT_JOINT_DYN_ORIENTATION_ERROR,
    GRAPH_3DOBJECT_JOINT_DYN_FORCE_OR_TORQUE,
    GRAPH_3DOBJECT_JOINT_VELOCITY,
    GRAPH_3DOBJECT_JOINT_SUBEND=700,                // sub-end

    GRAPH_3DOBJECT_PATH_SUBSTART=701,                   // sub-start
    GRAPH_3DOBJECT_PATH_POSITION,
    GRAPH_3DOBJECT_PATH_POSITION_LINEAR_COMPONENT,
    GRAPH_3DOBJECT_PATH_POSITION_ANGULAR_COMPONENT,
    GRAPH_3DOBJECT_PATH_SUBEND=750,             // sub-end

    GRAPH_3DOBJECT_MILL_SUBSTART=751,           // sub-start
    GRAPH_3DOBJECT_MILL_CUT_SURFACE,
    GRAPH_3DOBJECT_MILL_CUT_VOLUME,
    GRAPH_3DOBJECT_MILL_CALCULATION_TIME,
    GRAPH_3DOBJECT_MILL_SUBEND=770,             // sub-end

    GRAPH_3DOBJECT_FORCESENSOR_SUBSTART=771,            // sub-start
    GRAPH_3DOBJECT_FORCESENSOR_FORCE_X,
    GRAPH_3DOBJECT_FORCESENSOR_FORCE_Y,
    GRAPH_3DOBJECT_FORCESENSOR_FORCE_Z,
    GRAPH_3DOBJECT_FORCESENSOR_FORCE_LENGTH,
    GRAPH_3DOBJECT_FORCESENSOR_TORQUE_X,
    GRAPH_3DOBJECT_FORCESENSOR_TORQUE_Y,
    GRAPH_3DOBJECT_FORCESENSOR_TORQUE_Z,
    GRAPH_3DOBJECT_FORCESENSOR_TORQUE_LENGTH,
    GRAPH_3DOBJECT_FORCESENSOR_POSITION_ERROR,
    GRAPH_3DOBJECT_FORCESENSOR_ORIENTATION_ERROR,
    GRAPH_3DOBJECT_FORCESENSOR_BROKEN,
    GRAPH_3DOBJECT_FORCESENSOR_SUBEND=790,              // sub-end

    GRAPH_3DOBJECT_END=2000,                    //End
    GRAPH_COLLISION_START=2001,                 //Start
    GRAPH_COLLISION_BOOLEAN,
    GRAPH_COLLISION_CALCULATION_TIME,
    GRAPH_COLLISION_END=2100,                   //End
    GRAPH_DISTANCE_START=2101,                  //Start
    GRAPH_DISTANCE_DIST,
    GRAPH_DISTANCE_SEG1_X_ABS,
    GRAPH_DISTANCE_SEG1_Y_ABS,
    GRAPH_DISTANCE_SEG1_Z_ABS,
    GRAPH_DISTANCE_SEG2_X_ABS,
    GRAPH_DISTANCE_SEG2_Y_ABS,
    GRAPH_DISTANCE_SEG2_Z_ABS,
    GRAPH_DISTANCE_SEG1_X_REL,
    GRAPH_DISTANCE_SEG1_Y_REL,
    GRAPH_DISTANCE_SEG1_Z_REL,
    GRAPH_DISTANCE_SEG2_X_REL,
    GRAPH_DISTANCE_SEG2_Y_REL,
    GRAPH_DISTANCE_SEG2_Z_REL,
    GRAPH_DISTANCE_CALCULATION_TIME,
    GRAPH_DISTANCE_END=2400,                    //End
    GRAPH_IK_START=2401,                        //Start
    GRAPH_IK_CALCULATION_TIME,
    GRAPH_IK_END=2500,                          //End
    GRAPH_GCS_START=2501,                       //Start
    GRAPH_GCS_CALCULATION_TIME,
    GRAPH_GCS_END=2600,                         //End
    GRAPH_NOOBJECT_START=2601,                  //Start
    GRAPH_NOOBJECT_TIME,
    GRAPH_NOOBJECT_COLLISION_QUANTITY,
    GRAPH_NOOBJECT_PROXSENSOR_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_COLLISION_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_DISTANCE_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_VISIONSENSOR_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_IK_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_GCS_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_CHILDSCRIPT_EXECUTION_TIME,
    GRAPH_NOOBJECT_USER_DEFINED,
    GRAPH_NOOBJECT_MILL_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_MILL_OVERALL_CUT_SURFACE,
    GRAPH_NOOBJECT_MILL_OVERALL_CUT_VOLUME,
    GRAPH_NOOBJECT_DYNAMICS_OVERALL_CALCULATION_TIME,
    GRAPH_NOOBJECT_SIMULATIONPASS_EXECUTION_TIME,
    GRAPH_NOOBJECT_RENDERING_TIME,
    GRAPH_NOOBJECT_WORK_THREADS_EXECUTION_TIME,
    GRAPH_NOOBJECT_END=3000,                    //End
};

// Hierarchy and other pictures (TGA format):
enum {
    NO_TREE_PICTURE=0,
    SIMPLE_SHAPE_TREE_PICTURE,
    MULTI_SHAPE_TREE_PICTURE,
    PURE_SHAPE_TREE_PICTURE,
    HEIGHTFIELD_SHAPE_TREE_PICTURE,
    PURE_MULTISHAPE_TREE_PICTURE,
    REVOLUTE_JOINT_TREE_PICTURE,
    PRISMATIC_JOINT_TREE_PICTURE,
    SPHERICAL_JOINT_TREE_PICTURE,
    CAMERA_TREE_PICTURE,
    MIRROR_TREE_PICTURE,
    CONVEX_SHAPE_TREE_PICTURE,
    CONVEX_MULTISHAPE_TREE_PICTURE,
    CLIPPLANE_TREE_PICTURE,
    OMNI_LIGHT_ON_TREE_PICTURE,
    OMNI_LIGHT_OFF_TREE_PICTURE,
    SPOT_LIGHT_ON_TREE_PICTURE,
    SPOT_LIGHT_OFF_TREE_PICTURE,
    DIR_LIGHT_ON_TREE_PICTURE,
    DIR_LIGHT_OFF_TREE_PICTURE,
    GRAPH_TREE_PICTURE,
    DUMMY_TREE_PICTURE,
    OCTREE_TREE_PICTURE,
    POINTCLOUD_TREE_PICTURE,
    MODEL_TREE_PICTURE,
    PROXIMITYSENSOR_TREE_PICTURE,
    VISIONSENSOR_TREE_PICTURE,
    PATH_TREE_PICTURE,
    MILL_TREE_PICTURE,
    WORLD_TREE_PICTURE,
    FORCE_SENSOR_TREE_PICTURE,
    WARNING_PICTURE,
    DYNAMICS_PICTURE,
    FOLDER_PICTURE,
    MINUS_SIGN_TREE_PICTURE,
    PLUS_SIGN_TREE_PICTURE,
    MAIN_SCRIPT_PICTURE,
    MAIN_SCRIPT_CUSTOMIZED_PICTURE,
    SCRIPT_PICTURE,
    SCRIPTDISABLED_PICTURE,
    CHECKED_BACKGROUND_PICTURE,
    SCRIPT_THREADED_PICTURE,
    SCRIPTDISABLED_THREADED_PICTURE,
    SCRIPT_PARAMETERS_PICTURE,
    SCRIPT_PARAMETERS_ACTIVE_PICTURE,
    PATH_POINT_PICTURE,
    VERTEX_PICTURE,
    TRIANGLE_PICTURE,
    EDGE_PICTURE,
    BUTTON_BLOCK_PICTURE,
    CUSTOMIZATIONSCRIPT_PICTURE,
    CUSTOMIZATIONSCRIPTDISABLED_PICTURE,
    CURSOR_ARROW,
    CURSOR_FINGER,
    CURSOR_ALL_DIR,
    CURSOR_HORIZONTAL_DIR,
    CURSOR_VERTICAL_DIR,
    CURSOR_SLASH_DIR,
    CURSOR_BACKSLASH_DIR,
    CURSOR_NO_BUTTON,
    CURSOR_LEFT_BUTTON,
    CURSOR_MIDDLE_BUTTON,
    CURSOR_RIGHT_BUTTON,
    EDU_TAG,
    VREP_TAG,
    EVAL_TAG,
    BLUEREALITY_TAG,
    BLUEREALITYEVAL_TAG,
    CURSOR_WHEEL_BUTTON,
    CURSOR_SHIFT_BUTTON,
    CURSOR_CTRL_BUTTON,
};

// Special keys and commands:
// (esc-key is handled in the windows messaging part and sends a "looseFocus" command
enum {
    TAB_KEY=2000,
    ENTER_KEY,
    BACKSPACE_KEY,
    DELETE_KEY,
    CTRL_X_KEY,
    CTRL_C_KEY,
    CTRL_V_KEY,
    UP_KEY,
    DOWN_KEY,
    LEFT_KEY,
    RIGHT_KEY,
    ESC_KEY,
    CTRL_Y_KEY,
    CTRL_Z_KEY,
    CTRL_S_KEY,
    CTRL_O_KEY,
    CTRL_A_KEY,
    CTRL_W_KEY,
    CTRL_Q_KEY,
    CTRL_N_KEY,
    CTRL_SPACE_KEY,
    CTRL_D_KEY,
    CTRL_G_KEY,
    CTRL_E_KEY,
    CTRL_B_KEY,
};

// Rich text items
enum {
    COLOR_AND_COLOR_RESET_RICH_TEXT=0,
    BOX_RICH_TEXT,
    PAUSE_RICH_TEXT,
    START_RICH_TEXT,
    END_RICH_TEXT,
    ARROW_LEFT_RICH_TEXT,
    ARROW_RIGHT_RICH_TEXT,
    ARROW_UP_RICH_TEXT,
    ARROW_DOWN_RICH_TEXT,
    CHECK_RICH_TEXT,
    SQUARE_RICH_TEXT,
    MINIMIZE_RICH_TEXT
};

// menu items
enum {
    NO_COMMAND_CMD=1, // Always start at 1!!!!

    //---------------------------------
    // Edit mode commands start:
    EDIT_MODE_COMMANDS_START_EMCMD,

    // Following is also a kind of edit mode (but not in path edit mode!):
    HALF_PATH_EDIT_MODE_DELETE_PATH_POINTS_EMCMD,

    // General edit mode commands:
    ANY_EDIT_MODE_DESELECT_BUFFER_EMCMD,
    ANY_EDIT_MODE_FINISH_AND_CANCEL_CHANGES_EMCMD,
    ANY_EDIT_MODE_FINISH_AND_APPLY_CHANGES_EMCMD,
    ANY_EDIT_MODE_FINISH_WITH_QUESTION_DLG_EMCMD,

    // Shape edit mode commands:
    SHAPE_EDIT_MODE_START_EMCMD, // also used for compound shape edit mode
    SHAPE_EDIT_MODE_TOGGLE_ON_OFF_EMCMD, // also used for compound shape edit mode
    SHAPE_EDIT_MODE_SWAP_TO_VERTEX_EDIT_MODE_EMCMD,
    SHAPE_EDIT_MODE_SWAP_TO_TRIANGLE_EDIT_MODE_EMCMD,
    SHAPE_EDIT_MODE_SWAP_TO_EDGE_EDIT_MODE_EMCMD,
    SHAPE_EDIT_MODE_FLIP_TRIANGLES_SIDE_EMCMD,
    SHAPE_EDIT_MODE_INSERT_TRIANGLES_EMCMD,
    SHAPE_EDIT_MODE_INSERT_TRIANGLE_FAN_EMCMD,
    SHAPE_EDIT_MODE_MAKE_SHAPE_WITH_SELECTED_TRIANGLES_EMCMD,
    SHAPE_EDIT_MODE_MAKE_RECTANGLE_WITH_SELECTED_TRIANGLES_EMCMD,
    SHAPE_EDIT_MODE_MAKE_SPHERE_WITH_SELECTED_TRIANGLES_EMCMD,
    SHAPE_EDIT_MODE_MAKE_CYLINDER_WITH_SELECTED_TRIANGLES_EMCMD,
    SHAPE_EDIT_MODE_MAKE_DUMMIES_WITH_SELECTED_VERTICES_EMCMD,
    SHAPE_EDIT_MODE_MAKE_PATH_WITH_SELECTED_EDGES_EMCMD,
    SHAPE_EDIT_MODE_TRIANGLE_VERTEX_COPY_EMCMD,
    SHAPE_EDIT_MODE_PASTE_TRIANGLE_VERTEX_EMCMD,
    SHAPE_EDIT_MODE_EMPTY_TRIANGLE_VERTEX_COPY_BUFFER_EMCMD,
    SHAPE_EDIT_MODE_DELETE_TRIANGLE_VERTEX_EDGE_EMCMD,
    SHAPE_EDIT_MODE_TRIANGLE_VERTEX_CUT_EMCMD,
    SHAPE_EDIT_MODE_TOGGLE_HIDDEN_VERTICE_EDGE_SHOW_EMCMD,
    SHAPE_EDIT_MODE_TOGGLE_AUTOMATIC_EDGE_FOLLOWING_EMCMD,
    SHAPE_EDIT_MODE_DIVIDE_LARGEST_TRIANGLES_EMCMD,
    SHAPE_EDIT_MODE_SELECT_ALL_ITEMS_EMCMD,

    // Path edit mode commands:
    PATH_EDIT_MODE_START_EMCMD,
    PATH_EDIT_MODE_TOGGLE_ON_OFF_EMCMD,
    PATH_EDIT_MODE_PATH_POINT_COPY_EMCMD,
    PATH_EDIT_MODE_PASTE_PATH_POINT_EMCMD,
    PATH_EDIT_MODE_DELETE_PATH_POINT_EMCMD,
    PATH_EDIT_MODE_PATH_POINT_CUT_EMCMD,
    PATH_EDIT_MODE_INSERT_NEW_PATH_POINT_EMCMD,
    PATH_EDIT_MODE_APPEND_NEW_PATH_POINT_FROM_CAMERA_EMCMD,
    PATH_EDIT_MODE_MAKE_PATH_FROM_BEZIER_EMCMD,
    PATH_EDIT_MODE_MAKE_DUMMIES_FROM_PATH_CTRL_POINTS_EMCMD,
    PATH_EDIT_MODE_INVERSE_ORDER_OF_SELECTED_PATH_CTRL_POINTS_EMCMD,
    PATH_EDIT_MODE_KEEP_ALL_X_AND_ALIGN_Z_FOR_PATH_POINTS_EMCMD,
    PATH_EDIT_MODE_SELECT_ALL_PATH_POINTS_EMCMD,

    // UI edit mode commands:
    UI_EDIT_MODE_START_EMCMD,
    UI_EDIT_MODE_TOGGLE_ON_OFF_EMCMD,
    UI_EDIT_MODE_COPY_UI_EMCMD,
    UI_EDIT_MODE_PASTE_UI_EMCMD,
    UI_EDIT_MODE_DELETE_UI_EMCMD,
    UI_EDIT_MODE_CUT_UI_EMCMD,
    UI_EDIT_MODE_DELETE_SELECTED_BUTTONS_EMCMD,

    // Edit mode commands end:
    EDIT_MODE_COMMANDS_END_EMCMD,
    //---------------------------------


    //---------------------------------
    // Scene object operations start:
    SCENE_OBJECT_OPERATION_START_SOOCMD,

    SCENE_OBJECT_OPERATION_DESELECT_OBJECTS_SOOCMD,
    SCENE_OBJECT_OPERATION_PASTE_OBJECTS_SOOCMD,
    SCENE_OBJECT_OPERATION_DELETE_OBJECTS_SOOCMD,
    SCENE_OBJECT_OPERATION_OBJECT_FULL_CUT_SOOCMD,
    SCENE_OBJECT_OPERATION_OBJECT_FULL_COPY_SOOCMD,
    SCENE_OBJECT_OPERATION_UNDO_SOOCMD,
    SCENE_OBJECT_OPERATION_REDO_SOOCMD,
    SCENE_OBJECT_OPERATION_EMPTY_PATH_SOOCMD,
    SCENE_OBJECT_OPERATION_ASSEMBLE_SOOCMD,
    SCENE_OBJECT_OPERATION_ROLL_PATH_POINTS_FORWARD_SOOCMD,
    SCENE_OBJECT_OPERATION_ROLL_PATH_POINTS_BACKWARD_SOOCMD,
    SCENE_OBJECT_OPERATION_TRANSFER_DNA_SOOCMD,
    SCENE_OBJECT_OPERATION_MAKE_PARENT_SOOCMD,
    SCENE_OBJECT_OPERATION_MAKE_SIMPLE_SHAPES_PURE_SOOCMD,
    SCENE_OBJECT_OPERATION_MAKE_ORPHANS_SOOCMD,
    SCENE_OBJECT_OPERATION_REPLACE_OBJECTS_SOOCMD,
    SCENE_OBJECT_OPERATION_MORPH_INTO_CONVEX_SHAPES_SOOCMD,
    SCENE_OBJECT_OPERATION_MORPH_INTO_CONVEX_DECOMPOSITION_SOOCMD,
    SCENE_OBJECT_OPERATION_EXTRACT_SHAPE_INSIDE_SOOCMD,
    SCENE_OBJECT_OPERATION_DECIMATE_SHAPE_SOOCMD,
    SCENE_OBJECT_OPERATION_UNLINK_DUMMIES_SOOCMD,
    SCENE_OBJECT_OPERATION_LINK_DUMMIES_DYNAMICS_LOOP_CLOSURE_SOOCMD,
    SCENE_OBJECT_OPERATION_LINK_DUMMIES_GCS_LOOP_CLOSURE_SOOCMD,
    SCENE_OBJECT_OPERATION_LINK_DUMMIES_GCS_TIP_SOOCMD,
    SCENE_OBJECT_OPERATION_LINK_DUMMIES_GCS_TARGET_SOOCMD,
    SCENE_OBJECT_OPERATION_LINK_DUMMIES_IK_TIP_TARGET_SOOCMD,
    SCENE_OBJECT_OPERATION_ALIGN_BOUNDING_BOX_WITH_MAIN_AXIS_SOOCMD,
    SCENE_OBJECT_OPERATION_ALIGN_BOUNDING_BOX_WITH_WORLD_SOOCMD,
    SCENE_OBJECT_OPERATION_ALIGN_BOUNDING_BOX_WITH_TUBE_MAIN_AXIS_SOOCMD,
    SCENE_OBJECT_OPERATION_ALIGN_BOUNDING_BOX_WITH_CUBOID_MAIN_AXIS_SOOCMD,
    SCENE_OBJECT_OPERATION_SELECT_ALL_OBJECTS_SOOCMD,
    SCENE_OBJECT_OPERATION_REMOVE_ASSOCIATED_CHILD_SCRIPT_SOOCMD,
    SCENE_OBJECT_OPERATION_REMOVE_ASSOCIATED_CUSTOMIZATION_SCRIPT_SOOCMD,
    SCENE_OBJECT_OPERATION_GROUP_SHAPES_SOOCMD,
    SCENE_OBJECT_OPERATION_UNGROUP_SHAPES_SOOCMD,
    SCENE_OBJECT_OPERATION_MERGE_SHAPES_SOOCMD,
    SCENE_OBJECT_OPERATION_DIVIDE_SHAPES_SOOCMD,
    SCENE_OBJECT_OPERATION_MERGE_PATHS_SOOCMD,

    // Scene object operations end:
    SCENE_OBJECT_OPERATION_END_SOOCMD,
    //---------------------------------

    //---------
    // Page container functions start:
    PAGE_CONT_FUNCTIONS_START_PCCMD,

    PAGE_CONT_FUNCTIONS_CREATE_SINGLE_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_FOUR_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_SIX_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_EIGHT_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_HORIZONTAL_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_VERTICAL_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_HORIZONTAL_3_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_VERTICAL_3_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_HORIZONTAL_1_PLUS_3_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_VERTICAL_1_PLUS_3_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_HORIZONTAL_1_PLUS_4_VIEW_TYPE_PCCMD,
    PAGE_CONT_FUNCTIONS_CREATE_VERTICAL_1_PLUS_4_VIEW_TYPE_PCCMD,

    // Page container functions end:
    PAGE_CONT_FUNCTIONS_END_PCCMD,
    //---------


    //---------
    // View functions start:
    VIEW_FUNCTIONS_START_VFCMD,

    VIEW_FUNCTIONS_TOGGLE_SOLID_DISPLAY_VFCMD,
    VIEW_FUNCTIONS_PERSPECTIVE_DISPLAY_VFCMD,
    VIEW_FUNCTIONS_SHOW_EDGES_VFCMD,
    VIEW_FUNCTIONS_THICK_EDGES_VFCMD,
    VIEW_FUNCTIONS_TEXTURED_DISPLAY_VFCMD,
    VIEW_FUNCTIONS_SHOW_INERTIAS_VFCMD,
    VIEW_FUNCTIONS_XY_GRAPH_DISPLAY_VFCMD,
    VIEW_FUNCTIONS_XY_GRAPH_AUTO_MODE_DURING_SIMULATION_VFCMD,
    VIEW_FUNCTIONS_TIME_GRAPH_X_AUTO_MODE_DURING_SIMULATION_VFCMD,
    VIEW_FUNCTIONS_TIME_GRAPH_Y_AUTO_MODE_DURING_SIMULATION_VFCMD,
    VIEW_FUNCTIONS_XY_GRAPH_KEEP_PROPORTIONS_AT_ONE_ONE_VFCMD,
    VIEW_FUNCTIONS_LOOK_THROUGH_CAMERA_VFCMD,
//    VIEW_FUNCTIONS_LOOK_AT_GRAPH_VFCMD,
    VIEW_FUNCTIONS_LOOK_AT_VISION_SENSOR_VFCMD,
    VIEW_FUNCTIONS_TRACK_OBJECT_VFCMD,
    VIEW_FUNCTIONS_DONT_TRACK_OBJECT_VFCMD,

    // View functions end:
    VIEW_FUNCTIONS_END_VFCMD,
    //---------


    //---------
    // View selector functions start:
    VIEW_SELECTOR_START_VSCMD,

    VIEW_SELECTOR_SELECT_ANY_VSCMD,

    // View selector functions end:
    VIEW_SELECTOR_END_VSCMD,
    //---------

    //----------
    // Simulation commands start:
    SIMULATION_COMMANDS_START_SCCMD,

    SIMULATION_COMMANDS_START_RESUME_SIMULATION_REQUEST_SCCMD,
    SIMULATION_COMMANDS_PAUSE_SIMULATION_REQUEST_SCCMD,
    SIMULATION_COMMANDS_STOP_SIMULATION_REQUEST_SCCMD,
    SIMULATION_COMMANDS_THREADED_RENDERING_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_REAL_TIME_SIMULATION_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_ONLINE_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_TO_BULLET_2_78_ENGINE_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_TO_BULLET_2_83_ENGINE_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_TO_ODE_ENGINE_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_TO_VORTEX_ENGINE_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_TO_NEWTON_ENGINE_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_DYNAMIC_CONTENT_VISUALIZATION_SCCMD,
    SIMULATION_COMMANDS_SLOWER_SIMULATION_SCCMD,
    SIMULATION_COMMANDS_FASTER_SIMULATION_SCCMD,
    SIMULATION_COMMANDS_TOGGLE_VISUALIZATION_SCCMD,

    // Simulation commands end:
    SIMULATION_COMMANDS_END_SCCMD,
    //----------

    //----------
    // BR commands start:
    BR_COMMANDS_START_SCCMD,

    BR_COMMAND_1_SCCMD,

    // BR commands end:
    BR_COMMANDS_END_SCCMD=BR_COMMANDS_START_SCCMD+1000,
    //----------

    //----------
    // Add commands start:
    ADD_COMMANDS_START_ACCMD,

    ADD_COMMANDS_ADD_FLOATING_VIEW_ACCMD,
    ADD_COMMANDS_ADD_REVOLUTE_JOINT_ACCMD,
    ADD_COMMANDS_ADD_PRISMATIC_JOINT_ACCMD,
    ADD_COMMANDS_ADD_SPHERICAL_JOINT_ACCMD,
    ADD_COMMANDS_ADD_PRIMITIVE_PLANE_ACCMD,
    ADD_COMMANDS_ADD_PRIMITIVE_DISC_ACCMD,
    ADD_COMMANDS_ADD_PRIMITIVE_RECTANGLE_ACCMD,
    ADD_COMMANDS_ADD_PRIMITIVE_SPHERE_ACCMD,
    ADD_COMMANDS_ADD_PRIMITIVE_CYLINDER_ACCMD,
    ADD_COMMANDS_ADD_DUMMY_ACCMD,
    ADD_COMMANDS_ADD_OCTREE_ACCMD,
    ADD_COMMANDS_ADD_POINTCLOUD_ACCMD,
    ADD_COMMANDS_ADD_MIRROR_ACCMD,
    ADD_COMMANDS_ADD_PATH_SEGMENT_ACCMD,
    ADD_COMMANDS_ADD_PATH_CIRCLE_ACCMD,
    ADD_COMMANDS_ADD_AND_ASSOCIATE_NON_THREADED_CHILD_SCRIPT_ACCMD,
    ADD_COMMANDS_ADD_AND_ASSOCIATE_THREADED_CHILD_SCRIPT_ACCMD,
    ADD_COMMANDS_ADD_AND_ASSOCIATE_CUSTOMIZATION_SCRIPT_ACCMD,
    ADD_COMMANDS_ADD_GRAPH_ACCMD,
    ADD_COMMANDS_ADD_ORTHOGONAL_VISION_SENSOR_ACCMD,
    ADD_COMMANDS_ADD_PERSPECTIVE_VISION_SENSOR_ACCMD,
    ADD_COMMANDS_ADD_FORCE_SENSOR_ACCMD,
    ADD_COMMANDS_ADD_RAY_PROXSENSOR_ACCMD,
    ADD_COMMANDS_ADD_PYRAMID_PROXSENSOR_ACCMD,
    ADD_COMMANDS_ADD_CYLINDER_PROXSENSOR_ACCMD,
    ADD_COMMANDS_ADD_DISC_PROXSENSOR_ACCMD,
    ADD_COMMANDS_ADD_CONE_PROXSENSOR_ACCMD,
    ADD_COMMANDS_ADD_RANDOMIZED_RAY_PROXSENSOR_ACCMD,
    ADD_COMMANDS_ADD_PYRAMID_MILL_ACCMD,
    ADD_COMMANDS_ADD_CYLINDER_MILL_ACCMD,
    ADD_COMMANDS_ADD_DISC_MILL_ACCMD,
    ADD_COMMANDS_ADD_CONE_MILL_ACCMD,
    ADD_COMMANDS_ADD_CONVEX_HULL_ACCMD,
    ADD_COMMANDS_ADD_GROWN_CONVEX_HULL_ACCMD,
    ADD_COMMANDS_ADD_CONVEX_DECOMPOSITION_ACCMD,
    ADD_COMMANDS_ADD_CAMERA_ACCMD,
    ADD_COMMANDS_ADD_OMNI_LIGHT_ACCMD,
    ADD_COMMANDS_ADD_SPOT_LIGHT_ACCMD,
    ADD_COMMANDS_ADD_DIR_LIGHT_ACCMD,
    ADD_COMMANDS_MAKE_GRAPH_CURVE_STATIC_ACCMD,

    // Add commands end;
    ADD_COMMANDS_END_ACCMD,
    //----------


    //----------
    // Script container commands start:
    SCRIPT_CONT_COMMANDS_START_SCCMD,

    SCRIPT_CONT_COMMANDS_ADDON_SCRIPT_MENU_ITEM_START_SCCMD,
    SCRIPT_CONT_COMMANDS_ADDON_SCRIPT_MENU_ITEM_END_SCCMD=SCRIPT_CONT_COMMANDS_ADDON_SCRIPT_MENU_ITEM_START_SCCMD+30,
    SCRIPT_CONT_COMMANDS_ADDON_FUNCTION_MENU_ITEM_START_SCCMD,
    SCRIPT_CONT_COMMANDS_ADDON_FUNCTION_MENU_ITEM_END_SCCMD=SCRIPT_CONT_COMMANDS_ADDON_FUNCTION_MENU_ITEM_START_SCCMD+30,

    // Script container commands end;
    SCRIPT_CONT_COMMANDS_END_SCCMD,
    //----------


    //----------
    SWITCH_TOINSTANCEWITHTHUMBNAILSAVEINDEX0_GUIGUICMD,
    SWITCH_TOINSTANCEWITHTHUMBNAILSAVEINDEX39_GUIGUICMD=SWITCH_TOINSTANCEWITHTHUMBNAILSAVEINDEX0_GUIGUICMD+39,
    //----------


    //----------
    SAVE_LAYOUT_CONFIG_BR,
    SWITCH_ONLINE_BR,
    OPEN_PACKML_BR,
    GET_QUOTE_BR,
    CREATE_JOB_BR,
    DELETE_JOB_BR,
    VERIFY_LAYOUT_BR,
    SWITCH_TO_JOB_BR,
    SWITCH_TO_JOB_END_BR=SWITCH_TO_JOB_BR+100,
    //----------


    SET_SHAPE_TRANSPARENCY_CMD,


    SOLID_DISPLAY_CMD,
    WIREFRAME_EDGES_DISPLAY_CMD,
    WIREFRAME_TRIANGLES_DISPLAY_CMD,
    BOUNDINGBOX_SOLID_DISPLAY_CMD,
    BOUNDINGBOX_WIREFRAME_DISPLAY_CMD,

    VIEW_FIT_TO_SCENE_CMD,
    VIEW_FIT_TO_SELECTION_CMD,

    COPY_GRAPH_CURVE_TO_CLIPBOARD_CMD,


    REMOVE_VIEW_CMD,
    PAGE_SELECTOR_CMD,
    SCENE_SELECTOR_CMD,
    SCENE_SELECTOR_PHASE2_CMD,

    COMPUTE_PATH_CMD,

    OPEN_GRAPH_DLG_CMD,
    OPEN_CAMERA_DLG_CMD,
    OPEN_LIGHT_DLG_CMD,
    OPEN_MIRROR_DLG_CMD,
    OPEN_SHAPE_DLG_CMD,
    OPEN_PROXIMITY_SENSOR_DLG_CMD,
    OPEN_VISION_SENSOR_DLG_CMD,
    OPEN_MILL_DLG_CMD,

    OPEN_SHAPE_EDITION_DLG_CMD,
    OPEN_SHAPE_EDIT_MODE_TRIANGLE_PART_CMD,
    OPEN_SHAPE_EDIT_MODE_VERTEX_PART_CMD,
    OPEN_SHAPE_EDIT_MODE_EDGE_PART_CMD,

    CLOSE_SHAPE_EDITION_DLG_CMD,

    OPEN_PATH_EDITION_DLG_CMD,
    CLOSE_PATH_EDITION_DLG_CMD,

    OPEN_OBJECT_DLG_CMD,
    OPEN_OBJECT_DLG_OBJECT_SPECIFIC_PART_CMD,
    OPEN_CALCULATION_DLG_CMD,

    OPEN_FORCE_SENSOR_DLG_CMD,
    OPEN_DUMMY_DLG_CMD,
    OPEN_JOINT_DLG_CMD,
    OPEN_PATH_DLG_CMD,
    OPEN_BUTTON_DLG_CMD,
    OPEN_ENVIRONMENT_DLG_CMD,
    OPEN_FOG_DLG_CMD,
    OPEN_CUSTOM_UI_DLG_CMD,
    CLOSE_CUSTOM_UI_DLG_CMD,
    OPEN_MULTISHAPE_EDITION_DLG_CMD,
    CLOSE_MULTISHAPE_EDITION_DLG_CMD,

    TOGGLE_GENERAL_PROPERTIES_DLG_CMD,
    TOGGLE_GRAPH_DLG_CMD,
    TOGGLE_COLLECTION_DLG_CMD,
    TOGGLE_CAMERA_DLG_CMD,
    TOGGLE_LIGHT_DLG_CMD,
    TOGGLE_MIRROR_DLG_CMD,
    TOGGLE_COLLISION_DLG_CMD,
    TOGGLE_SELECTION_DLG_CMD,
    TOGGLE_SHAPE_DLG_CMD,
    TOGGLE_PROXIMITY_SENSOR_DLG_CMD,
    TOGGLE_VISION_SENSOR_DLG_CMD,
    TOGGLE_MILL_DLG_CMD,
    TOGGLE_FORCE_SENSOR_DLG_CMD,
    TOGGLE_LUA_SCRIPT_DLG_CMD,
    TOGGLE_SETTINGS_DLG_CMD,
    TOGGLE_DUMMY_DLG_CMD,
    TOGGLE_DISTANCE_DLG_CMD,
    TOGGLE_JOINT_DLG_CMD,
    TOGGLE_ENVIRONMENT_DLG_CMD,
    TOGGLE_IK_DLG_CMD,
    TOGGLE_BUTTON_DLG_CMD,
    TOGGLE_HIERARCHY_DLG_CMD,
    OPEN_HIERARCHY_DLG_CMD,
    CLOSE_HIERARCHY_DLG_CMD,
    TOGGLE_BROWSER_DLG_CMD,
    TOGGLE_LAYERS_DLG_CMD,
    TOGGLE_DYNAMICS_DLG_CMD,
    TOGGLE_PATH_DLG_CMD,
    TOGGLE_OBJECT_DLG_CMD,
    TOGGLE_CALCULATION_DLG_CMD,
    TOGGLE_PATH_PLANNING_DLG_CMD,
    TOGGLE_CONSTRAINT_SOLVER_DLG_CMD,
    TOGGLE_SIMULATION_DLG_CMD,
    TOGGLE_INTERACTIVE_IK_DLG_CMD,
    TOGGLE_AVI_RECORDER_DLG_CMD,


    //---------
    FILE_OPERATION_START_FOCMD,

    FILE_OPERATION_OPEN_SCENE_FOCMD,
    FILE_OPERATION_OPEN_SCENE_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE0_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE1_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE3_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE4_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE5_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE6_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE7_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE8_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE9_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE0_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE1_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE2_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE3_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE4_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE5_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE6_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE7_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE8_PHASE2_FOCMD,
    FILE_OPERATION_OPEN_RECENT_SCENE9_PHASE2_FOCMD,
    FILE_OPERATION_CLOSE_SCENE_FOCMD,
    FILE_OPERATION_NEW_SCENE_FOCMD,
    FILE_OPERATION_NEW_SCENE_PHASE2_FOCMD,
    FILE_OPERATION_LOAD_MODEL_FOCMD,
    FILE_OPERATION_SAVE_SCENE_FOCMD,
    FILE_OPERATION_SAVE_SCENE_AS_VREP_FOCMD,
    FILE_OPERATION_SAVE_SCENE_AS_BR_FOCMD,
    FILE_OPERATION_EXPORT_IK_CONTENT_FOCMD,
    FILE_OPERATION_SAVE_MODEL_AS_VREP_FOCMD,
    FILE_OPERATION_SAVE_MODEL_AS_BR_FOCMD,
    FILE_OPERATION_IMPORT_MESH_FOCMD,
    FILE_OPERATION_IMPORT_PATH_FOCMD,
    FILE_OPERATION_IMPORT_HEIGHTFIELD_FOCMD,
    FILE_OPERATION_EXPORT_SHAPE_FOCMD,
    FILE_OPERATION_EXPORT_GRAPHS_FOCMD,
    FILE_OPERATION_EXPORT_PATH_SIMPLE_POINTS_FOCMD,
    FILE_OPERATION_EXPORT_PATH_BEZIER_POINTS_FOCMD,
    FILE_OPERATION_EXPORT_DYNAMIC_CONTENT_FOCMD,
    FILE_OPERATION_EXIT_SIMULATOR_FOCMD,
    FILE_OPERATION_OPEN_DRAG_AND_DROP_MODEL_FOCMD,

    FILE_OPERATION_END_FOCMD,
    //---------


    CAMERA_SHIFT_TO_FRAME_SELECTION_CMD,
    CAMERA_SHIFT_NAVIGATION_CMD,
    CAMERA_ROTATE_NAVIGATION_CMD,
    CAMERA_ZOOM_NAVIGATION_CMD,
    CAMERA_TILT_NAVIGATION_CMD,
    CAMERA_ANGLE_NAVIGATION_CMD,
    CAMERA_FLY_NAVIGATION_CMD,
    OBJECT_SHIFT_NAVIGATION_CMD,
    OBJECT_ROTATE_NAVIGATION_CMD,
    OBJECT_SELECTION_SELECTION_CMD,
    CLEAR_SELECTION_SELECTION_CMD,
    PATH_POINT_CREATION_MODE_CMD,

    VIEW_1_CMD,
    VIEW_2_CMD,
    VIEW_3_CMD,
    VIEW_4_CMD,
    VIEW_5_CMD,
    VIEW_6_CMD,
    VIEW_7_CMD,
    VIEW_8_CMD,


    ADDITIONAL_TOOL_MENU_ITEM_START_CMD,
    ADDITIONAL_TOOL_MENU_ITEM_END_CMD=ADDITIONAL_TOOL_MENU_ITEM_START_CMD+100,

    EXPAND_HIERARCHY_CMD,
    COLLAPSE_HIERARCHY_CMD,
    EXPAND_SELECTED_HIERARCHY_CMD,
    COLLAPSE_SELECTED_HIERARCHY_CMD,

    HIERARCHY_COLORING_NONE_CMD,
    HIERARCHY_COLORING_RED_CMD,
    HIERARCHY_COLORING_GREEN_CMD,
    HIERARCHY_COLORING_BLUE_CMD,


    DISPLAY_MESSAGE_CMD,


    SET_SHAPE_SHADING_ANGLE_CMD,
    SET_SHAPE_EDGE_ANGLE_CMD,

    HELP_TOPICS_CMD,
    ABOUT_CMD,
    CREDITS_CMD,
    ENTER_KEY_CMD,


    SHOW_INTERNAL_FUNCTION_ACCESS_DEBUG_CMD,
    SHOW_C_API_ACCESS_DEBUG_CMD,
    SHOW_LUA_API_ACCESS_DEBUG_CMD,
    DEBUG_TO_FILE_DEBUG_CMD,
    DISABLE_FRUSTUM_CULLING_DEBUG_CMD,
    DISABLE_DISTANCE_CACHING_DEBUG_CMD,
    VISUALIZE_OBB_STRUCTURE_DEBUG_CMD,

    CLICK_RAY_INTERSECTION_CMD,
    SWAP_VIEWS_CMD,
    MODEL_BROWSER_DRAG_AND_DROP_CMD,
    OPEN_DRAG_AND_DROP_SCENE_CMD,
    OPEN_DRAG_AND_DROP_SCENE_PHASE2_CMD,
    DISPLAY_ACKNOWLEDGMENT_MESSAGE_CMD,
    POSTPONE_PROCESSING_THIS_LOOP_CMD,
    TOGGLE_EXPAND_COLLAPSE_HIERARCHY_OBJECT_CMD,
    ADD_OR_REMOVE_TO_FROM_OBJECT_SELECTION_CMD,
    OPEN_SCRIPT_EDITOR_CMD,
    OPEN_MODAL_SCRIPT_SIMULATION_PARAMETERS_CMD,
    OPEN_MODAL_MODEL_PROPERTIES_CMD,
    MAKE_OBJECT_CHILD_OF_CMD,
    CLOSE_FLOATING_VIEW_CMD,
    REMOVE_CURRENT_PAGE_CMD,
    AUTO_SAVE_SCENE_CMD,
    MEMORIZE_UNDO_STATE_IF_NEEDED_CMD,
    REFRESH_DIALOGS_CMD,
    DISPLAY_VARIOUS_WARNING_MESSAGES_DURING_SIMULATION_CMD,
    DISPLAY_WARNING_IF_DEBUGGING_CMD,
    FINAL_EXIT_REQUEST_CMD,

    START_GUITRIGGEREDCMD,

    SET_VIEW_ANGLE_CAMERAGUITRIGGEREDCMD,
    SET_ORTHO_VIEW_SIZE_CAMERAGUITRIGGEREDCMD,
    SET_NEAR_CLIPPING_CAMERAGUITRIGGEREDCMD,
    SET_FAR_CLIPPING_CAMERAGUITRIGGEREDCMD,
    SET_TRACKED_OBJECT_CAMERAGUITRIGGEREDCMD,
    TOGGLE_SHOWFOG_CAMERAGUITRIGGEREDCMD,
    TOGGLE_KEEPHEADUP_CAMERAGUITRIGGEREDCMD,
    TOGGLE_USEPARENTASMANIPPROXY_CAMERAGUITRIGGEREDCMD,
    TOGGLE_SHIFTALONGX_CAMERAGUITRIGGEREDCMD,
    TOGGLE_SHIFTALONGY_CAMERAGUITRIGGEREDCMD,
    TOGGLE_SHIFTALONGZ_CAMERAGUITRIGGEREDCMD,
    TOGGLE_FULLROTATION_CAMERAGUITRIGGEREDCMD,
    TOGGLE_TILTING_CAMERAGUITRIGGEREDCMD,
    SET_SIZE_CAMERAGUITRIGGEREDCMD,
    TOGGLE_LOCALLIGHTS_CAMERAGUITRIGGEREDCMD,
    TOGGLE_ALLOWPICKING_CAMERAGUITRIGGEREDCMD,
    SET_RENDERMODE_CAMERAGUITRIGGEREDCMD,

    NEW_COLLECTION_COLLECTIONGUITRIGGEREDCMD,
    TOGGLE_OVERRIDE_COLLECTIONGUITRIGGEREDCMD,
    REMOVE_COLLECTION_COLLECTIONGUITRIGGEREDCMD,
    REMOVE_COLLECTION_ITEM_COLLECTIONGUITRIGGEREDCMD,
    RENAME_COLLECTION_COLLECTIONGUITRIGGEREDCMD,
    ADD_COLLECTION_ITEM_EVERYTHING_COLLECTIONGUITRIGGEREDCMD,
    ADD_COLLECTION_ITEM_LOOS_COLLECTIONGUITRIGGEREDCMD,
    ADD_COLLECTION_ITEM_FROMBASE_COLLECTIONGUITRIGGEREDCMD,
    ADD_COLLECTION_ITEM_FROMTIP_COLLECTIONGUITRIGGEREDCMD,

    TOGGLE_ENABLE_ALL_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_EXTERNALINPUT_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_PERSPECTIVE_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_IGNORERGB_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_IGNOREDEPTH_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_PACKET1BLANK_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_LOCALLIGHTS_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_SHOWFOG_VISIONSENSORGUITRIGGEREDCMD,
    SET_RENDERMODE_VISIONSENSORGUITRIGGEREDCMD,
    SET_NEARCLIPPING_VISIONSENSORGUITRIGGEREDCMD,
    SET_FARCLIPPING_VISIONSENSORGUITRIGGEREDCMD,
    SET_PERSPECTANGLE_OR_ORTHOSIZE_VISIONSENSORGUITRIGGEREDCMD,
    SET_RESOLUTION_VISIONSENSORGUITRIGGEREDCMD,
    SET_ENTITYTODETECT_VISIONSENSORGUITRIGGEREDCMD,
    APPLY_MAINPROP_TO_SELECTION_VISIONSENSORGUITRIGGEREDCMD,
    SET_OBJECTSIZE_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_SHOWVOLUME_WHEN_NOT_DETECTING_VISIONSENSORGUITRIGGEREDCMD,
    TOGGLE_SHOWVOLUME_WHEN_DETECTING_VISIONSENSORGUITRIGGEREDCMD,
    APPLY_VISUALPROP_TO_SELECTION_VISIONSENSORGUITRIGGEREDCMD,
    SET_DEFAULTIMGCOL_VISIONSENSORGUITRIGGEREDCMD,

    TOGGLE_ENABLE_ALL_COLLISIONGUITRIGGEREDCMD,
    ADD_NEW_COLLISIONGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_COLLISIONGUITRIGGEREDCMD,
    TOGGLE_COLLIDERCOLORCHANGES_COLLISIONGUITRIGGEREDCMD,
    TOGGLE_COLLIDEECOLORCHANGES_COLLISIONGUITRIGGEREDCMD,
    TOGGLE_COLLISIONCONTOUR_COLLISIONGUITRIGGEREDCMD,
    SET_CONTOURWIDTH_COLLISIONGUITRIGGEREDCMD,
    SET_OBJECTNAME_COLLISIONGUITRIGGEREDCMD,
    DELETE_OBJECT_COLLISIONGUITRIGGEREDCMD,

    TOGGLE_ENABLE_ALL_DISTANCEGUITRIGGEREDCMD,
    ADD_NEW_DISTANCEGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_DISTANCEGUITRIGGEREDCMD,
    TOGGLE_SEGMENTDISPLAY_DISTANCEGUITRIGGEREDCMD,
    TOGGLE_USETHRESHOLD_DISTANCEGUITRIGGEREDCMD,
    SET_SEGMENTWIDTH_DISTANCEGUITRIGGEREDCMD,
    SET_OBJECTNAME_DISTANCEGUITRIGGEREDCMD,
    SET_THRESHOLD_DISTANCEGUITRIGGEREDCMD,
    DELETE_OBJECT_DISTANCEGUITRIGGEREDCMD,

    TOGGLE_SELECTABLE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_SELECTINVISIBLE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_SELECTBASEOFMODEL_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_DEPTHMAPIGNORED_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_CANNOTBEDELETED_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_CANNOTBEDELETEDDURINGSIMULATION_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_DONGTSHOWINSIDEMODELSELECTION_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_VIEWFITTINGIGNORED_COMMONPROPGUITRIGGEREDCMD,
    SET_EXTENSIONSTRING_COMMONPROPGUITRIGGEREDCMD,
    APPLY_GENERALPROP_COMMONPROPGUITRIGGEREDCMD,
    SET_CAMERAVISIBILITYLAYERS_COMMONPROPGUITRIGGEREDCMD,
    SET_CANBESEENBY_COMMONPROPGUITRIGGEREDCMD,
    APPLY_VISIBILITYPROP_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_COLLIDABLE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_MEASURABLE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_DETECTABLE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_RENDERABLE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_CUTTABLE_COMMONPROPGUITRIGGEREDCMD,
    SET_DETECTABLEITEMS_COMMONPROPGUITRIGGEREDCMD,
    APPLY_SPECIALPROP_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_MODELBASE_COMMONPROPGUITRIGGEREDCMD,
    TOGGLE_CANTRANSFERDNA_COMMONPROPGUITRIGGEREDCMD,
    SET_SELFCOLLISIONINDICATOR_COMMONPROPGUITRIGGEREDCMD,

    TOGGLE_ENABLEALL_PROXSENSORGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_PROXSENSORGUITRIGGEREDCMD,
    SET_SENSORSUBTYPE_PROXSENSORGUITRIGGEREDCMD,
    SET_ENTITYTODETECT_PROXSENSORGUITRIGGEREDCMD,
    APPLY_MAINPROP_PROXSENSORGUITRIGGEREDCMD,
    TOGGLE_SHOWVOLWHENDETECTING_PROXSENSORGUITRIGGEREDCMD,
    TOGGLE_SHOWVOLWHENNOTDETECTING_PROXSENSORGUITRIGGEREDCMD,
    SET_POINTSIZE_PROXSENSORGUITRIGGEREDCMD,
    APPLY_VISUALPROP_PROXSENSORGUITRIGGEREDCMD,
    SET_DETECTIONPARAMS_PROXSENSORGUITRIGGEREDCMD,

    SET_TYPE_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_OFFSET_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_RANGE_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_XSIZE_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_YSIZE_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_XSIZEFAR_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_YSIZEFAR_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_INSIDEGAP_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_RADIUS_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_RADIUSFAR_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_ANGLE_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_FACECOUNT_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_FACECOUNTFAR_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_SUBDIVISIONS_DETECTIONVOLUMEGUITRIGGEREDCMD,
    SET_SUBDIVISIONSFAR_DETECTIONVOLUMEGUITRIGGEREDCMD,
    APPLY_DETECTIONVOLUMEGUITRIGGEREDCMD,


    TOGGLE_ENABLEALL_MILLGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_MILLGUITRIGGEREDCMD,
    SET_ENTITYTOCUT_MILLGUITRIGGEREDCMD,
    SET_SIZE_MILLGUITRIGGEREDCMD,


    TOGGLE_ENABLED_LIGHTGUITRIGGEREDCMD,
    TOGGLE_LIGHTISLOCAL_LIGHTGUITRIGGEREDCMD,
    SET_SPOTCUTOFF_LIGHTGUITRIGGEREDCMD,
    SET_SPOTEXPONENT_LIGHTGUITRIGGEREDCMD,
    SET_CONSTATTENUATION_LIGHTGUITRIGGEREDCMD,
    SET_LINATTENUATION_LIGHTGUITRIGGEREDCMD,
    SET_QUADATTENUATION_LIGHTGUITRIGGEREDCMD,
    SET_SIZE_LIGHTGUITRIGGEREDCMD,


    SET_LINKEDDUMMY_DUMMYGUITRIGGEREDCMD,
    SET_LINKTYPE_DUMMYGUITRIGGEREDCMD,
    TOGGLE_FOLLOWORIENTATION_DUMMYGUITRIGGEREDCMD,
    TOGGLE_FOLLOWPOSITION_DUMMYGUITRIGGEREDCMD,
    SET_FREEORFIXEDONPATH_DUMMYGUITRIGGEREDCMD,
    SET_OFFSET_DUMMYGUITRIGGEREDCMD,
    SET_COPYINCREMENT_DUMMYGUITRIGGEREDCMD,
    SET_SIZE_DUMMYGUITRIGGEREDCMD,
    APPLY_VISUALPROP_DUMMYGUITRIGGEREDCMD,

    TOGGLE_DISABLEALLMIRRORS_MIRRORGUITRIGGEREDCMD,
    TOGGLE_DISABLEALLCLIPPING_MIRRORGUITRIGGEREDCMD,
    TOGGLE_ENABLED_MIRRORGUITRIGGEREDCMD,
    SET_MIRRORFUNC_MIRRORGUITRIGGEREDCMD,
    SET_CLIPPINGFUNC_MIRRORGUITRIGGEREDCMD,
    SET_REFLECTANCE_MIRRORGUITRIGGEREDCMD,
    SET_CLIPPINGENTITY_MIRRORGUITRIGGEREDCMD,
    SET_WIDTH_MIRRORGUITRIGGEREDCMD,
    SET_HEIGHT_MIRRORGUITRIGGEREDCMD,

    SET_MAXTRIANGLESIZE_ENVIRONMENTGUITRIGGEREDCMD,
    SET_MINTRIANGLESIZE_ENVIRONMENTGUITRIGGEREDCMD,
    TOGGLE_SAVECALCSTRUCT_ENVIRONMENTGUITRIGGEREDCMD,
    TOGGLE_SHAPETEXTURES_ENVIRONMENTGUITRIGGEREDCMD,
    TOGGLE_GLUITEXTURES_ENVIRONMENTGUITRIGGEREDCMD,
    TOGGLE_LOCKSCENE_ENVIRONMENTGUITRIGGEREDCMD,
    SET_EXTSTRING_ENVIRONMENTGUITRIGGEREDCMD,
    CLEANUP_OBJNAMES_ENVIRONMENTGUITRIGGEREDCMD,
    CLEANUP_GHOSTS_ENVIRONMENTGUITRIGGEREDCMD,
    SET_ACKNOWLEDGMENT_ENVIRONMENTGUITRIGGEREDCMD,

    SET_SHADINGANGLE_MULTISHAPEEDITIONGUITRIGGEREDCMD,
    SET_EDGEANGLE_MULTISHAPEEDITIONGUITRIGGEREDCMD,
    TOGGLE_SHOWEDGES_MULTISHAPEEDITIONGUITRIGGEREDCMD,
    TOGGLE_HIDDENBORDER_MULTISHAPEEDITIONGUITRIGGEREDCMD,
    TOGGLE_BACKFACECULLING_MULTISHAPEEDITIONGUITRIGGEREDCMD,
    TOGGLE_WIREFRAME_MULTISHAPEEDITIONGUITRIGGEREDCMD,

    TOGGLE_ENABLED_FOGGUITRIGGEREDCMD,
    SET_TYPE_FOGGUITRIGGEREDCMD,
    SET_START_FOGGUITRIGGEREDCMD,
    SET_END_FOGGUITRIGGEREDCMD,
    SET_DENSITY_FOGGUITRIGGEREDCMD,

    SET_ITEMRGB_COLORGUITRIGGEREDCMD,

    SET_OBJECT_SELECTION_GUITRIGGEREDCMD,
    CLEAR_OBJECT_SELECTION_GUITRIGGEREDCMD,
    ADD_OBJECTS_TO_SELECTION_GUITRIGGEREDCMD,
    INVERT_SELECTION_GUITRIGGEREDCMD,
    POST_SCENE_CHANGED_ANNOUNCEMENT_GUITRIGGEREDCMD,
    FULLREFRESH_ALL_DIALOGS_GUITRIGGEREDCMD,
    CALL_DIALOG_FUNCTION_GUITRIGGEREDCMD,
    FULLREFRESH_HIERARCHY_GUITRIGGEREDCMD,
    REFRESH_TOOLBARS_GUITRIGGEREDCMD,

    SET_ROLLEDUPSIZES_ROLLEDUPGUITRIGGEREDCMD,


    SCALE_SCALINGGUITRIGGEREDCMD,

    SET_OVERRIDEPROPANDACKNOWLEDGMENT_MODELGUITRIGGEREDCMD,

    SET_TIMESTEPSCHEME_SIMULATIONGUITRIGGEREDCMD,
    SET_TIMESTEP_SIMULATIONGUITRIGGEREDCMD,
    SET_PPF_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_PAUSEATTIME_SIMULATIONGUITRIGGEREDCMD,
    SET_PAUSETIME_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_PAUSEATERROR_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_FULLSCREENATSTART_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_REALTIME_SIMULATIONGUITRIGGEREDCMD,
    SET_REALTIMEFACTOR_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_TRYCATCHINGUP_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_RESETSCENETOINITIAL_SIMULATIONGUITRIGGEREDCMD,
    TOGGLE_REMOVENEWOBJECTS_SIMULATIONGUITRIGGEREDCMD,

    SET_OFFFSET_JOINTDEPENDENCYGUITRIGGEREDCMD,
    SET_MULTFACT_JOINTDEPENDENCYGUITRIGGEREDCMD,
    SET_OTHERJOINT_JOINTDEPENDENCYGUITRIGGEREDCMD,

    TOGGLE_CYCLIC_JOINTGUITRIGGEREDCMD,
    SET_PITCH_JOINTGUITRIGGEREDCMD,
    SET_MINPOS_JOINTGUITRIGGEREDCMD,
    SET_RANGE_JOINTGUITRIGGEREDCMD,
    SET_POS_JOINTGUITRIGGEREDCMD,
    SET_IKWEIGHT_JOINTGUITRIGGEREDCMD,
    SET_MAXSTEPSIZE_JOINTGUITRIGGEREDCMD,
    APPLY_CONFIGPARAMS_JOINTGUITRIGGEREDCMD,
    SET_MODE_JOINTGUITRIGGEREDCMD,
    TOGGLE_HYBRID_JOINTGUITRIGGEREDCMD,
    APPLY_MODEPARAMS_JOINTGUITRIGGEREDCMD,
    SET_LENGTH_JOINTGUITRIGGEREDCMD,
    SET_DIAMETER_JOINTGUITRIGGEREDCMD,
    APPLY_VISUALPARAMS_JOINTGUITRIGGEREDCMD,

    TOGGLE_MOTORENABLED_JOINTDYNGUITRIGGEREDCMD,
    SET_TARGETVELOCITY_JOINTDYNGUITRIGGEREDCMD,
    SET_MAXFORCE_JOINTDYNGUITRIGGEREDCMD,
    TOGGLE_LOCKMOTOR_JOINTDYNGUITRIGGEREDCMD,
    APPLY_MOTORPARAMS_JOINTDYNGUITRIGGEREDCMD,
    TOGGLE_CTRLLOOP_JOINTDYNGUITRIGGEREDCMD,
    SET_TARGETPOSITION_JOINTDYNGUITRIGGEREDCMD,
    SET_UPPERVELLIMIT_JOINTDYNGUITRIGGEREDCMD,
    SELECT_PIDCTRL_JOINTDYNGUITRIGGEREDCMD,
    SELECT_SPRINGDAMPERCTRL_JOINTDYNGUITRIGGEREDCMD,
    SET_PIDVALUES_JOINTDYNGUITRIGGEREDCMD,
    SET_KCVALUES_JOINTDYNGUITRIGGEREDCMD,
    APPLY_CTRLPARAMS_JOINTDYNGUITRIGGEREDCMD,
    SET_ALLENGINEPARAMS_JOINTDYNGUITRIGGEREDCMD,
    APPLY_ALLENGINEPARAMS_JOINTDYNGUITRIGGEREDCMD,

    SET_DISTANCEUNIT_PATHGUITRIGGEREDCMD,
    SET_ATTRIBUTES_PATHGUITRIGGEREDCMD,
    SET_LINESIZE_PATHGUITRIGGEREDCMD,
    SET_CTRLPTSIZE_PATHGUITRIGGEREDCMD,

    TOGGLE_SHAPINGENABLED_PATHSHAPINGGUITRIGGEREDCMD,
    TOGGLE_FOLLOWORIENTATION_PATHSHAPINGGUITRIGGEREDCMD,
    TOGGLE_CONVEXHULLS_PATHSHAPINGGUITRIGGEREDCMD,
    GENERATE_SHAPE_PATHSHAPINGGUITRIGGEREDCMD,
    SET_ELEMENTMAXLENGTH_PATHSHAPINGGUITRIGGEREDCMD,
    SET_TYPE_PATHSHAPINGGUITRIGGEREDCMD,
    TOGGLE_LASTCOORDLINKSTOFIRST_PATHSHAPINGGUITRIGGEREDCMD,
    SET_SCALINGFACTOR_PATHSHAPINGGUITRIGGEREDCMD,
    SET_COORDINATES_PATHSHAPINGGUITRIGGEREDCMD,

    TOGGLE_DYNAMICS_DYNAMICSGUITRIGGEREDCMD,
    TOGGLE_DISPLAYCONTACTS_DYNAMICSGUITRIGGEREDCMD,
    SET_GRAVITY_DYNAMICSGUITRIGGEREDCMD,
    SET_ENGINE_DYNAMICSGUITRIGGEREDCMD,
    SET_ALLGLOBALPARAMS_DYNAMICSGUITRIGGEREDCMD,

    TOGGLE_RESPONDABLE_SHAPEDYNGUITRIGGEREDCMD,
    SET_RESPONDABLEMASK_SHAPEDYNGUITRIGGEREDCMD,
    SET_MATERIAL_SHAPEDYNGUITRIGGEREDCMD,
    DUPLICATE_MATERIAL_SHAPEDYNGUITRIGGEREDCMD,
    SET_ENGINEPARAMS_SHAPEDYNGUITRIGGEREDCMD,
    APPLY_RESPONDABLEPARAMS_SHAPEDYNGUITRIGGEREDCMD,
    TOGGLE_STATIC_SHAPEDYNGUITRIGGEREDCMD,
    TOGGLE_STARTINSLEEPMODE_SHAPEDYNGUITRIGGEREDCMD,
    TOGGLE_SETTODYNAMICIFGETSPARENT_SHAPEDYNGUITRIGGEREDCMD,
    COMPUTE_MASSANDINERTIA_SHAPEDYNGUITRIGGEREDCMD,
    SET_MASS_SHAPEDYNGUITRIGGEREDCMD,
    MULTIPLY_MASSFORSELECTION_SHAPEDYNGUITRIGGEREDCMD,
    SET_PRINCIPALMOMENTOFINTERIA_SHAPEDYNGUITRIGGEREDCMD,
    MULTIPLY_INERTIAFORSELECTION_SHAPEDYNGUITRIGGEREDCMD,
    SET_COMMATRIX_SHAPEDYNGUITRIGGEREDCMD,
    APPLY_DYNPARAMS_SHAPEDYNGUITRIGGEREDCMD,

    SET_VOXELSIZE_OCTREEGUITRIGGEREDCMD,
    INSERT_SELECTEDVISIBLEOBJECTS_OCTREEGUITRIGGEREDCMD,
    SUBTRACT_SELECTEDVISIBLEOBJECTS_OCTREEGUITRIGGEREDCMD,
    CLEAR_OCTREEGUITRIGGEREDCMD,
    SET_POINTSIZE_OCTREEGUITRIGGEREDCMD,
    TOGGLE_RANDOMCOLORS_OCTREEGUITRIGGEREDCMD,
    TOGGLE_SHOWSTRUCTURE_OCTREEGUITRIGGEREDCMD,
    TOGGLE_COLOREMISSIVE_OCTREEGUITRIGGEREDCMD,
    TOGGLE_SHOWPOINTS_OCTREEGUITRIGGEREDCMD,

    TOGGLE_USEOCTREE_PTCLOUDGUITRIGGEREDCMD,
    SET_MAXVOXELSIZE_PTCLOUDGUITRIGGEREDCMD,
    SET_MAXPTCNT_PTCLOUDGUITRIGGEREDCMD,
    INSERT_OBJECTS_PTCLOUDGUITRIGGEREDCMD,
    SUBTRACT_OBJECTS_PTCLOUDGUITRIGGEREDCMD,
    SET_INSERTTOLERANCE_PTCLOUDGUITRIGGEREDCMD,
    SET_SUBTRACTTOLERANCE_PTCLOUDGUITRIGGEREDCMD,
    SET_BUILDRESOLUTION_PTCLOUDGUITRIGGEREDCMD,
    CLEAR_PTCLOUDGUITRIGGEREDCMD,
    TOGGLE_RANDOMCOLORS_PTCLOUDGUITRIGGEREDCMD,
    TOGGLE_SHOWOCTREE_PTCLOUDGUITRIGGEREDCMD,
    TOGGLE_EMISSIVECOLOR_PTCLOUDGUITRIGGEREDCMD,
    SET_DISPLAYRATIO_PTCLOUDGUITRIGGEREDCMD,
    SET_PTSIZE_PTCLOUDGUITRIGGEREDCMD,

    SET_SAMPLESIZE_FORCESENSORGUITRIGGEREDCMD,
    SET_AVERAGEVALUE_FORCESENSORGUITRIGGEREDCMD,
    SET_MEDIANVALUE_FORCESENSORGUITRIGGEREDCMD,
    APPLY_FILER_FORCESENSORGUITRIGGEREDCMD,
    TOGGLE_FORCETHRESHOLDENABLE_FORCESENSORGUITRIGGEREDCMD,
    TOGGLE_TORQUETHRESHOLDENABLE_FORCESENSORGUITRIGGEREDCMD,
    SET_FORCETHRESHOLD_FORCESENSORGUITRIGGEREDCMD,
    SET_TORQUETHRESHOLD_FORCESENSORGUITRIGGEREDCMD,
    SET_CONSECTHRESHOLDVIOLATIONS_FORCESENSORGUITRIGGEREDCMD,
    APPLY_BREAKING_FORCESENSORGUITRIGGEREDCMD,
    SET_SIZE_FORCESENSORGUITRIGGEREDCMD,
    APPLY_VISUALPROP_FORCESENSORGUITRIGGEREDCMD,

    APPLY_VISUALPROP_SHAPEGUITRIGGEREDCMD,
    SET_SHADINGANGLE_SHAPEGUITRIGGEREDCMD,
    TOGGLE_SHOWEDGES_SHAPEGUITRIGGEREDCMD,
    SET_EDGEANGLE_SHAPEGUITRIGGEREDCMD,
    TOGGLE_HIDEEDGEBORDERS_SHAPEGUITRIGGEREDCMD,
    TOGGLE_BACKFACECULLING_SHAPEGUITRIGGEREDCMD,
    TOGGLE_WIREFRAME_SHAPEGUITRIGGEREDCMD,
    APPLY_OTHERPROP_SHAPEGUITRIGGEREDCMD,
    INVERT_FACES_SHAPEGUITRIGGEREDCMD,
    CLEAR_TEXTURES_SHAPEGUITRIGGEREDCMD,
    SET_QUICKTEXTURES_SHAPEGUITRIGGEREDCMD,

    SET_ALL_SCRIPTSIMULPARAMETERGUITRIGGEREDCMD,

    TOGGLE_ENABLEALL_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    INSERT_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    REMOVE_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    RENAME_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_MAXITERATIONS_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_INTERPOLATION_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_DAMPING_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_MAXLINVARIATION_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_MAXANGVARIATION_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_LOOPCLOSUREPOSTOL_GEOMCONSTRSOLVERGUITRIGGEREDCMD,
    SET_LOOPCLOSUREANGTOL_GEOMCONSTRSOLVERGUITRIGGEREDCMD,

    TOGGLE_EXPLICITHANDLING_GRAPHGUITRIGGEREDCMD,
    TOGGLE_BUFFERCYCLIC_GRAPHGUITRIGGEREDCMD,
    TOGGLE_SHOWXYZPLANES_GRAPHGUITRIGGEREDCMD,
    TOGGLE_TIMEGRAPHVISIBLE_GRAPHGUITRIGGEREDCMD,
    TOGGLE_TIMEGRAPHSHOWLABEL_GRAPHGUITRIGGEREDCMD,
    TOGGLE_TIMEGRAPHLINKPOINTS_GRAPHGUITRIGGEREDCMD,
    SET_OBJECTSIZE_GRAPHGUITRIGGEREDCMD,
    SET_BUFFERSIZE_GRAPHGUITRIGGEREDCMD,
    SET_VALUEMULTIPLIER_GRAPHGUITRIGGEREDCMD,
    SET_VALUEOFFSET_GRAPHGUITRIGGEREDCMD,
    SET_MOVINGAVERAGEPERIOD_GRAPHGUITRIGGEREDCMD,
    REMOVE_ALLSTATICCURVES_GRAPHGUITRIGGEREDCMD,
    INSERT_DATASTREAM_GRAPHGUITRIGGEREDCMD,
    REMOVE_DATASTREAM_GRAPHGUITRIGGEREDCMD,
    RENAME_DATASTREAM_GRAPHGUITRIGGEREDCMD,
    SET_VALUERAWSTATE_GRAPHGUITRIGGEREDCMD,
    DUPLICATE_TOSTATIC_GRAPHGUITRIGGEREDCMD,

    TOGGLE_VISIBLE_GRAPHCURVEGUITRIGGEREDCMD,
    TOGGLE_LABEL_GRAPHCURVEGUITRIGGEREDCMD,
    TOGGLE_LINKPTS_GRAPHCURVEGUITRIGGEREDCMD,
    TOGGLE_ONTOP_GRAPHCURVEGUITRIGGEREDCMD,
    ADD_NEWCURVE_GRAPHCURVEGUITRIGGEREDCMD,
    RENAME_CURVE_GRAPHCURVEGUITRIGGEREDCMD,
    DELETE_CURVE_GRAPHCURVEGUITRIGGEREDCMD,
    DUPLICATE_TOSTATIC_GRAPHCURVEGUITRIGGEREDCMD,
    SET_CURVEWIDTH_GRAPHCURVEGUITRIGGEREDCMD,
    SET_RELATIVETO_GRAPHCURVEGUITRIGGEREDCMD,

    SET_POSRELATIVETO_OBJECTMANIPGUITRIGGEREDCMD,
    SET_PERMISSIONS_OBJECTMANIPGUITRIGGEREDCMD,
    SET_POSSTEPSIZE_OBJECTMANIPGUITRIGGEREDCMD,
    SET_ORRELATIVETO_OBJECTMANIPGUITRIGGEREDCMD,
    SET_ORSTEPSIZE_OBJECTMANIPGUITRIGGEREDCMD,

    SAVE_USERSETTINGSGUITRIGGEREDCMD,
    SET_TRANSLATIONSTEPSIZE_USERSETTINGSGUITRIGGEREDCMD,
    SET_ROTATIONSTEPSIZE_USERSETTINGSGUITRIGGEREDCMD,
    SET_IDENTICALVERTICESTOLERANCE_USERSETTINGSGUITRIGGEREDCMD,
    SET_EXTERNALSCRIPTEDITOR_USERSETTINGSGUITRIGGEREDCMD,
    SET_OPENGLSETTINGS_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_REMOVEIDENTICALVERTICES_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_REMOVEIDENTICALTRIANGLES_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_IGNORETRIANGLEWINDING_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_SHOWWORLDREF_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_SHOWBOUNDINGBOX_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_UNDOREDO_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_HIDECONSOLE_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_AUTOSAVE_USERSETTINGSGUITRIGGEREDCMD,
    TOGGLE_HIDEHIERARCHY_USERSETTINGSGUITRIGGEREDCMD,

    SET_TRANSF_POSITIONTRANSLATIONGUITRIGGEREDCMD,
    APPLY_POS_POSITIONTRANSLATIONGUITRIGGEREDCMD,
    TRANSLATESCALE_SELECTION_POSITIONTRANSLATIONGUITRIGGEREDCMD,

    APPLY_OR_ORIENTATIONROTATIONGUITRIGGEREDCMD,
    ROTATE_SELECTION_ORIENTATIONROTATIONGUITRIGGEREDCMD,

    ADD_ELEMENT_IKELEMENTGUITRIGGEREDCMD,
    REMOVE_ELEMENT_IKELEMENTGUITRIGGEREDCMD,
    TOGGLE_ACTIVE_IKELEMENTGUITRIGGEREDCMD,
    TOGGLE_CONSTRAINT_IKELEMENTGUITRIGGEREDCMD,
    SET_BASE_IKELEMENTGUITRIGGEREDCMD,
    SET_REFERENCEFRAME_IKELEMENTGUITRIGGEREDCMD,
    SET_PRECISION_IKELEMENTGUITRIGGEREDCMD,
    SET_WEIGHT_IKELEMENTGUITRIGGEREDCMD,

    TOGGLE_ALLENABLED_IKGROUPGUITRIGGEREDCMD,
    ADD_IKGROUP_IKGROUPGUITRIGGEREDCMD,
    REMOVE_IKGROUP_IKGROUPGUITRIGGEREDCMD,
    RENAME_IKGROUP_IKGROUPGUITRIGGEREDCMD,
    SHIFT_IKGROUP_IKGROUPGUITRIGGEREDCMD,
    TOGGLE_ACTIVE_IKGROUPGUITRIGGEREDCMD,
    TOGGLE_EXPLICITHANDLING_IKGROUPGUITRIGGEREDCMD,
    TOGGLE_REDUNDANT_IKGROUPGUITRIGGEREDCMD,
    TOGGLE_IGNOREMAXSTEPSIZES_IKGROUPGUITRIGGEREDCMD,
    SET_CALCMETHOD_IKGROUPGUITRIGGEREDCMD,
    SET_DAMPING_IKGROUPGUITRIGGEREDCMD,
    SET_ITERATIONS_IKGROUPGUITRIGGEREDCMD,
    SET_CALCWEIGHT_IKGROUPGUITRIGGEREDCMD,
    SET_LIMITTHRESHOLD_IKGROUPGUITRIGGEREDCMD,
    SET_CONDITIONALPARAMS_IKGROUPGUITRIGGEREDCMD,
    SET_AVOIDANCEPARAMS_IKGROUPGUITRIGGEREDCMD,

    ADD_OBJECT_MOTIONPLANNINGGUITRIGGEREDCMD,
    REMOVE_OBJECT_MOTIONPLANNINGGUITRIGGEREDCMD,
    RENAME_OBJECT_MOTIONPLANNINGGUITRIGGEREDCMD,
    SET_ASSOCIATEDIKGROUP_MOTIONPLANNINGGUITRIGGEREDCMD,
    SET_ENTITY1_MOTIONPLANNINGGUITRIGGEREDCMD,
    SET_ENTITY2_MOTIONPLANNINGGUITRIGGEREDCMD,
    SET_COLLDIST_MOTIONPLANNINGGUITRIGGEREDCMD,
    TOGGLE_PHASE1NODES_MOTIONPLANNINGGUITRIGGEREDCMD,
    COMPUTE_PHASE1NODES_MOTIONPLANNINGGUITRIGGEREDCMD,
    SET_WORKSPACEMETRIC_MOTIONPLANNINGGUITRIGGEREDCMD,
    SET_JOINTPROPERTIES_MOTIONPLANNINGGUITRIGGEREDCMD,

    ADD_OBJECT_PATHPLANNINGGUITRIGGEREDCMD,
    REMOVE_OBJECT_PATHPLANNINGGUITRIGGEREDCMD,
    RENAME_OBJECT_PATHPLANNINGGUITRIGGEREDCMD,
    SET_GOALDUMMY_PATHPLANNINGGUITRIGGEREDCMD,
    SET_PATHOBJECT_PATHPLANNINGGUITRIGGEREDCMD,
    SET_CHECKTYPE_PATHPLANNINGGUITRIGGEREDCMD,
    SET_ROBOT_PATHPLANNINGGUITRIGGEREDCMD,
    SET_OBSTACLE_PATHPLANNINGGUITRIGGEREDCMD,
    SET_DISTANCES_PATHPLANNINGGUITRIGGEREDCMD,
    TOGGLE_USEPARTIALPATH_PATHPLANNINGGUITRIGGEREDCMD,
    TOGGLE_SHOWSEARCHEDNODES_PATHPLANNINGGUITRIGGEREDCMD,
    SET_CALCTIME_PATHPLANNINGGUITRIGGEREDCMD,
    SET_POSTPROCESSINGPASSES_PATHPLANNINGGUITRIGGEREDCMD,
    COMPUTE_PATHPLANNINGGUITRIGGEREDCMD,
    SET_VARIOUSPARAMS_PATHPLANNINGGUITRIGGEREDCMD,

    ADD_UI_OPENGLUIBLOCKGUITRIGGEREDCMD,
    RENAME_UI_OPENGLUIBLOCKGUITRIGGEREDCMD,
    SET_CELLCNT_OPENGLUIBLOCKGUITRIGGEREDCMD,
    SET_CELLSIZE_OPENGLUIBLOCKGUITRIGGEREDCMD,
    SET_UIPOSITION_OPENGLUIBLOCKGUITRIGGEREDCMD,
    SET_ATTRIBUTES_OPENGLUIBLOCKGUITRIGGEREDCMD,
    SET_DISPLAYPAGE_OPENGLUIBLOCKGUITRIGGEREDCMD,
    SET_ASSOCIATEDWITHOBJECT_OPENGLUIBLOCKGUITRIGGEREDCMD,

    INSERT_BUTTONS_OPENGLUIBUTTONGUITRIGGEREDCMD,
    INSERT_MERGEDBUTTON_OPENGLUIBUTTONGUITRIGGEREDCMD,
    SET_BUTTONHANDLE_OPENGLUIBUTTONGUITRIGGEREDCMD,
    SET_ATTRIBUTES_OPENGLUIBUTTONGUITRIGGEREDCMD,
    SET_LABEL_OPENGLUIBUTTONGUITRIGGEREDCMD,
    APPLY_BUTTONTYPE_OPENGLUIBUTTONGUITRIGGEREDCMD,
    APPLY_BUTTONLABELS_OPENGLUIBUTTONGUITRIGGEREDCMD,
    APPLY_BUTTONCOLORS_OPENGLUIBUTTONGUITRIGGEREDCMD,
    APPLY_BUTTONOTHERPROP_OPENGLUIBUTTONGUITRIGGEREDCMD,

    ADD_FILTER_VISIONSENSORFILTERGUITRIGGEREDCMD,
    DELETE_FILTER_VISIONSENSORFILTERGUITRIGGEREDCMD,
    MOVE_FILTER_VISIONSENSORFILTERGUITRIGGEREDCMD,
    TOGGLE_FILTERENABLE_VISIONSENSORFILTERGUITRIGGEREDCMD,
    APPLY_FILTERS_VISIONSENSORFILTERGUITRIGGEREDCMD,
    SET_FILTERPARAMS_VISIONSENSORFILTERGUITRIGGEREDCMD,
    SET_CUSTOMFILTERPARAMS_VISIONSENSORFILTERGUITRIGGEREDCMD,

    SELECT_REMOVE_TEXTUREGUITRIGGEREDCMD,
    LOAD_ANDAPPLY_TEXTUREGUITRIGGEREDCMD,
    SET_3DCONFIG_TEXTUREGUITRIGGEREDCMD,
    SET_SCALING_TEXTUREGUITRIGGEREDCMD,
    TOGGLE_BOOLPROP_TEXTUREGUITRIGGEREDCMD,
    SET_MAPPINGMODE_TEXTUREGUITRIGGEREDCMD,
    SET_APPLYMODE_TEXTUREGUITRIGGEREDCMD,

    INSERT_SCRIPT_SCRIPTGUITRIGGEREDCMD,
    DELETE_SCRIPT_SCRIPTGUITRIGGEREDCMD,
    TOGGLE_DISABLED_SCRIPTGUITRIGGEREDCMD,
    TOGGLE_DISABLE_CUSTOM_SCRIPT_WITH_ERROR_SCRIPTGUITRIGGEREDCMD,
    TOGGLE_EXECUTEONCE_SCRIPTGUITRIGGEREDCMD,
    SET_ASSOCIATEDOBJECT_SCRIPTGUITRIGGEREDCMD,
    SET_EXECORDER_SCRIPTGUITRIGGEREDCMD,
    SET_TREETRAVERSALDIR_SCRIPTGUITRIGGEREDCMD,
    SET_DEBUGMODE_SCRIPTGUITRIGGEREDCMD,

    APPLY_SIZE_GEOMETRYGUITRIGGEREDCMD,
    APPLY_SCALING_GEOMETRYGUITRIGGEREDCMD,
    APPLY_FRAMEROTATION_GEOMETRYGUITRIGGEREDCMD,

    TOGGLE_LAYER_LAYERGUITRIGGEREDCMD,
    TOGGLE_SHOWDYNCONTENT_LAYERGUITRIGGEREDCMD,

    SET_SHININESS_MATERIALGUITRIGGEREDCMD,
    TOGGLE_TRANSPARENCY_MATERIALGUITRIGGEREDCMD,
    SET_TRANSPARENCYFACT_MATERIALGUITRIGGEREDCMD,
    SET_NAME_MATERIALGUITRIGGEREDCMD,
    SET_EXTSTRING_MATERIALGUITRIGGEREDCMD,
    SET_PULSATIONPARAMS_MATERIALGUITRIGGEREDCMD,

    SET_CURRENTDIRECTORY_GUITRIGGEREDCMD,

    SET_THUMBNAIL_GUITRIGGEREDCMD,
    SHOW_PROGRESSDLGGUITRIGGEREDCMD,
    HIDE_PROGRESSDLGGUITRIGGEREDCMD,


    PATHEDIT_MAKEDUMMY_GUITRIGGEREDCMD,
    SHAPEEDIT_MAKESHAPE_GUITRIGGEREDCMD,
    SHAPEEDIT_MAKEPRIMITIVE_GUITRIGGEREDCMD,

    ADD_OBJECTTOSCENE_GUITRIGGEREDCMD,
    SWITCH_TOINSTANCEINDEX_GUITRIGGEREDCMD,
    SET_ACTIVEPAGE_GUITRIGGEREDCMD,
    SELECT_VIEW_GUITRIGGEREDCMD,
    SET_MOUSEMODE_GUITRIGGEREDCMD,

    END_GUITRIGGEREDCMD,

    //----------------------
    START_VREPPLUS_CMDS=9500,
    OUTSIDE_CUSTOMIZED_COMMANDS_START_CMD=10000
    // 100000-200000 for cmds from UI to SIM
    // 999995-999999 for UNDO point announcements
    //------------------------
};

enum { // color type ids, not serialized
    COLOR_ID_AMBIENT_LIGHT=0,
    COLOR_ID_BACKGROUND_UP,
    COLOR_ID_BACKGROUND_DOWN,
    COLOR_ID_FOG,
    COLOR_ID_CAMERA_A,
    COLOR_ID_CAMERA_B,
    COLOR_ID_COLLISION,
    COLOR_ID_COLLISIONCONTOUR,
    COLOR_ID_DISTANCESEGMENT,
    COLOR_ID_MIRROR,
    COLOR_ID_CLIPPINGPLANE,
    COLOR_ID_LIGHT_CASING,
    COLOR_ID_LIGHT_LIGHT,
    COLOR_ID_DUMMY,
    COLOR_ID_VISIONSENSOR_PASSIVE,
    COLOR_ID_VISIONSENSOR_ACTIVE,
    COLOR_ID_PROXSENSOR_PASSIVE,
    COLOR_ID_PROXSENSOR_ACTIVE,
    COLOR_ID_PROXSENSOR_RAY,
    COLOR_ID_PROXSENSOR_MINDIST,
    COLOR_ID_MILL_PASSIVE,
    COLOR_ID_MILL_ACTIVE,
    COLOR_ID_SHAPE,
    COLOR_ID_OCTREE,
    COLOR_ID_POINTCLOUD,
    COLOR_ID_FORCESENSOR_A,
    COLOR_ID_FORCESENSOR_B,
    COLOR_ID_SHAPE_GEOMETRY,
    COLOR_ID_JOINT_A,
    COLOR_ID_JOINT_B,
    COLOR_ID_PATH,
    COLOR_ID_PATH_SHAPING,
    COLOR_ID_GRAPH_3DCURVE,
    COLOR_ID_GRAPH_2DCURVE,
    COLOR_ID_OPENGLBUTTON_UP,
    COLOR_ID_OPENGLBUTTON_DOWN,
    COLOR_ID_OPENGLBUTTON_TEXT,
    COLOR_ID_GRAPH_BACKGROUND,
    COLOR_ID_GRAPH_GRID,
    COLOR_ID_GRAPH_TIMECURVE,
};

enum { // texture type ids, not serialized
    TEXTURE_ID_SIMPLE_SHAPE=0,
    TEXTURE_ID_COMPOUND_SHAPE,
    TEXTURE_ID_OPENGL_GUI_BACKGROUND,
    TEXTURE_ID_OPENGL_GUI_BUTTON,
};

enum { // directories, not serialized
    DIRECTORY_ID_EXECUTABLE=0,
    DIRECTORY_ID_SYSTEM,
    DIRECTORY_ID_SCENE,
    DIRECTORY_ID_MODEL,
    DIRECTORY_ID_OPENGLUI,
    DIRECTORY_ID_CADFORMAT,
    DIRECTORY_ID_TEXTURE,
    DIRECTORY_ID_OTHER,
    DIRECTORY_ID_REMOTEAPIFILETRANSFER,
};

enum { // VERY CAREFUL, FOLLOWING VALUES ARE SERIALIZED!!
    SIM_IDSTART_3DOBJECT            =0,
    SIM_IDEND_3DOBJECT              =1999999,
    SIM_IDSTART_COLLECTION          =2000000,
    SIM_IDEND_COLLECTION            =SIM_IDSTART_COLLECTION+10000,
    SIM_IDSTART_COLLISION           =SIM_IDEND_COLLECTION+1,
    SIM_IDEND_COLLISION             =SIM_IDSTART_COLLISION+10000,
    SIM_IDSTART_DISTANCE            =SIM_IDEND_COLLISION+1,
    SIM_IDEND_DISTANCE              =SIM_IDSTART_DISTANCE+10000,
    SIM_IDSTART_IKGROUP             =SIM_IDEND_DISTANCE+1,
    SIM_IDEND_IKGROUP               =SIM_IDSTART_IKGROUP+10000,
    SIM_IDSTART_GCSOBJECT           =SIM_IDEND_IKGROUP+1,
    SIM_IDEND_GCSOBJECT             =SIM_IDSTART_GCSOBJECT+10000,
    SIM_IDSTART_LUASCRIPT           =SIM_IDEND_GCSOBJECT+1,
    SIM_IDSTART_ADDONSCRIPT         =SIM_IDEND_GCSOBJECT+5000,
    SIM_IDSTART_SANDBOXSCRIPT       =SIM_IDEND_GCSOBJECT+9990,
    SIM_IDEND_LUASCRIPT             =SIM_IDSTART_LUASCRIPT+10000,
    SIM_IDSTART_2DELEMENT           =SIM_IDEND_LUASCRIPT+1,
    SIM_IDEND_2DELEMENT             =SIM_IDSTART_2DELEMENT+10000,
    SIM_IDSTART_PATHPLANNINGTASK    =SIM_IDEND_2DELEMENT+1,
    SIM_IDEND_PATHPLANNINGTASK      =SIM_IDSTART_PATHPLANNINGTASK+10000,
    SIM_IDSTART_GEOMETRIC_OLD       =SIM_IDEND_PATHPLANNINGTASK+1,
    SIM_IDEND_GEOMETRIC_OLD         =SIM_IDSTART_GEOMETRIC_OLD+100000,
    SIM_IDSTART_TEXTURE             =SIM_IDEND_GEOMETRIC_OLD+1,
    SIM_IDEND_TEXTURE               =SIM_IDSTART_TEXTURE+100000,
    SIM_IDSTART_MOTIONPLANNINGTASK  =SIM_IDEND_TEXTURE+1,
    SIM_IDEND_MOTIONPLANNINGTASK    =SIM_IDSTART_MOTIONPLANNINGTASK+10000,
    SIM_IDSTART_DYNMATERIAL_OLD     =SIM_IDEND_MOTIONPLANNINGTASK+1,
    SIM_IDEND_DYNMATERIAL_OLD       =SIM_IDSTART_DYNMATERIAL_OLD+10000,
    SIM_IDSTART_INTERFACESTACK      =SIM_IDEND_DYNMATERIAL_OLD+1,
    SIM_IDEND_INTERFACESTACK        =SIM_IDSTART_INTERFACESTACK+10000,
    SIM_IDSTART_DEFDYNMATERIAL      =SIM_IDEND_INTERFACESTACK+1, //
    SIM_IDEND_DEFDYNMATERIAL        =SIM_IDSTART_DEFDYNMATERIAL+10000,
};
