#pragma once

#include <string>
#include <interfaceStack.h>
#include <app.h>
#include <script.h>

extern std::string callMethod(int targetObj, const char* method, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
bool checkInputArguments(const CInterfaceStack* inStack, std::string* errStr, std::vector<int> inargs);

bool hasNonNullArg(const CInterfaceStack* inStack, int index);
bool fetchBool(const CInterfaceStack* inStack, int index, bool defaultValue = false);
int64_t fetchInt64(const CInterfaceStack* inStack, int index, int64_t defaultValue = -1);
int fetchInt(const CInterfaceStack* inStack, int index, int defaultValue = -1);
int64_t fetchHandle(const CInterfaceStack* inStack, int index, int64_t defaultValue = -1);
double fetchDouble(const CInterfaceStack* inStack, int index, double defaultValue = 0.0);
std::string fetchText(const CInterfaceStack* inStack, int index, const char* txt = "");
std::string fetchBuffer(const CInterfaceStack* inStack, int index);
void fetchBuffer(const CInterfaceStack* inStack, int index, std::vector<char>& buff);
void fetchColor(const CInterfaceStack* inStack, int index, float outArr[4], std::initializer_list<float> arr = {});
void fetchColor(const CInterfaceStack* inStack, int index, float outArr[4], const float defaultArr[4]);
CQuaternion fetchQuaternion(const CInterfaceStack* inStack, int index, std::initializer_list<double> wxyz = {});
CQuaternion fetchQuaternion(const CInterfaceStack* inStack, int index, const double wxyz[4]);
CPose fetchPose(const CInterfaceStack* inStack, int index, std::initializer_list<double> xyzqwqxqyqz = {});
CPose fetchPose(const CInterfaceStack* inStack, int index, const double xyzqwqxqyqz[7]);
C3Vector fetchVector3(const CInterfaceStack* inStack, int index, std::initializer_list<double> xyz = {});
C3Vector fetchVector3(const CInterfaceStack* inStack, int index, const double xyz[3]);
CMatrix fetchMatrix(const CInterfaceStack* inStack, int index);
void fetchMatrixData(const CInterfaceStack* inStack, int index, std::vector<double>& data, bool rowByRow);
void fetchMatrixData(const CInterfaceStack* inStack, int index, std::vector<float>& data, bool rowByRow);
void fetchIntArray(const CInterfaceStack* inStack, int index, std::vector<int>& outArr, std::initializer_list<int> arr = {});
void fetchIntArray(const CInterfaceStack* inStack, int index, std::vector<int>& outArr, std::vector<int>& arr);
void fetchInt64Array(const CInterfaceStack* inStack, int index, std::vector<int64_t>& outArr);
void fetchHandleArray(const CInterfaceStack* inStack, int index, std::vector<int>& outArr);
void fetchHandleArray(const CInterfaceStack* inStack, int index, std::vector<int64_t>& outArr, std::initializer_list<int64_t> arr = {});
void fetchHandleArray(const CInterfaceStack* inStack, int index, std::vector<int64_t>& outArr, std::vector<int64_t>& arr);
void fetchDoubleArray(const CInterfaceStack* inStack, int index, std::vector<double>& outArr, std::initializer_list<double> arr = {});
void fetchDoubleArray(const CInterfaceStack* inStack, int index, std::vector<double>& outArr, std::vector<double>& arr);
void fetchVector(const CInterfaceStack* inStack, int index, std::vector<double>& outArr, std::initializer_list<double> arr = {});
void fetchTextArray(const CInterfaceStack* inStack, int index, std::vector<std::string>& outArr, std::initializer_list<std::string> arr = {});
void fetchTextArray(const CInterfaceStack* inStack, int index, std::vector<std::string>& outArr, std::vector<std::string>& arr);
CInterfaceStackTable* fetchMap(const CInterfaceStack* inStack, int index);

void fetchArrayAsConsecutiveNumbers(const CInterfaceStack* inStack, int index, std::vector<float>& outArr);
void fetchArrayAsConsecutiveNumbers(const CInterfaceStack* inStack, int index, std::vector<double>& outArr);

CSceneObject* getSceneObject(int identifier, std::string* errMsg = nullptr, size_t argPos = -1);
CSceneObject* getSpecificSceneObjectType(int identifier, int type, std::string* errMsg = nullptr, size_t argPos = -1);
CCollection* getCollection(int identifier, std::string* errMsg = nullptr, size_t argPos = -1);
CDrawingObject* getDrawingObject(int identifier, std::string* errMsg = nullptr, size_t argPos = -1);
CScript* getNakedScript(int identifier, std::string* errMsg = nullptr, size_t argPos = -1);
CMesh* getMesh(int identifier, std::string* errMsg = nullptr, size_t argPos = -1);
bool doesEntityExist(int identifier, std::string* errMsg = nullptr, size_t argPos = -1);
std::string getInvalidArgString(size_t argPos);

extern std::string _method_getPosition(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setPosition(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getQuaternion(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setQuaternion(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getPose(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setPose(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setParent(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_handleMessagePump(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_handleSandboxScript(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_handleAddOnScripts(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_handleCustomizationScripts(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_handleSimulationScripts(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadModel(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadModelFromBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadModelInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadModelInfoFromBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_saveModel(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_saveModelToBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadScene(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadSceneFromBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_save(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_saveToBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_removeModel(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_duplicateObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addItem(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_removeItem(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_checkCollision(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_checkDistance(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_handleSensor(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_resetSensor(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_checkSensor(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addItems(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addPackedItems(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_clearItems(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_removeItems(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_callFunction(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_executeString(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
//extern std::string _method_getApiInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
//extern std::string _method_getApiFunc(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getStackTraceback(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_reset(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_init(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_suspend(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_resume(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_scale(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_scaleTree(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_startSimulation(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_pauseSimulation(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_stopSimulation(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getName(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_dynamicReset(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadImage(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_loadImageFromBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_saveImage(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_saveImageToBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_transformImage(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_transformBuffer(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getImage(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setImage(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getDepth(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_relocateFrame(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_alignBoundingBox(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_logInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_logWarn(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_logError(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_quit(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_systemLock(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setStepping(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getStepping(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getObject(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_announceChange(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getObjectFromUid(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getInertia(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setInertia(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_computeInertia(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addForce(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addTorque(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_ungroup(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_divide(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_pack(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_unpack(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_packArray(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_unpackArray(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_groupShapes(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_mergeShapes(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getBoolProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getBufferProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getColorProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getFloatArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getFloatProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getStringArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getHandleArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getHandleProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getIntArray2Property(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getIntArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getIntProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getLongProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getPoseProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getQuaternionProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getStringProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getVector3Property(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getTableProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setBoolProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setBufferProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setColorProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setFloatArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setFloatProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setStringArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setHandleArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setHandleProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setIntArray2Property(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setIntArrayProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setIntProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setLongProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setPoseProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setQuaternionProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setStringProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setVector3Property(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getMatrixProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setMatrixProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getMethodProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setMethodProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setTableProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_removeProperty(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getPropertyName(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getPropertyInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setPropertyInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_isValid(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addCurve(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addSignal(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setSignalPoint(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_removeTrace(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_snapshotTrace(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_step(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_makeClass(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_makeObject(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addFromObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_subtractFromObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_clear(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addVoxels(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addPackedVoxels(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_subtractVoxels(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_subtractPackedVoxels(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_checkPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_checkPackedPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_addPackedPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_subtractPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_subtractPackedPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_intersectPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_intersectPackedPoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setTargetPosition(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setTargetVelocity(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_pushEvent(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getContacts(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getGenesisEvents(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setEventFilters(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getPluginInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setPluginInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_setModuleEntry(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_dynamicsStep(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_stepKinematicJoints(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_broadcast(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_textureSet(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_textureSetData(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_textureGetData(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getEnumInfo(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_copyObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_cutObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_pasteObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);

extern std::string _method_remove(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_removeObjects(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_createCamera(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_createLight(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_createGraph(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_createCustomSceneObject(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_createCustomObjectClass(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_createShapeFromPath(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
extern std::string _method_getClosestOnPath(int targetObj, CScript* currentScript, const CInterfaceStack* inStack, CInterfaceStack* outStack);
