#if !defined(sim_INCLUDED_)
#define sim_INCLUDED_

#include "simConst.h"
#include "simTypes.h"

#ifndef SIM_DLLEXPORT
    #ifdef WIN_SIM
        #define SIM_DLLEXPORT extern "C" __declspec(dllexport)
    #endif
    #ifdef MAC_SIM
        #define SIM_DLLEXPORT extern "C" __attribute__((visibility("default")))
    #endif
    #ifdef LIN_SIM
        #define SIM_DLLEXPORT extern "C" __attribute__((visibility("default")))
    #endif
#endif

SIM_DLLEXPORT simInt simRunSimulator(const simChar* applicationName,simInt options,simVoid(*initCallBack)(),simVoid(*loopCallBack)(),simVoid(*deinitCallBack)());
SIM_DLLEXPORT simInt simRunSimulatorEx(const simChar* applicationName,simInt options,simVoid(*initCallBack)(),simVoid(*loopCallBack)(),simVoid(*deinitCallBack)(),simInt stopDelay,const simChar* sceneOrModelToLoad);
SIM_DLLEXPORT simVoid* simGetMainWindow(simInt type);
SIM_DLLEXPORT simChar* simGetLastError();
SIM_DLLEXPORT simInt simSetBoolParam(simInt parameter,simBool boolState);
SIM_DLLEXPORT simInt simGetBoolParam(simInt parameter);
SIM_DLLEXPORT simInt simSetInt32Param(simInt parameter,simInt intState);
SIM_DLLEXPORT simInt simGetInt32Param(simInt parameter,simInt* intState);
SIM_DLLEXPORT simInt simGetUInt64Param(simInt parameter,simUInt64* intState);
SIM_DLLEXPORT simInt simSetFloatParam(simInt parameter,simFloat floatState);
SIM_DLLEXPORT simInt simGetFloatParam(simInt parameter,simFloat* floatState);
SIM_DLLEXPORT simInt simSetStringParam(simInt parameter,const simChar* str);
SIM_DLLEXPORT simChar* simGetStringParam(simInt parameter);
SIM_DLLEXPORT simInt simSetArrayParam(simInt parameter,const simVoid* arrayOfValues);
SIM_DLLEXPORT simInt simGetArrayParam(simInt parameter,simVoid* arrayOfValues);
SIM_DLLEXPORT simInt simSetNamedStringParam(const simChar* paramName,const simChar* stringParam,simInt paramLength);
SIM_DLLEXPORT simChar* simGetNamedStringParam(const simChar* paramName,simInt* paramLength);
SIM_DLLEXPORT simInt simGetObjectHandleEx(const simChar* objectAlias,simInt index,simInt proxy,simInt options);
SIM_DLLEXPORT simInt simGetScriptHandleEx(simInt scriptType,simInt objectHandle,const simChar* scriptName);
SIM_DLLEXPORT simInt simRemoveObject(simInt objectHandle);
SIM_DLLEXPORT simInt simRemoveModel(simInt objectHandle);
SIM_DLLEXPORT simChar* simGetObjectAlias(simInt objectHandle,simInt options);
SIM_DLLEXPORT simInt simSetObjectAlias(simInt objectHandle,const simChar* objectAlias,simInt options);
SIM_DLLEXPORT simInt simGetObjectMatrix(simInt objectHandle,simInt relativeToObjectHandle,simFloat* matrix);
SIM_DLLEXPORT simInt simSetObjectMatrix(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* matrix);
SIM_DLLEXPORT simInt simGetObjectPose(simInt objectHandle,simInt relativeToObjectHandle,simFloat* pose);
SIM_DLLEXPORT simInt simSetObjectPose(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* pose);
SIM_DLLEXPORT simInt simGetObjectPosition(simInt objectHandle,simInt relativeToObjectHandle,simFloat* position);
SIM_DLLEXPORT simInt simSetObjectPosition(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* position);
SIM_DLLEXPORT simInt simGetObjectOrientation(simInt objectHandle,simInt relativeToObjectHandle,simFloat* eulerAngles);
SIM_DLLEXPORT simInt simGetObjectQuaternion(simInt objectHandle,simInt relativeToObjectHandle,simFloat* quaternion);
SIM_DLLEXPORT simInt simSetObjectQuaternion(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* quaternion);
SIM_DLLEXPORT simInt simSetObjectOrientation(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* eulerAngles);
SIM_DLLEXPORT simInt simGetJointPosition(simInt objectHandle,simFloat* position);
SIM_DLLEXPORT simInt simSetJointPosition(simInt objectHandle,simFloat position);
SIM_DLLEXPORT simInt simSetJointTargetPosition(simInt objectHandle,simFloat targetPosition);
SIM_DLLEXPORT simInt simGetJointTargetPosition(simInt objectHandle,simFloat* targetPosition);
SIM_DLLEXPORT simInt simSetJointMaxForce(simInt objectHandle,simFloat forceOrTorque);
SIM_DLLEXPORT simInt simGetObjectChildPose(simInt objectHandle,simFloat* pose);
SIM_DLLEXPORT simInt simSetObjectChildPose(simInt objectHandle,const simFloat* pose);
SIM_DLLEXPORT simInt simGetJointInterval(simInt objectHandle,simBool* cyclic,simFloat* interval);
SIM_DLLEXPORT simInt simSetJointInterval(simInt objectHandle,simBool cyclic,const simFloat* interval);
SIM_DLLEXPORT simInt simGetObjectParent(simInt objectHandle);
SIM_DLLEXPORT simInt simGetObjectChild(simInt objectHandle,simInt index);
SIM_DLLEXPORT simInt simSetObjectParent(simInt objectHandle,simInt parentObjectHandle,simBool keepInPlace);
SIM_DLLEXPORT simInt simGetObjectType(simInt objectHandle);
SIM_DLLEXPORT simInt simGetJointType(simInt objectHandle);
SIM_DLLEXPORT simInt simBuildIdentityMatrix(simFloat* matrix);
SIM_DLLEXPORT simInt simBuildMatrix(const simFloat* position,const simFloat* eulerAngles,simFloat* matrix);
SIM_DLLEXPORT simInt simBuildMatrixQ(const simFloat* position,const simFloat* quaternion,simFloat* matrix);
SIM_DLLEXPORT simInt simGetEulerAnglesFromMatrix(const simFloat* matrix,simFloat* eulerAngles);
SIM_DLLEXPORT simInt simGetQuaternionFromMatrix(const simFloat* matrix,simFloat* quaternion);
SIM_DLLEXPORT simInt simInvertMatrix(simFloat* matrix);
SIM_DLLEXPORT simInt simMultiplyMatrices(const simFloat* matrixIn1,const simFloat* matrixIn2,simFloat* matrixOut);
SIM_DLLEXPORT simInt simInterpolateMatrices(const simFloat* matrixIn1,const simFloat* matrixIn2,simFloat interpolFactor,simFloat* matrixOut);
SIM_DLLEXPORT simInt simTransformVector(const simFloat* matrix,simFloat* vect);
SIM_DLLEXPORT simInt simReservedCommand(simInt v,simInt w);
SIM_DLLEXPORT simFloat simGetSimulationTime();
SIM_DLLEXPORT simInt simGetSimulationState();
SIM_DLLEXPORT simUInt simGetSystemTimeInMs(simInt previousTime);
SIM_DLLEXPORT simInt simLoadScene(const simChar* filename);
SIM_DLLEXPORT simInt simCloseScene();
SIM_DLLEXPORT simInt simSaveScene(const simChar* filename);
SIM_DLLEXPORT simInt simLoadModel(const simChar* filename);
SIM_DLLEXPORT simInt simSaveModel(simInt baseOfModelHandle,const simChar* filename);
SIM_DLLEXPORT simChar* simGetSimulatorMessage(simInt* messageID,simInt* auxiliaryData,simInt* returnedDataSize);
SIM_DLLEXPORT simInt simDoesFileExist(const simChar* filename);
SIM_DLLEXPORT simInt* simGetObjectSel(simInt* cnt);
SIM_DLLEXPORT simInt simSetObjectSel(const simInt* handles,simInt cnt);
SIM_DLLEXPORT simInt simHandleProximitySensor(simInt sensorHandle,simFloat* detectedPoint,simInt* detectedObjectHandle,simFloat* normalVector);
SIM_DLLEXPORT simInt simReadProximitySensor(simInt sensorHandle,simFloat* detectedPoint,simInt* detectedObjectHandle,simFloat* normalVector);
SIM_DLLEXPORT simInt simHandleDynamics(simFloat deltaTime);
SIM_DLLEXPORT simInt simSetScriptText(simInt scriptHandle,const simChar* scriptText);
SIM_DLLEXPORT const simChar* simGetScriptText(simInt scriptHandle);
SIM_DLLEXPORT simInt simGetScriptProperty(simInt scriptHandle,simInt* scriptProperty,simInt* associatedObjectHandle);
SIM_DLLEXPORT simInt simAssociateScriptWithObject(simInt scriptHandle,simInt associatedObjectHandle);
SIM_DLLEXPORT simInt simHandleMainScript();
SIM_DLLEXPORT simInt simResetScript(simInt scriptHandle);
SIM_DLLEXPORT simInt simAddScript(simInt scriptProperty);
SIM_DLLEXPORT simInt simRemoveScript(simInt scriptHandle);
SIM_DLLEXPORT simInt simRefreshDialogs(simInt refreshDegree);
SIM_DLLEXPORT simInt simResetProximitySensor(simInt sensorHandle);
SIM_DLLEXPORT simInt simCheckProximitySensor(simInt sensorHandle,simInt entityHandle,simFloat* detectedPoint);
SIM_DLLEXPORT simInt simCheckProximitySensorEx(simInt sensorHandle,simInt entityHandle,simInt detectionMode,simFloat detectionThreshold,simFloat maxAngle,simFloat* detectedPoint,simInt* detectedObjectHandle,simFloat* normalVector);
SIM_DLLEXPORT simInt simCheckProximitySensorEx2(simInt sensorHandle,simFloat* vertexPointer,simInt itemType,simInt itemCount,simInt detectionMode,simFloat detectionThreshold,simFloat maxAngle,simFloat* detectedPoint,simFloat* normalVector);
SIM_DLLEXPORT simChar* simCreateBuffer(simInt size);
SIM_DLLEXPORT simInt simReleaseBuffer(const simChar* buffer);
SIM_DLLEXPORT simInt simCheckCollision(simInt entity1Handle,simInt entity2Handle);
SIM_DLLEXPORT simInt simCheckCollisionEx(simInt entity1Handle,simInt entity2Handle,simFloat** intersectionSegments);
SIM_DLLEXPORT simInt simCheckDistance(simInt entity1Handle,simInt entity2Handle,simFloat threshold,simFloat* distanceData);
SIM_DLLEXPORT simInt simSetSimulationTimeStep(simFloat timeStep);
SIM_DLLEXPORT simFloat simGetSimulationTimeStep();
SIM_DLLEXPORT simInt simGetRealTimeSimulation();
SIM_DLLEXPORT simInt simIsRealTimeSimulationStepNeeded();
SIM_DLLEXPORT simInt simAdjustRealTimeTimer(simInt instanceIndex,simFloat deltaTime);
SIM_DLLEXPORT simInt simGetSimulationPassesPerRenderingPass();
SIM_DLLEXPORT simInt simAdvanceSimulationByOneStep();
SIM_DLLEXPORT simInt simStartSimulation();
SIM_DLLEXPORT simInt simStopSimulation();
SIM_DLLEXPORT simInt simPauseSimulation();
SIM_DLLEXPORT simInt simLoadModule(const simChar* filenameAndPath,const simChar* pluginName);
SIM_DLLEXPORT simInt simUnloadModule(simInt pluginhandle);
SIM_DLLEXPORT simVoid* simSendModuleMessage(simInt message,simInt* auxiliaryData,simVoid* customData,simInt* replyData);
SIM_DLLEXPORT simVoid* simBroadcastMessage(simInt* auxiliaryData,simVoid* customData,simInt* replyData);
SIM_DLLEXPORT simChar* simGetModuleName(simInt index,simUChar* moduleVersion);
SIM_DLLEXPORT simInt simFloatingViewAdd(simFloat posX,simFloat posY,simFloat sizeX,simFloat sizeY,simInt options);
SIM_DLLEXPORT simInt simFloatingViewRemove(simInt floatingViewHandle);
SIM_DLLEXPORT simInt simAdjustView(simInt viewHandleOrIndex,simInt associatedViewableObjectHandle,simInt options,const simChar* viewLabel);
SIM_DLLEXPORT simInt simSetLastError(const simChar* funcName,const simChar* errorMessage);
SIM_DLLEXPORT simInt simHandleGraph(simInt graphHandle,simFloat simulationTime);
SIM_DLLEXPORT simInt simResetGraph(simInt graphHandle);
SIM_DLLEXPORT simInt simAddGraphStream(simInt graphHandle,const simChar* streamName,const simChar* unitStr,simInt options,const simFloat* color,simFloat cyclicRange);
SIM_DLLEXPORT simInt simDestroyGraphCurve(simInt graphHandle,simInt curveId);
SIM_DLLEXPORT simInt simSetGraphStreamTransformation(simInt graphHandle,simInt streamId,simInt trType,simFloat mult,simFloat off,simInt movingAvgPeriod);
SIM_DLLEXPORT simInt simDuplicateGraphCurveToStatic(simInt graphHandle,simInt curveId,const simChar* curveName);
SIM_DLLEXPORT simInt simAddGraphCurve(simInt graphHandle,const simChar* curveName,simInt dim,const simInt* streamIds,const simFloat* defaultValues,const simChar* unitStr,simInt options,const simFloat* color,simInt curveWidth);
SIM_DLLEXPORT simInt simSetGraphStreamValue(simInt graphHandle,simInt streamId,simFloat value);
SIM_DLLEXPORT simInt simSetNavigationMode(simInt navigationMode);
SIM_DLLEXPORT simInt simGetNavigationMode();
SIM_DLLEXPORT simInt simSetPage(simInt index);
SIM_DLLEXPORT simInt simGetPage();
SIM_DLLEXPORT simInt simRegisterScriptCallbackFunction(const simChar* funcNameAtPluginName,const simChar* callTips,simVoid(*callBack)(struct SScriptCallBack* cb));
SIM_DLLEXPORT simInt simRegisterScriptVariable(const simChar* varNameAtPluginName,const simChar* varValue,simInt stackHandle);
SIM_DLLEXPORT simInt simRegisterScriptFuncHook(simInt scriptHandle,const simChar* funcToHook,const simChar* userFunction,simBool executeBefore,simInt options);
SIM_DLLEXPORT simInt simSetJointTargetVelocity(simInt objectHandle,simFloat targetVelocity);
SIM_DLLEXPORT simInt simGetJointTargetVelocity(simInt objectHandle,simFloat* targetVelocity);
SIM_DLLEXPORT simInt simCopyPasteObjects(simInt* objectHandles,simInt objectCount,simInt options);
SIM_DLLEXPORT simInt simScaleObjects(const simInt* objectHandles,simInt objectCount,simFloat scalingFactor,simBool scalePositionsToo);
SIM_DLLEXPORT simInt simAddDrawingObject(simInt objectType,simFloat size,simFloat duplicateTolerance,simInt parentObjectHandle,simInt maxItemCount,const simFloat* ambient_diffuse,const simFloat* setToNULL,const simFloat* specular,const simFloat* emission);
SIM_DLLEXPORT simInt simRemoveDrawingObject(simInt objectHandle);
SIM_DLLEXPORT simInt simAddDrawingObjectItem(simInt objectHandle,const simFloat* itemData);
SIM_DLLEXPORT simInt simAddParticleObject(simInt objectType,simFloat size,simFloat density,const simVoid* params,simFloat lifeTime,simInt maxItemCount,const simFloat* ambient_diffuse,const simFloat* setToNULL,const simFloat* specular,const simFloat* emission);
SIM_DLLEXPORT simInt simRemoveParticleObject(simInt objectHandle);
SIM_DLLEXPORT simInt simAddParticleObjectItem(simInt objectHandle,const simFloat* itemData);
SIM_DLLEXPORT simFloat simGetObjectSizeFactor(simInt objectHandle);
SIM_DLLEXPORT simInt simAnnounceSceneContentChange();
SIM_DLLEXPORT simInt simSetInt32Signal(const simChar* signalName,simInt signalValue);
SIM_DLLEXPORT simInt simGetInt32Signal(const simChar* signalName,simInt* signalValue);
SIM_DLLEXPORT simInt simClearInt32Signal(const simChar* signalName);
SIM_DLLEXPORT simInt simSetFloatSignal(const simChar* signalName,simFloat signalValue);
SIM_DLLEXPORT simInt simGetFloatSignal(const simChar* signalName,simFloat* signalValue);
SIM_DLLEXPORT simInt simClearFloatSignal(const simChar* signalName);
SIM_DLLEXPORT simInt simSetDoubleSignal(const simChar* signalName,simDouble signalValue);
SIM_DLLEXPORT simInt simGetDoubleSignal(const simChar* signalName,simDouble* signalValue);
SIM_DLLEXPORT simInt simClearDoubleSignal(const simChar* signalName);
SIM_DLLEXPORT simInt simSetStringSignal(const simChar* signalName,const simChar* signalValue,simInt stringLength);
SIM_DLLEXPORT simChar* simGetStringSignal(const simChar* signalName,simInt* stringLength);
SIM_DLLEXPORT simInt simClearStringSignal(const simChar* signalName);
SIM_DLLEXPORT simChar* simGetSignalName(simInt signalIndex,simInt signalType);
SIM_DLLEXPORT simInt simSetObjectProperty(simInt objectHandle,simInt prop);
SIM_DLLEXPORT simInt simGetObjectProperty(simInt objectHandle);
SIM_DLLEXPORT simInt simSetObjectSpecialProperty(simInt objectHandle,simInt prop);
SIM_DLLEXPORT simInt simGetObjectSpecialProperty(simInt objectHandle);
SIM_DLLEXPORT simInt simReadForceSensor(simInt objectHandle,simFloat* forceVector,simFloat* torqueVector);
SIM_DLLEXPORT simInt simGetShapeVertex(simInt shapeHandle,simInt groupElementIndex,simInt vertexIndex,simFloat* relativePosition);
SIM_DLLEXPORT simInt simGetShapeTriangle(simInt shapeHandle,simInt groupElementIndex,simInt triangleIndex,simInt* vertexIndices,simFloat* triangleNormals);
SIM_DLLEXPORT simInt simSetLightParameters(simInt objectHandle,simInt state,const simFloat* setToNULL,const simFloat* diffusePart,const simFloat* specularPart);
SIM_DLLEXPORT simInt simGetLightParameters(simInt objectHandle,simFloat* setToNULL,simFloat* diffusePart,simFloat* specularPart);
SIM_DLLEXPORT simInt simGetVelocity(simInt shapeHandle,simFloat* linearVelocity,simFloat* angularVelocity);
SIM_DLLEXPORT simInt simGetObjectVelocity(simInt objectHandle,simFloat* linearVelocity,simFloat* angularVelocity);
SIM_DLLEXPORT simInt simGetJointVelocity(simInt jointHandle,simFloat* velocity);
SIM_DLLEXPORT simInt simAddForceAndTorque(simInt shapeHandle,const simFloat* force,const simFloat* torque);
SIM_DLLEXPORT simInt simAddForce(simInt shapeHandle,const simFloat* position,const simFloat* force);
SIM_DLLEXPORT simInt simSetExplicitHandling(simInt objectHandle,int explicitFlags);
SIM_DLLEXPORT simInt simGetExplicitHandling(simInt objectHandle);
SIM_DLLEXPORT simInt simGetLinkDummy(simInt dummyHandle);
SIM_DLLEXPORT simInt simSetLinkDummy(simInt dummyHandle,simInt linkedDummyHandle);
SIM_DLLEXPORT simInt simSetModelProperty(simInt objectHandle,simInt modelProperty);
SIM_DLLEXPORT simInt simGetModelProperty(simInt objectHandle);
SIM_DLLEXPORT simInt simSetObjectColor(simInt objectHandle,simInt index,simInt colorComponent,const simFloat* rgbData);
SIM_DLLEXPORT simInt simGetObjectColor(simInt objectHandle,simInt index,simInt colorComponent,simFloat* rgbData);
SIM_DLLEXPORT simInt simSetShapeColor(simInt shapeHandle,const simChar* colorName,simInt colorComponent,const simFloat* rgbData);
SIM_DLLEXPORT simInt simGetShapeColor(simInt shapeHandle,const simChar* colorName,simInt colorComponent,simFloat* rgbData);
SIM_DLLEXPORT simInt simResetDynamicObject(simInt objectHandle);
SIM_DLLEXPORT simInt simSetJointMode(simInt jointHandle,simInt jointMode,simInt options);
SIM_DLLEXPORT simInt simGetJointMode(simInt jointHandle,simInt* options);
SIM_DLLEXPORT simInt simSerialOpen(const simChar* portString,simInt baudRate,simVoid* reserved1,simVoid* reserved2);
SIM_DLLEXPORT simInt simSerialClose(simInt portHandle);
SIM_DLLEXPORT simInt simSerialSend(simInt portHandle,const simChar* data,simInt dataLength);
SIM_DLLEXPORT simInt simSerialRead(simInt portHandle,simChar* buffer,simInt dataLengthToRead);
SIM_DLLEXPORT simInt simSerialCheck(simInt portHandle);
SIM_DLLEXPORT simInt simGetContactInfo(simInt dynamicPass,simInt objectHandle,simInt index,simInt* objectHandles,simFloat* contactInfo);
SIM_DLLEXPORT simInt simAuxiliaryConsoleOpen(const simChar* title,simInt maxLines,simInt mode,const simInt* position,const simInt* size,const simFloat* textColor,const simFloat* backgroundColor);
SIM_DLLEXPORT simInt simAuxiliaryConsoleClose(simInt consoleHandle);
SIM_DLLEXPORT simInt simAuxiliaryConsoleShow(simInt consoleHandle,simBool showState);
SIM_DLLEXPORT simInt simAuxiliaryConsolePrint(simInt consoleHandle,const simChar* text);
SIM_DLLEXPORT simInt simImportShape(simInt fileformat,const simChar* pathAndFilename,simInt options,simFloat identicalVerticeTolerance,simFloat scalingFactor);
SIM_DLLEXPORT simInt simImportMesh(simInt fileformat,const simChar* pathAndFilename,simInt options,simFloat identicalVerticeTolerance,simFloat scalingFactor,simFloat*** vertices,simInt** verticesSizes,simInt*** indices,simInt** indicesSizes,simFloat*** reserved,simChar*** names);
SIM_DLLEXPORT simInt simExportMesh(simInt fileformat,const simChar* pathAndFilename,simInt options,simFloat scalingFactor,simInt elementCount,const simFloat** vertices,const simInt* verticesSizes,const simInt** indices,const simInt* indicesSizes,simFloat** reserved,const simChar** names);
SIM_DLLEXPORT simInt simCreateMeshShape(simInt options,simFloat shadingAngle,const simFloat* vertices,simInt verticesSize,const simInt* indices,simInt indicesSize,simFloat* reserved);
SIM_DLLEXPORT simInt simCreatePureShape(simInt primitiveType,simInt options,const simFloat* sizes,simFloat mass,const simInt* precision);
SIM_DLLEXPORT simInt simCreateHeightfieldShape(simInt options,simFloat shadingAngle,simInt xPointCount,simInt yPointCount,simFloat xSize,const simFloat* heights);
SIM_DLLEXPORT simInt simGetShapeMesh(simInt shapeHandle,simFloat** vertices,simInt* verticesSize,simInt** indices,simInt* indicesSize,simFloat** normals);
SIM_DLLEXPORT simInt simCreateJoint(simInt jointType,simInt jointMode,simInt options,const simFloat* sizes,const simFloat* colorA,const simFloat* colorB);
SIM_DLLEXPORT simInt simGetObjectInt32Param(simInt objectHandle,simInt ParamID,simInt* Param);
SIM_DLLEXPORT simInt simSetObjectInt32Param(simInt objectHandle,simInt ParamID,simInt Param);
SIM_DLLEXPORT simInt simGetObjectFloatParam(simInt objectHandle,simInt ParamID,simFloat* Param);
SIM_DLLEXPORT simInt simSetObjectFloatParam(simInt objectHandle,simInt ParamID,simFloat Param);
SIM_DLLEXPORT simChar* simGetObjectStringParam(simInt objectHandle,simInt ParamID,simInt* ParamLength);
SIM_DLLEXPORT simInt simSetObjectStringParam(simInt objectHandle,simInt ParamID,const simChar* Param,simInt ParamLength);
SIM_DLLEXPORT simInt simSetSimulationPassesPerRenderingPass(simInt p);
SIM_DLLEXPORT simInt simGetRotationAxis(const simFloat* matrixStart,const simFloat* matrixGoal,simFloat* axis,simFloat* angle);
SIM_DLLEXPORT simInt simRotateAroundAxis(const simFloat* matrixIn,const simFloat* axis,const simFloat* axisPos,simFloat angle,simFloat* matrixOut);
SIM_DLLEXPORT simInt simGetJointForce(simInt jointHandle,simFloat* forceOrTorque);
SIM_DLLEXPORT simInt simGetJointMaxForce(simInt jointHandle,simFloat* forceOrTorque);
SIM_DLLEXPORT simInt simCameraFitToView(simInt viewHandleOrIndex,simInt objectCount,const simInt* objectHandles,simInt options,simFloat scaling);
SIM_DLLEXPORT simInt simPersistentDataWrite(const simChar* dataName,const simChar* dataValue,simInt dataLength,simInt options);
SIM_DLLEXPORT simChar* simPersistentDataRead(const simChar* dataName,simInt* dataLength);
SIM_DLLEXPORT simInt simIsHandle(simInt generalObjectHandle,simInt generalObjectType);
SIM_DLLEXPORT simInt simHandleVisionSensor(simInt visionSensorHandle,simFloat** auxValues,simInt** auxValuesCount);
SIM_DLLEXPORT simInt simReadVisionSensor(simInt visionSensorHandle,simFloat** auxValues,simInt** auxValuesCount);
SIM_DLLEXPORT simInt simResetVisionSensor(simInt visionSensorHandle);
SIM_DLLEXPORT simInt simCheckVisionSensor(simInt visionSensorHandle,simInt entityHandle,simFloat** auxValues,simInt** auxValuesCount);
SIM_DLLEXPORT simFloat* simCheckVisionSensorEx(simInt visionSensorHandle,simInt entityHandle,simBool returnImage);
SIM_DLLEXPORT simInt simGetVisionSensorResolution(simInt visionSensorHandle,simInt* resolution);
SIM_DLLEXPORT simFloat* simGetVisionSensorImage(simInt visionSensorHandle);
SIM_DLLEXPORT simUChar* simGetVisionSensorCharImage(simInt visionSensorHandle,simInt* resolutionX,simInt* resolutionY);
SIM_DLLEXPORT simInt simSetVisionSensorImage(simInt visionSensorHandle,const simFloat* image);
SIM_DLLEXPORT simInt simSetVisionSensorCharImage(simInt visionSensorHandle,const simUChar* image);
SIM_DLLEXPORT int simSetVisionSensorDepthBuffer(simInt visionSensorHandle,const float* depthBuffer);
SIM_DLLEXPORT simInt simRuckigPos(simInt dofs,simDouble smallestTimeStep,simInt flags,const simDouble* currentPos,const simDouble* currentVel,const simDouble* currentAccel,const simDouble* maxVel,const simDouble* maxAccel,const simDouble* maxJerk,const simBool* selection,const simDouble* targetPos,const simDouble* targetVel,simDouble* reserved1,simInt* reserved2);
SIM_DLLEXPORT simInt simRuckigVel(simInt dofs,simDouble smallestTimeStep,simInt flags,const simDouble* currentPos,const simDouble* currentVel,const simDouble* currentAccel,const simDouble* maxAccel,const simDouble* maxJerk,const simBool* selection,const simDouble* targetVel,simDouble* reserved1,simInt* reserved2);
SIM_DLLEXPORT simInt simRuckigStep(simInt objHandle,simDouble timeStep,simDouble* newPos,simDouble* newVel,simDouble* newAccel,simDouble* syncTime,simDouble* reserved1,simInt* reserved2);
SIM_DLLEXPORT simInt simRuckigRemove(simInt objHandle);
SIM_DLLEXPORT simInt simCreateDummy(simFloat size,const simFloat* color);
SIM_DLLEXPORT simInt simGroupShapes(const simInt* shapeHandles,simInt shapeCount);
SIM_DLLEXPORT simInt* simUngroupShape(simInt shapeHandle,simInt* shapeCount);
SIM_DLLEXPORT simInt simCreateProximitySensor(simInt sensorType,simInt subType,simInt options,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
SIM_DLLEXPORT simInt simCreateForceSensor(simInt options,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
SIM_DLLEXPORT simInt simCreateVisionSensor(simInt options,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
SIM_DLLEXPORT simInt simConvexDecompose(simInt shapeHandle,simInt options,const simInt* intParams,const simFloat* floatParams);
SIM_DLLEXPORT simVoid simQuitSimulator(simBool ignoredArgument);
SIM_DLLEXPORT simInt simSetShapeMaterial(simInt shapeHandle,simInt materialIdOrShapeHandle);
SIM_DLLEXPORT simInt simGetTextureId(const simChar* textureName,simInt* resolution);
SIM_DLLEXPORT simChar* simReadTexture(simInt textureId,simInt options,simInt posX,simInt posY,simInt sizeX,simInt sizeY);
SIM_DLLEXPORT simInt simWriteTexture(simInt textureId,simInt options,const simChar* data,simInt posX,simInt posY,simInt sizeX,simInt sizeY,simFloat interpol);
SIM_DLLEXPORT simInt simCreateTexture(const simChar* fileName,simInt options,const simFloat* planeSizes,const simFloat* scalingUV,const simFloat* xy_g,simInt fixedResolution,simInt* textureId,simInt* resolution,const simVoid* reserved);
SIM_DLLEXPORT simInt simWriteCustomDataBlock(simInt objectHandle,const simChar* tagName,const simChar* data,simInt dataSize);
SIM_DLLEXPORT simChar* simReadCustomDataBlock(simInt objectHandle,const simChar* tagName,simInt* dataSize);
SIM_DLLEXPORT simChar* simReadCustomDataBlockTags(simInt objectHandle,simInt* tagCount);
SIM_DLLEXPORT simInt simGetShapeGeomInfo(simInt shapeHandle,simInt* intData,simFloat* floatData,simVoid* reserved);
SIM_DLLEXPORT simInt simGetObjects(simInt index,simInt objectType);
SIM_DLLEXPORT simInt* simGetObjectsInTree(simInt treeBaseHandle,simInt objectType,simInt options,simInt* objectCount);
SIM_DLLEXPORT simInt simScaleObject(simInt objectHandle,simFloat xScale,simFloat yScale,simFloat zScale,simInt options);
SIM_DLLEXPORT simInt simSetShapeTexture(simInt shapeHandle,simInt textureId,simInt mappingMode,simInt options,const simFloat* uvScaling,const simFloat* position,const simFloat* orientation);
SIM_DLLEXPORT simInt simGetShapeTextureId(simInt shapeHandle);
SIM_DLLEXPORT simInt simCreateCollectionEx(simInt options);
SIM_DLLEXPORT simInt simAddItemToCollection(simInt collectionHandle,simInt what,simInt objectHandle,simInt options);
SIM_DLLEXPORT simInt simDestroyCollection(simInt collectionHandle);
SIM_DLLEXPORT simInt* simGetCollectionObjects(simInt collectionHandle,simInt* objectCount);
SIM_DLLEXPORT simInt simSetScriptAttribute(simInt scriptHandle,simInt attributeID,simFloat floatVal,simInt intOrBoolVal);
SIM_DLLEXPORT simInt simGetScriptAttribute(simInt scriptHandle,simInt attributeID,simFloat* floatVal,simInt* intOrBoolVal);
SIM_DLLEXPORT simInt simReorientShapeBoundingBox(simInt shapeHandle,simInt relativeToHandle,simInt reservedSetToZero);
SIM_DLLEXPORT simInt simSaveImage(const simUChar* image,const simInt* resolution,simInt options,const simChar* filename,simInt quality,simVoid* reserved);
SIM_DLLEXPORT simUChar* simLoadImage(simInt* resolution,simInt options,const simChar* filename,simVoid* reserved);
SIM_DLLEXPORT simUChar* simGetScaledImage(const simUChar* imageIn,const simInt* resolutionIn,simInt* resolutionOut,simInt options,simVoid* reserved);
SIM_DLLEXPORT simInt simTransformImage(simUChar* image,const simInt* resolution,simInt options,const simFloat* floatParams,const simInt* intParams,simVoid* reserved);
SIM_DLLEXPORT simInt simGetQHull(const simFloat* inVertices,simInt inVerticesL,simFloat** verticesOut,simInt* verticesOutL,simInt** indicesOut,simInt* indicesOutL,simInt reserved1,const simFloat* reserved2);
SIM_DLLEXPORT simInt simGetDecimatedMesh(const simFloat* inVertices,simInt inVerticesL,const simInt* inIndices,simInt inIndicesL,simFloat** verticesOut,simInt* verticesOutL,simInt** indicesOut,simInt* indicesOutL,simFloat decimationPercent,simInt reserved1,const simFloat* reserved2);
SIM_DLLEXPORT simInt simCallScriptFunctionEx(simInt scriptHandleOrType,const simChar* functionNameAtScriptName,simInt stackId);
SIM_DLLEXPORT simChar* simGetExtensionString(simInt objectHandle,simInt index,const char* key);
SIM_DLLEXPORT simInt simComputeMassAndInertia(simInt shapeHandle,simFloat density);
SIM_DLLEXPORT simInt simCreateStack();
SIM_DLLEXPORT simInt simReleaseStack(simInt stackHandle);
SIM_DLLEXPORT simInt simCopyStack(simInt stackHandle);
SIM_DLLEXPORT simInt simPushNullOntoStack(simInt stackHandle);
SIM_DLLEXPORT simInt simPushBoolOntoStack(simInt stackHandle,simBool value);
SIM_DLLEXPORT simInt simPushInt32OntoStack(simInt stackHandle,simInt value);
SIM_DLLEXPORT simInt simPushInt64OntoStack(simInt stackHandle,simInt64 value);
SIM_DLLEXPORT simInt simPushFloatOntoStack(simInt stackHandle,simFloat value);
SIM_DLLEXPORT simInt simPushDoubleOntoStack(simInt stackHandle,simDouble value);
SIM_DLLEXPORT simInt simPushStringOntoStack(simInt stackHandle,const simChar* value,simInt stringSize);
SIM_DLLEXPORT simInt simPushUInt8TableOntoStack(simInt stackHandle,const simUChar* values,simInt valueCnt);
SIM_DLLEXPORT simInt simPushInt32TableOntoStack(simInt stackHandle,const simInt* values,simInt valueCnt);
SIM_DLLEXPORT simInt simPushInt64TableOntoStack(simInt stackHandle,const simInt64* values,simInt valueCnt);
SIM_DLLEXPORT simInt simPushFloatTableOntoStack(simInt stackHandle,const simFloat* values,simInt valueCnt);
SIM_DLLEXPORT simInt simPushDoubleTableOntoStack(simInt stackHandle,const simDouble* values,simInt valueCnt);
SIM_DLLEXPORT simInt simPushTableOntoStack(simInt stackHandle);
SIM_DLLEXPORT simInt simInsertDataIntoStackTable(simInt stackHandle);
SIM_DLLEXPORT simInt simGetStackSize(simInt stackHandle);
SIM_DLLEXPORT simInt simPopStackItem(simInt stackHandle,simInt count);
SIM_DLLEXPORT simInt simMoveStackItemToTop(simInt stackHandle,simInt cIndex);
SIM_DLLEXPORT simInt simIsStackValueNull(simInt stackHandle);
SIM_DLLEXPORT simInt simGetStackBoolValue(simInt stackHandle,simBool* boolValue);
SIM_DLLEXPORT simInt simGetStackInt32Value(simInt stackHandle,simInt* numberValue);
SIM_DLLEXPORT simInt simGetStackInt64Value(simInt stackHandle,simInt64* numberValue);
SIM_DLLEXPORT simInt simGetStackFloatValue(simInt stackHandle,simFloat* numberValue);
SIM_DLLEXPORT simInt simGetStackDoubleValue(simInt stackHandle,simDouble* numberValue);
SIM_DLLEXPORT simChar* simGetStackStringValue(simInt stackHandle,simInt* stringSize);
SIM_DLLEXPORT simInt simGetStackTableInfo(simInt stackHandle,simInt infoType);
SIM_DLLEXPORT simInt simGetStackUInt8Table(simInt stackHandle,simUChar* array,simInt count);
SIM_DLLEXPORT simInt simGetStackInt32Table(simInt stackHandle,simInt* array,simInt count);
SIM_DLLEXPORT simInt simGetStackInt64Table(simInt stackHandle,simInt64* array,simInt count);
SIM_DLLEXPORT simInt simGetStackFloatTable(simInt stackHandle,simFloat* array,simInt count);
SIM_DLLEXPORT simInt simGetStackDoubleTable(simInt stackHandle,simDouble* array,simInt count);
SIM_DLLEXPORT simInt simUnfoldStackTable(simInt stackHandle);
SIM_DLLEXPORT simInt simDebugStack(simInt stackHandle,simInt cIndex);
SIM_DLLEXPORT simFloat simGetEngineFloatParam(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
SIM_DLLEXPORT simInt simGetEngineInt32Param(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
SIM_DLLEXPORT simBool simGetEngineBoolParam(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
SIM_DLLEXPORT simInt simSetEngineFloatParam(simInt paramId,simInt objectHandle,const simVoid* object,simFloat val);
SIM_DLLEXPORT simInt simSetEngineInt32Param(simInt paramId,simInt objectHandle,const simVoid* object,simInt val);
SIM_DLLEXPORT simInt simSetEngineBoolParam(simInt paramId,simInt objectHandle,const simVoid* object,simBool val);
SIM_DLLEXPORT simInt simCreateOctree(simFloat voxelSize,simInt options,simFloat pointSize,simVoid* reserved);
SIM_DLLEXPORT simInt simCreatePointCloud(simFloat maxVoxelSize,simInt maxPtCntPerVoxel,simInt options,simFloat pointSize,simVoid* reserved);
SIM_DLLEXPORT simInt simSetPointCloudOptions(simInt pointCloudHandle,simFloat maxVoxelSize,simInt maxPtCntPerVoxel,simInt options,simFloat pointSize,simVoid* reserved);
SIM_DLLEXPORT simInt simGetPointCloudOptions(simInt pointCloudHandle,simFloat* maxVoxelSize,simInt* maxPtCntPerVoxel,simInt* options,simFloat* pointSize,simVoid* reserved);
SIM_DLLEXPORT simInt simInsertVoxelsIntoOctree(simInt octreeHandle,simInt options,const simFloat* pts,simInt ptCnt,const simUChar* color,const simUInt* tag,simVoid* reserved);
SIM_DLLEXPORT simInt simRemoveVoxelsFromOctree(simInt octreeHandle,simInt options,const simFloat* pts,simInt ptCnt,simVoid* reserved);
SIM_DLLEXPORT simInt simInsertPointsIntoPointCloud(simInt pointCloudHandle,simInt options,const simFloat* pts,simInt ptCnt,const simUChar* color,simVoid* optionalValues);
SIM_DLLEXPORT simInt simRemovePointsFromPointCloud(simInt pointCloudHandle,simInt options,const simFloat* pts,simInt ptCnt,simFloat tolerance,simVoid* reserved);
SIM_DLLEXPORT simInt simIntersectPointsWithPointCloud(simInt pointCloudHandle,simInt options,const simFloat* pts,simInt ptCnt,simFloat tolerance,simVoid* reserved);
SIM_DLLEXPORT const float* simGetOctreeVoxels(simInt octreeHandle,simInt* ptCnt,simVoid* reserved);
SIM_DLLEXPORT const float* simGetPointCloudPoints(simInt pointCloudHandle,simInt* ptCnt,simVoid* reserved);
SIM_DLLEXPORT simInt simInsertObjectIntoOctree(simInt octreeHandle,simInt objectHandle,simInt options,const simUChar* color,simUInt tag,simVoid* reserved);
SIM_DLLEXPORT simInt simSubtractObjectFromOctree(simInt octreeHandle,simInt objectHandle,simInt options,simVoid* reserved);
SIM_DLLEXPORT simInt simInsertObjectIntoPointCloud(simInt pointCloudHandle,simInt objectHandle,simInt options,simFloat gridSize,const simUChar* color,simVoid* optionalValues);
SIM_DLLEXPORT simInt simSubtractObjectFromPointCloud(simInt pointCloudHandle,simInt objectHandle,simInt options,simFloat tolerance,simVoid* reserved);
SIM_DLLEXPORT simInt simCheckOctreePointOccupancy(simInt octreeHandle,simInt options,const simFloat* points,simInt ptCnt,simUInt* tag,simUInt64* location,simVoid* reserved);
SIM_DLLEXPORT simChar* simOpenTextEditor(const simChar* initText,const simChar* xml,simInt* various);
SIM_DLLEXPORT simChar* simPackTable(simInt stackHandle,simInt* bufferSize);
SIM_DLLEXPORT simInt simUnpackTable(simInt stackHandle,const simChar* buffer,simInt bufferSize);
SIM_DLLEXPORT simInt simSetReferencedHandles(simInt objectHandle,simInt count,const simInt* referencedHandles,const simInt* reserved1,const simInt* reserved2);
SIM_DLLEXPORT simInt simGetReferencedHandles(simInt objectHandle,simInt** referencedHandles,simInt** reserved1,simInt** reserved2);
SIM_DLLEXPORT simInt simGetShapeViz(simInt shapeHandle,simInt index,struct SShapeVizInfo* info);
SIM_DLLEXPORT simInt simExecuteScriptString(simInt scriptHandleOrType,const simChar* stringAtScriptName,simInt stackHandle);
SIM_DLLEXPORT simChar* simGetApiFunc(simInt scriptHandleOrType,const simChar* apiWord);
SIM_DLLEXPORT simChar* simGetApiInfo(simInt scriptHandleOrType,const simChar* apiWord);
SIM_DLLEXPORT simInt simSetModuleInfo(const simChar* moduleName,simInt infoType,const simChar* stringInfo,simInt intInfo);
SIM_DLLEXPORT simInt simGetModuleInfo(const simChar* moduleName,simInt infoType,simChar** stringInfo,simInt* intInfo);
SIM_DLLEXPORT simInt simIsDeprecated(const simChar* funcOrConst);
SIM_DLLEXPORT simChar* simGetPersistentDataTags(simInt* tagCount);
SIM_DLLEXPORT simInt simEventNotification(const simChar* event);
SIM_DLLEXPORT simInt simApplyTexture(simInt shapeHandle,const simFloat* textureCoordinates,simInt textCoordSize,const simUChar* texture,const simInt* textureResolution,simInt options);
SIM_DLLEXPORT simInt simSetJointDependency(simInt jointHandle,simInt masterJointHandle,simFloat offset,simFloat multCoeff);
SIM_DLLEXPORT simInt simGetJointDependency(simInt jointHandle,simInt* masterJointHandle,simFloat* offset,simFloat* multCoeff);
SIM_DLLEXPORT simInt simAddLog(const simChar* pluginName,simInt verbosityLevel,const simChar* logMsg);
SIM_DLLEXPORT simInt simGetShapeMass(simInt shapeHandle,simFloat* mass);
SIM_DLLEXPORT simInt simSetShapeMass(simInt shapeHandle,simFloat mass);
SIM_DLLEXPORT simInt simGetShapeInertia(simInt shapeHandle,simFloat* inertiaMatrix,simFloat* transformationMatrix);
SIM_DLLEXPORT simInt simSetShapeInertia(simInt shapeHandle,const simFloat* inertiaMatrix,const simFloat* transformationMatrix);
SIM_DLLEXPORT simInt simIsDynamicallyEnabled(simInt objectHandle);
SIM_DLLEXPORT simInt simGenerateShapeFromPath(const simFloat* path,simInt pathSize,const simFloat* section,simInt sectionSize,simInt options,const simFloat* upVector,simFloat reserved);
SIM_DLLEXPORT simFloat simGetClosestPosOnPath(const simFloat* path,simInt pathSize,const simFloat* pathLengths,const simFloat* absPt);
SIM_DLLEXPORT simInt simInitScript(simInt scriptHandle);
SIM_DLLEXPORT simInt simModuleEntry(simInt handle,const simChar* label,simInt state);


SIM_DLLEXPORT simInt _simGetContactCallbackCount();
SIM_DLLEXPORT const void* _simGetContactCallback(simInt index);
SIM_DLLEXPORT simVoid _simSetDynamicSimulationIconCode(simVoid* object,simInt code);
SIM_DLLEXPORT simVoid _simSetDynamicObjectFlagForVisualization(simVoid* object,simInt flag);
SIM_DLLEXPORT simInt _simGetObjectListSize(simInt objType);
SIM_DLLEXPORT const simVoid* _simGetObjectFromIndex(simInt objType,simInt index);
SIM_DLLEXPORT simInt _simGetObjectID(const simVoid* object);
SIM_DLLEXPORT simInt _simGetObjectType(const simVoid* object);
SIM_DLLEXPORT const simVoid** _simGetObjectChildren(const simVoid* object,simInt* count);
SIM_DLLEXPORT const simVoid* _simGetGeomProxyFromShape(const simVoid* shape);
SIM_DLLEXPORT const simVoid* _simGetParentObject(const simVoid* object);
SIM_DLLEXPORT const simVoid* _simGetObject(int objID);
SIM_DLLEXPORT simVoid _simGetObjectLocalTransformation(const simVoid* object,simFloat* pos,simFloat* quat,simBool excludeFirstJointTransformation);
SIM_DLLEXPORT simVoid _simSetObjectLocalTransformation(simVoid* object,const simFloat* pos,const simFloat* quat);
SIM_DLLEXPORT simVoid _simDynReportObjectCumulativeTransformation(simVoid* object,const simFloat* pos,const simFloat* quat);
SIM_DLLEXPORT simVoid _simSetObjectCumulativeTransformation(simVoid* object,const simFloat* pos,const simFloat* quat,simBool keepChildrenInPlace);
SIM_DLLEXPORT simVoid _simGetObjectCumulativeTransformation(const simVoid* object,simFloat* pos,simFloat* quat,simBool excludeFirstJointTransformation);
SIM_DLLEXPORT simBool _simIsShapeDynamicallyStatic(const simVoid* shape);
SIM_DLLEXPORT simInt _simGetTreeDynamicProperty(const simVoid* object);
SIM_DLLEXPORT simInt _simGetDummyLinkType(const simVoid* dummy,simInt* linkedDummyID);
SIM_DLLEXPORT simInt _simGetJointMode(const simVoid* joint);
SIM_DLLEXPORT simBool _simIsJointInHybridOperation(const simVoid* joint);
SIM_DLLEXPORT simVoid _simDisableDynamicTreeForManipulation(const simVoid* object,simBool disableFlag);
SIM_DLLEXPORT simBool _simIsShapeDynamicallyRespondable(const simVoid* shape);
SIM_DLLEXPORT simInt _simGetDynamicCollisionMask(const simVoid* shape);
SIM_DLLEXPORT const simVoid* _simGetLastParentForLocalGlobalCollidable(const simVoid* shape);
SIM_DLLEXPORT simVoid _simSetShapeIsStaticAndNotRespondableButDynamicTag(const simVoid* shape,simBool tag);
SIM_DLLEXPORT simBool _simGetShapeIsStaticAndNotRespondableButDynamicTag(const simVoid* shape);
SIM_DLLEXPORT simVoid _simSetJointPosition(const simVoid* joint,simFloat pos);
SIM_DLLEXPORT simFloat _simGetJointPosition(const simVoid* joint);
SIM_DLLEXPORT simVoid _simSetDynamicMotorPositionControlTargetPosition(const simVoid* joint,simFloat pos);
SIM_DLLEXPORT simVoid _simGetInitialDynamicVelocity(const simVoid* shape,simFloat* vel);
SIM_DLLEXPORT simVoid _simSetInitialDynamicVelocity(simVoid* shape,const simFloat* vel);
SIM_DLLEXPORT simVoid _simGetInitialDynamicAngVelocity(const simVoid* shape,simFloat* angularVel);
SIM_DLLEXPORT simVoid _simSetInitialDynamicAngVelocity(simVoid* shape,const simFloat* angularVel);
SIM_DLLEXPORT simBool _simGetStartSleeping(const simVoid* shape);
SIM_DLLEXPORT simBool _simGetWasPutToSleepOnce(const simVoid* shape);
SIM_DLLEXPORT simBool _simGetDynamicsFullRefreshFlag(const simVoid* object);
SIM_DLLEXPORT simVoid _simSetDynamicsFullRefreshFlag(const simVoid* object,simBool flag);
SIM_DLLEXPORT simVoid _simSetGeomProxyDynamicsFullRefreshFlag(simVoid* geomData,simBool flag);
SIM_DLLEXPORT simBool _simGetGeomProxyDynamicsFullRefreshFlag(const simVoid* geomData);
SIM_DLLEXPORT simVoid _simSetShapeDynamicVelocity(simVoid* shape,const simFloat* linear,const simFloat* angular);
SIM_DLLEXPORT simVoid _simGetAdditionalForceAndTorque(const simVoid* shape,simFloat* force,simFloat* torque);
SIM_DLLEXPORT simVoid _simClearAdditionalForceAndTorque(const simVoid* shape);
SIM_DLLEXPORT simBool _simGetJointPositionInterval(const simVoid* joint,simFloat* minValue,simFloat* rangeValue);
SIM_DLLEXPORT simInt _simGetJointType(const simVoid* joint);
SIM_DLLEXPORT simBool _simIsDynamicMotorEnabled(const simVoid* joint);
SIM_DLLEXPORT simBool _simIsDynamicMotorPositionCtrlEnabled(const simVoid* joint);
SIM_DLLEXPORT simBool _simIsDynamicMotorTorqueModulationEnabled(const simVoid* joint);
SIM_DLLEXPORT simVoid _simGetMotorPid(const simVoid* joint,simFloat* pParam,simFloat* iParam,simFloat* dParam);
SIM_DLLEXPORT simFloat _simGetDynamicMotorTargetPosition(const simVoid* joint);
SIM_DLLEXPORT simFloat _simGetDynamicMotorTargetVelocity(const simVoid* joint);
SIM_DLLEXPORT simFloat _simGetDynamicMotorMaxForce(const simVoid* joint);
SIM_DLLEXPORT simFloat _simGetDynamicMotorUpperLimitVelocity(const simVoid* joint);
SIM_DLLEXPORT simVoid _simSetDynamicMotorReflectedPositionFromDynamicEngine(simVoid* joint,simFloat pos);
SIM_DLLEXPORT simVoid _simSetJointSphericalTransformation(simVoid* joint,const simFloat* quat);
SIM_DLLEXPORT simVoid _simAddForceSensorCumulativeForcesAndTorques(simVoid* forceSensor,const simFloat* force,const simFloat* torque,int totalPassesCount);
SIM_DLLEXPORT simVoid _simAddJointCumulativeForcesOrTorques(simVoid* joint,simFloat forceOrTorque,int totalPassesCount);
SIM_DLLEXPORT const simVoid* _simGetGeomWrapFromGeomProxy(const simVoid* geomData);
SIM_DLLEXPORT simVoid _simGetLocalInertiaFrame(const simVoid* geomInfo,simFloat* pos,simFloat* quat);
SIM_DLLEXPORT simInt _simGetPurePrimitiveType(const simVoid* geomInfo);
SIM_DLLEXPORT simBool _simIsGeomWrapGeometric(const simVoid* geomInfo);
SIM_DLLEXPORT simBool _simIsGeomWrapConvex(const simVoid* geomInfo);
SIM_DLLEXPORT simInt _simGetGeometricCount(const simVoid* geomInfo);
SIM_DLLEXPORT simVoid _simGetAllGeometrics(const simVoid* geomInfo,simVoid** allGeometrics);
SIM_DLLEXPORT simVoid _simGetPurePrimitiveSizes(const simVoid* geometric,simFloat* sizes);
SIM_DLLEXPORT simVoid _simMakeDynamicAnnouncement(int announceType);
SIM_DLLEXPORT simVoid _simGetVerticesLocalFrame(const simVoid* geometric,simFloat* pos,simFloat* quat);
SIM_DLLEXPORT const simFloat* _simGetHeightfieldData(const simVoid* geometric,simInt* xCount,simInt* yCount,simFloat* minHeight,simFloat* maxHeight);
SIM_DLLEXPORT simVoid _simGetCumulativeMeshes(const simVoid* geomInfo,simFloat** vertices,simInt* verticesSize,simInt** indices,simInt* indicesSize);
SIM_DLLEXPORT simFloat _simGetMass(const simVoid* geomInfo);
SIM_DLLEXPORT simVoid _simGetPrincipalMomentOfInertia(const simVoid* geomInfo,simFloat* inertia);
SIM_DLLEXPORT simVoid _simGetGravity(simFloat* gravity);
SIM_DLLEXPORT simInt _simGetTimeDiffInMs(simInt previousTime);
SIM_DLLEXPORT simBool _simDoEntitiesCollide(simInt entity1ID,simInt entity2ID,simInt* cacheBuffer,simBool overrideCollidableFlagIfShape1,simBool overrideCollidableFlagIfShape2,simBool pathOrMotionPlanningRoutineCalling);
SIM_DLLEXPORT simBool _simGetDistanceBetweenEntitiesIfSmaller(simInt entity1ID,simInt entity2ID,simFloat* distance,simFloat* ray,simInt* cacheBuffer,simBool overrideMeasurableFlagIfNonCollection1,simBool overrideMeasurableFlagIfNonCollection2,simBool pathPlanningRoutineCalling);
SIM_DLLEXPORT simInt _simHandleJointControl(const simVoid* joint,simInt auxV,const simInt* inputValuesInt,const simFloat* inputValuesFloat,simFloat* outputValues);
SIM_DLLEXPORT simInt _simHandleCustomContact(simInt objHandle1,simInt objHandle2,simInt engine,simInt* dataInt,simFloat* dataFloat);
SIM_DLLEXPORT const simVoid* _simGetIkGroupObject(int ikGroupID);
SIM_DLLEXPORT simInt _simMpHandleIkGroupObject(const simVoid* ikGroup);
SIM_DLLEXPORT simFloat _simGetPureHollowScaling(const simVoid* geometric);
SIM_DLLEXPORT simInt _simGetJointCallbackCallOrder(const simVoid* joint);
SIM_DLLEXPORT simVoid _simDynCallback(const simInt* intData,const simFloat* floatData);


// Following courtesy of Stephen James:
SIM_DLLEXPORT simInt simExtLaunchUIThread(const simChar* applicationName,simInt options,const simChar* sceneOrModelOrUiToLoad,const simChar* applicationDir_);
SIM_DLLEXPORT simInt simExtCanInitSimThread();
SIM_DLLEXPORT simInt simExtSimThreadInit();
SIM_DLLEXPORT simInt simExtSimThreadDestroy();
SIM_DLLEXPORT simInt simExtPostExitRequest();
SIM_DLLEXPORT simInt simExtGetExitRequest();
SIM_DLLEXPORT simInt simExtStep(simBool stepIfRunning);
SIM_DLLEXPORT simInt simExtCallScriptFunction(simInt scriptHandleOrType, const simChar* functionNameAtScriptName,
                                               const simInt* inIntData, simInt inIntCnt,
                                               const simFloat* inFloatData, simInt inFloatCnt,
                                               const simChar** inStringData, simInt inStringCnt,
                                               const simChar* inBufferData, simInt inBufferCnt,
                                               simInt** outIntData, simInt* outIntCnt,
                                               simFloat** outFloatData, simInt* outFloatCnt,
                                               simChar*** outStringData, simInt* outStringCnt,
                                               simChar** outBufferData, simInt* outBufferSize);


// Deprecated begin
SIM_DLLEXPORT simInt simGetMaterialId(const simChar* materialName);
SIM_DLLEXPORT simInt simGetShapeMaterial(simInt shapeHandle);
SIM_DLLEXPORT simInt simHandleVarious();
SIM_DLLEXPORT simInt simSerialPortOpen(simInt portNumber,simInt baudRate,simVoid* reserved1,simVoid* reserved2);
SIM_DLLEXPORT simInt simSerialPortClose(simInt portNumber);
SIM_DLLEXPORT simInt simSerialPortSend(simInt portNumber,const simChar* data,simInt dataLength);
SIM_DLLEXPORT simInt simSerialPortRead(simInt portNumber,simChar* buffer,simInt dataLengthToRead);
SIM_DLLEXPORT simInt simJointGetForce(simInt jointHandle,simFloat* forceOrTorque);
SIM_DLLEXPORT simInt simGetPathPlanningHandle(const simChar* pathPlanningObjectName);
SIM_DLLEXPORT simInt simGetMotionPlanningHandle(const simChar* motionPlanningObjectName);
SIM_DLLEXPORT simInt simGetMpConfigForTipPose(simInt motionPlanningObjectHandle,simInt options,simFloat closeNodesDistance,simInt trialCount,const simFloat* tipPose,simInt maxTimeInMs,simFloat* outputJointPositions,const simFloat* referenceConfigs,simInt referenceConfigCount,const simFloat* jointWeights,const simInt* jointBehaviour,simInt correctionPasses);
SIM_DLLEXPORT simFloat* simFindMpPath(simInt motionPlanningObjectHandle,const simFloat* startConfig,const simFloat* goalConfig,simInt options,simFloat stepSize,simInt* outputConfigsCnt,simInt maxTimeInMs,simFloat* reserved,const simInt* auxIntParams,const simFloat* auxFloatParams);
SIM_DLLEXPORT simFloat* simSimplifyMpPath(simInt motionPlanningObjectHandle,const simFloat* pathBuffer,simInt configCnt,simInt options,simFloat stepSize,simInt increment,simInt* outputConfigsCnt,simInt maxTimeInMs,simFloat* reserved,const simInt* auxIntParams,const simFloat* auxFloatParams);
SIM_DLLEXPORT simFloat* simFindIkPath(simInt motionPlanningObjectHandle,const simFloat* startConfig,const simFloat* goalPose,simInt options,simFloat stepSize,simInt* outputConfigsCnt,simFloat* reserved,const simInt* auxIntParams,const simFloat* auxFloatParams);
SIM_DLLEXPORT simFloat* simGetMpConfigTransition(simInt motionPlanningObjectHandle,const simFloat* startConfig,const simFloat* goalConfig,simInt options,const simInt* select,simFloat calcStepSize,simFloat maxOutStepSize,simInt wayPointCnt,const simFloat* wayPoints,simInt* outputConfigsCnt,const simInt* auxIntParams,const simFloat* auxFloatParams);
SIM_DLLEXPORT simInt simCreateMotionPlanning(simInt jointCnt,const simInt* jointHandles,const simInt* jointRangeSubdivisions,const simFloat* jointMetricWeights,simInt options,const simInt* intParams,const simFloat* floatParams,const simVoid* reserved);
SIM_DLLEXPORT simInt simRemoveMotionPlanning(simInt motionPlanningHandle);
SIM_DLLEXPORT simInt simSearchPath(simInt pathPlanningObjectHandle,simFloat maximumSearchTime);
SIM_DLLEXPORT simInt simInitializePathSearch(simInt pathPlanningObjectHandle,simFloat maximumSearchTime,simFloat searchTimeStep);
SIM_DLLEXPORT simInt simPerformPathSearchStep(simInt temporaryPathSearchObject,simBool abortSearch);
SIM_DLLEXPORT simInt simLockInterface(simBool locked);
SIM_DLLEXPORT simInt simCopyPasteSelectedObjects();
SIM_DLLEXPORT simInt simResetPath(simInt pathHandle);
SIM_DLLEXPORT simInt simHandlePath(simInt pathHandle,simFloat deltaTime);
SIM_DLLEXPORT simInt simResetJoint(simInt jointHandle);
SIM_DLLEXPORT simInt simHandleJoint(simInt jointHandle,simFloat deltaTime);
SIM_DLLEXPORT simInt simAppendScriptArrayEntry(const simChar* reservedSetToNull,simInt scriptHandleOrType,const simChar* arrayNameAtScriptName,const simChar* keyName,const simChar* data,const simInt* what);
SIM_DLLEXPORT simInt simClearScriptVariable(const simChar* reservedSetToNull,simInt scriptHandleOrType,const simChar* variableNameAtScriptName);
SIM_DLLEXPORT simVoid _simGetJointOdeParameters(const simVoid* joint,simFloat* stopERP,simFloat* stopCFM,simFloat* bounce,simFloat* fudge,simFloat* normalCFM);
SIM_DLLEXPORT simVoid _simGetJointBulletParameters(const simVoid* joint,simFloat* stopERP,simFloat* stopCFM,simFloat* normalCFM);
SIM_DLLEXPORT simVoid _simGetOdeMaxContactFrictionCFMandERP(const simVoid* geomInfo,simInt* maxContacts,simFloat* friction,simFloat* cfm,simFloat* erp);
SIM_DLLEXPORT simBool _simGetBulletCollisionMargin(const simVoid* geomInfo,simFloat* margin,simInt* otherProp);
SIM_DLLEXPORT simBool _simGetBulletStickyContact(const simVoid* geomInfo);
SIM_DLLEXPORT simFloat _simGetBulletRestitution(const simVoid* geomInfo);
SIM_DLLEXPORT simVoid _simGetVortexParameters(const simVoid* object,simInt version,simFloat* floatParams,simInt* intParams);
SIM_DLLEXPORT simVoid _simGetNewtonParameters(const simVoid* object,simInt* version,simFloat* floatParams,simInt* intParams);
SIM_DLLEXPORT simVoid _simGetDamping(const simVoid* geomInfo,simFloat* linDamping,simFloat* angDamping);
SIM_DLLEXPORT simFloat _simGetFriction(const simVoid* geomInfo);
SIM_DLLEXPORT simInt simAddSceneCustomData(simInt header,const simChar* data,simInt dataLength);
SIM_DLLEXPORT simInt simGetSceneCustomDataLength(simInt header);
SIM_DLLEXPORT simInt simGetSceneCustomData(simInt header,simChar* data);
SIM_DLLEXPORT simInt simAddObjectCustomData(simInt objectHandle,simInt header,const simChar* data,simInt dataLength);
SIM_DLLEXPORT simInt simGetObjectCustomDataLength(simInt objectHandle,simInt header);
SIM_DLLEXPORT simInt simGetObjectCustomData(simInt objectHandle,simInt header,simChar* data);
SIM_DLLEXPORT simInt simCreateUI(const simChar* uiName,simInt menuAttributes,const simInt* clientSize,const simInt* cellSize,simInt* buttonHandles);
SIM_DLLEXPORT simInt simCreateUIButton(simInt uiHandle,const simInt* position,const simInt* size,simInt buttonProperty);
SIM_DLLEXPORT simInt simGetUIHandle(const simChar* uiName);
SIM_DLLEXPORT simInt simGetUIProperty(simInt uiHandle);
SIM_DLLEXPORT simInt simGetUIEventButton(simInt uiHandle,simInt* auxiliaryValues);
SIM_DLLEXPORT simInt simSetUIProperty(simInt uiHandle,simInt elementProperty);
SIM_DLLEXPORT simInt simGetUIButtonProperty(simInt uiHandle,simInt buttonHandle);
SIM_DLLEXPORT simInt simSetUIButtonProperty(simInt uiHandle,simInt buttonHandle,simInt buttonProperty);
SIM_DLLEXPORT simInt simGetUIButtonSize(simInt uiHandle,simInt buttonHandle,simInt* size);
SIM_DLLEXPORT simInt simSetUIButtonLabel(simInt uiHandle,simInt buttonHandle,const simChar* upStateLabel,const simChar* downStateLabel);
SIM_DLLEXPORT simChar* simGetUIButtonLabel(simInt uiHandle,simInt buttonHandle);
SIM_DLLEXPORT simInt simSetUISlider(simInt uiHandle,simInt buttonHandle,simInt position);
SIM_DLLEXPORT simInt simGetUISlider(simInt uiHandle,simInt buttonHandle);
SIM_DLLEXPORT simInt simSetUIButtonColor(simInt uiHandle,simInt buttonHandle,const simFloat* upStateColor,const simFloat* downStateColor,const simFloat* labelColor);
SIM_DLLEXPORT simInt simSetUIButtonTexture(simInt uiHandle,simInt buttonHandle,const simInt* size,const simChar* textureData);
SIM_DLLEXPORT simInt simCreateUIButtonArray(simInt uiHandle,simInt buttonHandle);
SIM_DLLEXPORT simInt simSetUIButtonArrayColor(simInt uiHandle,simInt buttonHandle,const simInt* position,const simFloat* color);
SIM_DLLEXPORT simInt simDeleteUIButtonArray(simInt uiHandle,simInt buttonHandle);
SIM_DLLEXPORT simInt simRemoveUI(simInt uiHandle);
SIM_DLLEXPORT simInt simSetUIPosition(simInt uiHandle,const simInt* position);
SIM_DLLEXPORT simInt simGetUIPosition(simInt uiHandle,simInt* position);
SIM_DLLEXPORT simInt simLoadUI(const simChar* filename,simInt maxCount,simInt* uiHandles);
SIM_DLLEXPORT simInt simSaveUI(simInt count,const simInt* uiHandles,const simChar* filename);
SIM_DLLEXPORT simInt simHandleGeneralCallbackScript(simInt callbackId,simInt callbackTag,simVoid* additionalData);
SIM_DLLEXPORT simInt simRegisterCustomLuaFunction(const simChar* funcName,const simChar* callTips,const simInt* inputArgumentTypes,simVoid(*callBack)(struct SLuaCallBack* p));
SIM_DLLEXPORT simInt simRegisterCustomLuaVariable(const simChar* varName,const simChar* varValue);
SIM_DLLEXPORT simInt simRegisterContactCallback(simInt(*callBack)(simInt,simInt,simInt,simInt*,simFloat*));
SIM_DLLEXPORT simInt simRegisterJointCtrlCallback(simInt(*callBack)(simInt,simInt,simInt,const simInt*,const simFloat*,simFloat*));
SIM_DLLEXPORT simInt simGetMechanismHandle(const simChar* mechanismName);
SIM_DLLEXPORT simInt simHandleMechanism(simInt mechanismHandle);
SIM_DLLEXPORT simInt simHandleCustomizationScripts(simInt callType);
SIM_DLLEXPORT simInt simCallScriptFunction(simInt scriptHandleOrType,const simChar* functionNameAtScriptName,SLuaCallBack* data,const simChar* reservedSetToNull);
SIM_DLLEXPORT simInt simSetVisionSensorFilter(simInt visionSensorHandle,simInt filterIndex,simInt options,const simInt* pSizes,const simUChar* bytes,const simInt* ints,const simFloat* floats,const simUChar* custom);
SIM_DLLEXPORT simInt simGetVisionSensorFilter(simInt visionSensorHandle,simInt filterIndex,simInt* options,simInt* pSizes,simUChar** bytes,simInt** ints,simFloat** floats,simUChar** custom);
SIM_DLLEXPORT simChar* simGetScriptSimulationParameter(simInt scriptHandle,const simChar* parameterName,simInt* parameterLength);
SIM_DLLEXPORT simInt simSetScriptSimulationParameter(simInt scriptHandle,const simChar* parameterName,const simChar* parameterValue,simInt parameterLength);
SIM_DLLEXPORT simInt simSetJointForce(simInt objectHandle,simFloat forceOrTorque);
SIM_DLLEXPORT simInt simHandleMill(simInt millHandle,simFloat* removedSurfaceAndVolume);
SIM_DLLEXPORT simInt simResetMill(simInt millHandle);
SIM_DLLEXPORT simInt simResetMilling(simInt objectHandle);
SIM_DLLEXPORT simInt simApplyMilling(simInt objectHandle);
SIM_DLLEXPORT simBool _simGetParentFollowsDynamic(const simVoid* shape);
SIM_DLLEXPORT simInt simGetNameSuffix(const simChar* name);
SIM_DLLEXPORT simInt simSetNameSuffix(simInt nameSuffixNumber);
SIM_DLLEXPORT simInt simAddStatusbarMessage(const simChar* message);
SIM_DLLEXPORT simChar* simGetScriptRawBuffer(simInt scriptHandle,simInt bufferHandle);
SIM_DLLEXPORT simInt simSetScriptRawBuffer(simInt scriptHandle,const simChar* buffer,simInt bufferSize);
SIM_DLLEXPORT simInt simReleaseScriptRawBuffer(simInt scriptHandle,simInt bufferHandle);
SIM_DLLEXPORT simInt simSetShapeMassAndInertia(simInt shapeHandle,simFloat mass,const simFloat* inertiaMatrix,const simFloat* centerOfMass,const simFloat* transformation);
SIM_DLLEXPORT simInt simGetShapeMassAndInertia(simInt shapeHandle,simFloat* mass,simFloat* inertiaMatrix,simFloat* centerOfMass,const simFloat* transformation);
SIM_DLLEXPORT simInt simCheckIkGroup(simInt ikGroupHandle,simInt jointCnt,const simInt* jointHandles,simFloat* jointValues,const simInt* jointOptions);
SIM_DLLEXPORT simInt simCreateIkGroup(simInt options,const simInt* intParams,const simFloat* floatParams,const simVoid* reserved);
SIM_DLLEXPORT simInt simRemoveIkGroup(simInt ikGroupHandle);
SIM_DLLEXPORT simInt simCreateIkElement(simInt ikGroupHandle,simInt options,const simInt* intParams,const simFloat* floatParams,const simVoid* reserved);
SIM_DLLEXPORT simInt simExportIk(const simChar* pathAndFilename,simInt reserved1,simVoid* reserved2);
SIM_DLLEXPORT simInt simComputeJacobian(simInt ikGroupHandle,simInt options,simVoid* reserved);
SIM_DLLEXPORT simInt simGetConfigForTipPose(simInt ikGroupHandle,simInt jointCnt,const simInt* jointHandles,simFloat thresholdDist,simInt maxTimeInMs,simFloat* retConfig,const simFloat* metric,simInt collisionPairCnt,const simInt* collisionPairs,const simInt* jointOptions,const simFloat* lowLimits,const simFloat* ranges,simVoid* reserved);
SIM_DLLEXPORT simFloat* simGenerateIkPath(simInt ikGroupHandle,simInt jointCnt,const simInt* jointHandles,simInt ptCnt,simInt collisionPairCnt,const simInt* collisionPairs,const simInt* jointOptions,simVoid* reserved);
SIM_DLLEXPORT simInt simGetIkGroupHandle(const simChar* ikGroupName);
SIM_DLLEXPORT simFloat* simGetIkGroupMatrix(simInt ikGroupHandle,simInt options,simInt* matrixSize);
SIM_DLLEXPORT simInt simHandleIkGroup(simInt ikGroupHandle);
SIM_DLLEXPORT simInt simSetIkGroupProperties(simInt ikGroupHandle,simInt resolutionMethod,simInt maxIterations,simFloat damping,void* reserved);
SIM_DLLEXPORT simInt simSetIkElementProperties(simInt ikGroupHandle,simInt tipDummyHandle,simInt constraints,const simFloat* precision,const simFloat* weight,void* reserved);
SIM_DLLEXPORT simInt simSetThreadIsFree(simBool freeMode);
SIM_DLLEXPORT simInt simTubeOpen(simInt dataHeader,const simChar* dataName,simInt readBufferSize,simBool notUsedButKeepZero);
SIM_DLLEXPORT simInt simTubeClose(simInt tubeHandle);
SIM_DLLEXPORT simInt simTubeWrite(simInt tubeHandle,const simChar* data,simInt dataLength);
SIM_DLLEXPORT simChar* simTubeRead(simInt tubeHandle,simInt* dataLength);
SIM_DLLEXPORT simInt simTubeStatus(simInt tubeHandle,simInt* readPacketsCount,simInt* writePacketsCount);
SIM_DLLEXPORT simInt simSendData(simInt targetID,simInt dataHeader,const simChar* dataName,const simChar* data,simInt dataLength,simInt antennaHandle,simFloat actionRadius,simFloat emissionAngle1,simFloat emissionAngle2,simFloat persistence);
SIM_DLLEXPORT simChar* simReceiveData(simInt dataHeader,const simChar* dataName,simInt antennaHandle,simInt index,simInt* dataLength,simInt* senderID,simInt* dataHeaderR,simChar** dataNameR);
SIM_DLLEXPORT simInt simGetPositionOnPath(simInt pathHandle,simFloat relativeDistance,simFloat* position);
SIM_DLLEXPORT simInt simGetDataOnPath(simInt pathHandle,simFloat relativeDistance,simInt dataType,simInt* intData,simFloat* floatData);
SIM_DLLEXPORT simInt simGetOrientationOnPath(simInt pathHandle,simFloat relativeDistance,simFloat* eulerAngles);
SIM_DLLEXPORT simInt simGetClosestPositionOnPath(simInt pathHandle,simFloat* absolutePosition,simFloat* pathPosition);
SIM_DLLEXPORT simInt simGetPathPosition(simInt objectHandle,simFloat* position);
SIM_DLLEXPORT simInt simSetPathPosition(simInt objectHandle,simFloat position);
SIM_DLLEXPORT simInt simGetPathLength(simInt objectHandle,simFloat* length);
SIM_DLLEXPORT simInt simCreatePath(simInt attributes,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
SIM_DLLEXPORT simInt simInsertPathCtrlPoints(simInt pathHandle,simInt options,simInt startIndex,simInt ptCnt,const simVoid* ptData);
SIM_DLLEXPORT simInt simCutPathCtrlPoints(simInt pathHandle,simInt startIndex,simInt ptCnt);
SIM_DLLEXPORT simInt simGetThreadId();
SIM_DLLEXPORT simInt simSwitchThread();
SIM_DLLEXPORT simInt simLockResources(simInt lockType,simInt reserved);
SIM_DLLEXPORT simInt simUnlockResources(simInt lockHandle);
SIM_DLLEXPORT simChar* simGetUserParameter(simInt objectHandle,const simChar* parameterName,simInt* parameterLength);
SIM_DLLEXPORT simInt simSetUserParameter(simInt objectHandle,const simChar* parameterName,const simChar* parameterValue,simInt parameterLength);
SIM_DLLEXPORT simInt simSetPathTargetNominalVelocity(simInt objectHandle,simFloat targetNominalVelocity);
SIM_DLLEXPORT simInt simGetCollectionHandle(const simChar* collectionName);
SIM_DLLEXPORT simInt simRemoveCollection(simInt collectionHandle);
SIM_DLLEXPORT simInt simEmptyCollection(simInt collectionHandle);
SIM_DLLEXPORT simChar* simGetCollectionName(simInt collectionHandle);
SIM_DLLEXPORT simInt simSetCollectionName(simInt collectionHandle,const simChar* collectionName);
SIM_DLLEXPORT simInt simCreateCollection(const simChar* collectionName,simInt options);
SIM_DLLEXPORT simInt simAddObjectToCollection(simInt collectionHandle,simInt objectHandle,simInt what,simInt options);
SIM_DLLEXPORT simInt simGetCollisionHandle(const simChar* collisionObjectName);
SIM_DLLEXPORT simInt simGetDistanceHandle(const simChar* distanceObjectName);
SIM_DLLEXPORT simInt simResetCollision(simInt collisionObjectHandle);
SIM_DLLEXPORT simInt simResetDistance(simInt distanceObjectHandle);
SIM_DLLEXPORT simInt simHandleCollision(simInt collisionObjectHandle);
SIM_DLLEXPORT simInt simReadCollision(simInt collisionObjectHandle);
SIM_DLLEXPORT simInt simHandleDistance(simInt distanceObjectHandle,simFloat* smallestDistance);
SIM_DLLEXPORT simInt simReadDistance(simInt distanceObjectHandle,simFloat* smallestDistance);
SIM_DLLEXPORT simInt simAddBanner(const simChar* label,simFloat size,simInt options,const simFloat* positionAndEulerAngles,simInt parentObjectHandle,const simFloat* labelColors,const simFloat* backgroundColors);
SIM_DLLEXPORT simInt simRemoveBanner(simInt bannerID);
SIM_DLLEXPORT simInt simAddGhost(simInt ghostGroup,simInt objectHandle,simInt options,simFloat startTime,simFloat endTime,const simFloat* color);
SIM_DLLEXPORT simInt simModifyGhost(simInt ghostGroup,simInt ghostId,simInt operation,simFloat floatValue,simInt options,simInt optionsMask,const simFloat* colorOrTransformation);
SIM_DLLEXPORT simInt simSetGraphUserData(simInt graphHandle,const simChar* streamName,simFloat data);
SIM_DLLEXPORT simInt simAddPointCloud(simInt pageMask,simInt layerMask,simInt objectHandle,simInt options,simFloat pointSize,simInt ptCnt,const simFloat* pointCoordinates,const simChar* defaultColors,const simChar* pointColors,const simFloat* pointNormals);
SIM_DLLEXPORT simInt simModifyPointCloud(simInt pointCloudHandle,simInt operation,const simInt* intParam,const simFloat* floatParam);
SIM_DLLEXPORT simInt simCopyMatrix(const simFloat* matrixIn,simFloat* matrixOut);
SIM_DLLEXPORT simInt simGetObjectIntParameter(simInt objectHandle,simInt ParamID,simInt* Param);
SIM_DLLEXPORT simInt simSetObjectIntParameter(simInt objectHandle,simInt ParamID,simInt Param);
SIM_DLLEXPORT simInt simGetObjectInt32Parameter(simInt objectHandle,simInt ParamID,simInt* Param);
SIM_DLLEXPORT simInt simSetObjectInt32Parameter(simInt objectHandle,simInt ParamID,simInt Param);
SIM_DLLEXPORT simInt simGetObjectFloatParameter(simInt objectHandle,simInt ParamID,simFloat* Param);
SIM_DLLEXPORT simInt simSetObjectFloatParameter(simInt objectHandle,simInt ParamID,simFloat Param);
SIM_DLLEXPORT simChar* simGetObjectStringParameter(simInt objectHandle,simInt ParamID,simInt* ParamLength);
SIM_DLLEXPORT simInt simSetObjectStringParameter(simInt objectHandle,simInt ParamID,const simChar* Param,simInt ParamLength);
SIM_DLLEXPORT simInt simSetBooleanParameter(simInt parameter,simBool boolState);
SIM_DLLEXPORT simInt simGetBooleanParameter(simInt parameter);
SIM_DLLEXPORT simInt simSetBoolParameter(simInt parameter,simBool boolState);
SIM_DLLEXPORT simInt simGetBoolParameter(simInt parameter);
SIM_DLLEXPORT simInt simSetIntegerParameter(simInt parameter,simInt intState);
SIM_DLLEXPORT simInt simGetIntegerParameter(simInt parameter,simInt* intState);
SIM_DLLEXPORT simInt simSetInt32Parameter(simInt parameter,simInt intState);
SIM_DLLEXPORT simInt simGetInt32Parameter(simInt parameter,simInt* intState);
SIM_DLLEXPORT simInt simGetUInt64Parameter(simInt parameter,simUInt64* intState);
SIM_DLLEXPORT simInt simSetFloatingParameter(simInt parameter,simFloat floatState);
SIM_DLLEXPORT simInt simGetFloatingParameter(simInt parameter,simFloat* floatState);
SIM_DLLEXPORT simInt simSetFloatParameter(simInt parameter,simFloat floatState);
SIM_DLLEXPORT simInt simGetFloatParameter(simInt parameter,simFloat* floatState);
SIM_DLLEXPORT simInt simSetStringParameter(simInt parameter,const simChar* str);
SIM_DLLEXPORT simChar* simGetStringParameter(simInt parameter);
SIM_DLLEXPORT simInt simSetArrayParameter(simInt parameter,const simVoid* arrayOfValues);
SIM_DLLEXPORT simInt simGetArrayParameter(simInt parameter,simVoid* arrayOfValues);
SIM_DLLEXPORT simFloat simGetEngineFloatParameter(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
SIM_DLLEXPORT simInt simGetEngineInt32Parameter(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
SIM_DLLEXPORT simBool simGetEngineBoolParameter(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
SIM_DLLEXPORT simInt simSetEngineFloatParameter(simInt paramId,simInt objectHandle,const simVoid* object,simFloat val);
SIM_DLLEXPORT simInt simSetEngineInt32Parameter(simInt paramId,simInt objectHandle,const simVoid* object,simInt val);
SIM_DLLEXPORT simInt simSetEngineBoolParameter(simInt paramId,simInt objectHandle,const simVoid* object,simBool val);
SIM_DLLEXPORT simInt simIsHandleValid(simInt generalObjectHandle,simInt generalObjectType);
SIM_DLLEXPORT simInt simAddModuleMenuEntry(const simChar* entryLabel,simInt itemCount,simInt* itemHandles);
SIM_DLLEXPORT simInt simSetModuleMenuItemState(simInt itemHandle,simInt state,const simChar* label);
SIM_DLLEXPORT simInt simSetIntegerSignal(const simChar* signalName,simInt signalValue);
SIM_DLLEXPORT simInt simGetIntegerSignal(const simChar* signalName,simInt* signalValue);
SIM_DLLEXPORT simInt simClearIntegerSignal(const simChar* signalName);
SIM_DLLEXPORT simChar* simGetObjectName(simInt objectHandle);
SIM_DLLEXPORT simInt simSetObjectName(simInt objectHandle,const simChar* objectName);
SIM_DLLEXPORT simChar* simGetScriptName(simInt scriptHandle);
SIM_DLLEXPORT simInt simGetScriptHandle(const simChar* scriptName);
SIM_DLLEXPORT simInt simSetScriptVariable(simInt scriptHandleOrType,const simChar* variableNameAtScriptName,simInt stackHandle);
SIM_DLLEXPORT simInt simGetObjectHandle(const simChar* objectAlias);
SIM_DLLEXPORT simInt simGetScript(simInt index);
SIM_DLLEXPORT simInt simGetScriptAssociatedWithObject(simInt objectHandle);
SIM_DLLEXPORT simInt simGetCustomizationScriptAssociatedWithObject(simInt objectHandle);
SIM_DLLEXPORT simInt simGetObjectAssociatedWithScript(simInt scriptHandle);
SIM_DLLEXPORT simChar* simGetObjectConfiguration(simInt objectHandle);
SIM_DLLEXPORT simInt simSetObjectConfiguration(const simChar* data);
SIM_DLLEXPORT simChar* simGetConfigurationTree(simInt objectHandle);
SIM_DLLEXPORT simInt simSetConfigurationTree(const simChar* data);
SIM_DLLEXPORT simInt simEnableEventCallback(simInt eventCallbackType,const simChar* plugin,simInt reserved);
SIM_DLLEXPORT simInt simSetObjectSizeValues(simInt objectHandle,const simFloat* sizeValues);
SIM_DLLEXPORT simInt simGetObjectSizeValues(simInt objectHandle,simFloat* sizeValues);
SIM_DLLEXPORT simInt simRMLPosition(simInt dofs,simDouble timeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxVelAccelJerk,const simBool* selection,const simDouble* targetPosVel,simDouble* newPosVelAccel,simVoid* auxData);
SIM_DLLEXPORT simInt simRMLVelocity(simInt dofs,simDouble timeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxAccelJerk,const simBool* selection,const simDouble* targetVel,simDouble* newPosVelAccel,simVoid* auxData);
SIM_DLLEXPORT simInt simRMLPos(simInt dofs,simDouble smallestTimeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxVelAccelJerk,const simBool* selection,const simDouble* targetPosVel,simVoid* auxData);
SIM_DLLEXPORT simInt simRMLVel(simInt dofs,simDouble smallestTimeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxAccelJerk,const simBool* selection,const simDouble* targetVel,simVoid* auxData);
SIM_DLLEXPORT simInt simRMLStep(simInt handle,simDouble timeStep,simDouble* newPosVelAccel,simVoid* auxData,simVoid* reserved);
SIM_DLLEXPORT simInt simRMLRemove(simInt handle);
SIM_DLLEXPORT simFloat simGetSystemTime();
SIM_DLLEXPORT simInt simGetSystemTimeInMilliseconds();
SIM_DLLEXPORT simChar* simFileDialog(simInt mode,const simChar* title,const simChar* startPath,const simChar* initName,const simChar* extName,const simChar* ext);
SIM_DLLEXPORT simInt simMsgBox(simInt dlgType,simInt buttons,const simChar* title,const simChar* message);
SIM_DLLEXPORT simInt simDisplayDialog(const simChar* titleText,const simChar* mainText,simInt dialogType,const simChar* initialText,const simFloat* titleColors,const simFloat* dialogColors,simInt* elementHandle);
SIM_DLLEXPORT simInt simGetDialogResult(simInt genericDialogHandle);
SIM_DLLEXPORT simChar* simGetDialogInput(simInt genericDialogHandle);
SIM_DLLEXPORT simInt simEndDialog(simInt genericDialogHandle);
SIM_DLLEXPORT simInt simIsObjectInSelection(simInt objectHandle);
SIM_DLLEXPORT simInt simAddObjectToSelection(simInt what,simInt objectHandle);
SIM_DLLEXPORT simInt simRemoveObjectFromSelection(simInt what,simInt objectHandle);
SIM_DLLEXPORT simInt simGetObjectSelectionSize();
SIM_DLLEXPORT simInt simGetObjectLastSelection();
SIM_DLLEXPORT simInt simGetObjectSelection(simInt* objectHandles);
SIM_DLLEXPORT simInt simScaleSelectedObjects(simFloat scalingFactor,simBool scalePositionsToo);
SIM_DLLEXPORT simInt simDeleteSelectedObjects();
SIM_DLLEXPORT simInt simSetStringNamedParam(const simChar* paramName,const simChar* stringParam,simInt paramLength);
SIM_DLLEXPORT simChar* simGetStringNamedParam(const simChar* paramName,simInt* paramLength);
SIM_DLLEXPORT simInt simGetObjectUniqueIdentifier(simInt objectHandle,simInt* uniqueIdentifier);
SIM_DLLEXPORT simVoid _simSetDynamicJointLocalTransformationPart2(simVoid* joint,const simFloat* pos,const simFloat* quat);
SIM_DLLEXPORT simVoid _simSetDynamicForceSensorLocalTransformationPart2(simVoid* forceSensor,const simFloat* pos,const simFloat* quat);
SIM_DLLEXPORT simVoid _simSetDynamicJointLocalTransformationPart2IsValid(simVoid* joint,simBool valid);
SIM_DLLEXPORT simVoid _simSetDynamicForceSensorLocalTransformationPart2IsValid(simVoid* forceSensor,simBool valid);
SIM_DLLEXPORT simInt simBreakForceSensor(simInt objectHandle);
SIM_DLLEXPORT simBool _simIsForceSensorBroken(const simVoid* forceSensor);
SIM_DLLEXPORT simVoid _simGetDynamicForceSensorLocalTransformationPart2(const simVoid* forceSensor,simFloat* pos,simFloat* quat);
SIM_DLLEXPORT simInt simGetJointMatrix(simInt objectHandle,simFloat* matrix);
SIM_DLLEXPORT simInt simSetSphericalJointMatrix(simInt objectHandle,const simFloat* matrix);
// Deprecated end

#endif // !defined(sim_INCLUDED_)
