
#if !defined(V_REP_internal_INCLUDED_)
#define V_REP_internal_INCLUDED_

#include "vrepMainHeader.h"
#include "v_repConst.h"
#include "v_repTypes.h"

std::vector<contactCallback>& getAllContactCallbacks();
std::vector<jointCtrlCallback>& getAllJointCtrlCallbacks();

void quicklyDisableAndAutomaticallyReenableCNameSuffixAdjustment();
void enableCNameSuffixAdjustment();
std::string getCNameSuffixAdjustedName(const char* name);
void setCNameSuffixNumber(int number);
int getCNameSuffixNumber();

simInt simRunSimulator_internal(const simChar* applicationName,simInt options,simVoid(*initCallBack)(),simVoid(*loopCallBack)(),simVoid(*deinitCallBack)(),simInt stopDelay,const simChar* sceneOrModelToLoad,bool launchSimThread);
simVoid* simGetMainWindow_internal(simInt type);
simChar* simGetLastError_internal();
simInt simSetBoolParameter_internal(simInt parameter,simBool boolState);
simInt simGetBoolParameter_internal(simInt parameter);
simInt simSetInt32Parameter_internal(simInt parameter,simInt intState);
simInt simGetInt32Parameter_internal(simInt parameter,simInt* intState);
simInt simGetUInt64Parameter_internal(simInt parameter,simUInt64* intState);
simInt simSetFloatParameter_internal(simInt parameter,simFloat floatState);
simInt simGetFloatParameter_internal(simInt parameter,simFloat* floatState);
simInt simSetStringParameter_internal(simInt parameter,const simChar* str);
simChar* simGetStringParameter_internal(simInt parameter);
simInt simGetObjectHandle_internal(const simChar* objectName);
simInt simRemoveObject_internal(simInt objectHandle);
simInt simRemoveModel_internal(simInt objectHandle);
simChar* simGetObjectName_internal(simInt objectHandle);
simInt simGetObjects_internal(simInt index,simInt objectType);
simInt simSetObjectName_internal(simInt objectHandle,const simChar* objectName);
simInt simGetCollectionHandle_internal(const simChar* collectionName);
simInt simRemoveCollection_internal(simInt collectionHandle);
simInt simEmptyCollection_internal(simInt collectionHandle);
simChar* simGetCollectionName_internal(simInt collectionHandle);
simInt simSetCollectionName_internal(simInt collectionHandle,const simChar* collectionName);
simInt simGetObjectMatrix_internal(simInt objectHandle,simInt relativeToObjectHandle,simFloat* matrix);
simInt simSetObjectMatrix_internal(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* matrix);
simInt simGetObjectPosition_internal(simInt objectHandle,simInt relativeToObjectHandle,simFloat* position);
simInt simSetObjectPosition_internal(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* position);
simInt simGetObjectOrientation_internal(simInt objectHandle,simInt relativeToObjectHandle,simFloat* eulerAngles);
simInt simGetObjectQuaternion_internal(simInt objectHandle,simInt relativeToObjectHandle,simFloat* quaternion);
simInt simSetObjectQuaternion_internal(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* quaternion);
simInt simSetObjectOrientation_internal(simInt objectHandle,simInt relativeToObjectHandle,const simFloat* eulerAngles);
simInt simGetJointPosition_internal(simInt objectHandle,simFloat* position);
simInt simSetJointPosition_internal(simInt objectHandle,simFloat position);
simInt simSetJointTargetPosition_internal(simInt objectHandle,simFloat targetPosition);
simInt simGetJointTargetPosition_internal(simInt objectHandle,simFloat* targetPosition);
simInt simSetJointForce_internal(simInt objectHandle,simFloat forceOrTorque);
simInt simGetPathPosition_internal(simInt objectHandle,simFloat* position);
simInt simSetPathPosition_internal(simInt objectHandle,simFloat position);
simInt simGetPathLength_internal(simInt objectHandle,simFloat* length);
simInt simGetJointMatrix_internal(simInt objectHandle,simFloat* matrix);
simInt simSetSphericalJointMatrix_internal(simInt objectHandle,const simFloat* matrix);
simInt simGetJointInterval_internal(simInt objectHandle,simBool* cyclic,simFloat* interval);
simInt simSetJointInterval_internal(simInt objectHandle,simBool cyclic,const simFloat* interval);
simInt simGetObjectParent_internal(simInt objectHandle);
simInt simGetObjectChild_internal(simInt objectHandle,simInt index);
simInt simSetObjectParent_internal(simInt objectHandle,simInt parentObjectHandle,simBool keepInPlace);
simInt simGetObjectType_internal(simInt objectHandle);
simInt simGetJointType_internal(simInt objectHandle);
simInt simBuildIdentityMatrix_internal(simFloat* matrix);
simInt simCopyMatrix_internal(const simFloat* matrixIn,simFloat* matrixOut);
simInt simBuildMatrix_internal(const simFloat* position,const simFloat* eulerAngles,simFloat* matrix);
simInt simBuildMatrixQ_internal(const simFloat* position,const simFloat* quaternion,simFloat* matrix);
simInt simGetEulerAnglesFromMatrix_internal(const simFloat* matrix,simFloat* eulerAngles);
simInt simGetQuaternionFromMatrix_internal(const simFloat* matrix,simFloat* quaternion);
simInt simInvertMatrix_internal(simFloat* matrix);
simInt simMultiplyMatrices_internal(const simFloat* matrixIn1,const simFloat* matrixIn2,simFloat* matrixOut);
simInt simInterpolateMatrices_internal(const simFloat* matrixIn1,const simFloat* matrixIn2,simFloat interpolFactor,simFloat* matrixOut);
simInt simTransformVector_internal(const simFloat* matrix,simFloat* vect);
simInt simReservedCommand_internal(simInt v,simInt w);
simFloat simGetSimulationTime_internal();
simInt simGetSimulationState_internal();
simFloat simGetSystemTime_internal();
simInt simGetSystemTimeInMilliseconds_internal();
simUInt simGetSystemTimeInMs_internal(simInt previousTime);
simInt simLoadScene_internal(const simChar* filename);
simInt simCloseScene_internal();
simInt simSaveScene_internal(const simChar* filename);
simInt simLoadModel_internal(const simChar* filename);
simInt simSaveModel_internal(int baseOfModelHandle,const simChar* filename);
simInt simAddStatusbarMessage_internal(const simChar* message);
simChar* simGetSimulatorMessage_internal(simInt* messageID,simInt* auxiliaryData,simInt* returnedDataSize);
simInt simAddModuleMenuEntry_internal(const simChar* entryLabel,simInt itemCount,simInt* itemHandles);
simInt simSetModuleMenuItemState_internal(simInt itemHandle,simInt state,const simChar* label);
simInt simDoesFileExist_internal(const simChar* filename);
simInt simIsObjectInSelection_internal(simInt objectHandle);
simInt simAddObjectToSelection_internal(simInt what,simInt objectHandle);
simInt simRemoveObjectFromSelection_internal(simInt what,simInt objectHandle);
simInt simGetObjectSelectionSize_internal();
simInt simGetObjectLastSelection_internal();
simInt simGetObjectSelection_internal(simInt* objectHandles);
simInt simHandleCollision_internal(simInt collisionObjectHandle);
simInt simReadCollision_internal(simInt collisionObjectHandle);
simInt simHandleDistance_internal(simInt distanceObjectHandle,simFloat* smallestDistance);
simInt simReadDistance_internal(simInt distanceObjectHandle,simFloat* smallestDistance);
simInt simHandleProximitySensor_internal(simInt sensorHandle,simFloat* detectedPoint,simInt* detectedObjectHandle,simFloat* normalVector);
simInt simReadProximitySensor_internal(simInt sensorHandle,simFloat* detectedPoint,simInt* detectedObjectHandle,simFloat* normalVector);
simInt simHandleMill_internal(simInt millHandle,simFloat* removedSurfaceAndVolume);
simInt simHandleIkGroup_internal(simInt ikGroupHandle);
simInt simCheckIkGroup_internal(simInt ikGroupHandle,simInt jointCnt,const simInt* jointHandles,simFloat* jointValues,const simInt* jointOptions);
simInt simHandleDynamics_internal(simFloat deltaTime);
simInt simGetScriptHandle_internal(const simChar* scriptName);
simInt simSetScriptText_internal(simInt scriptHandle,const simChar* scriptText);
const simChar* simGetScriptText_internal(simInt scriptHandle);
simInt simGetScriptProperty_internal(simInt scriptHandle,simInt* scriptProperty,simInt* associatedObjectHandle);
simInt simAssociateScriptWithObject_internal(simInt scriptHandle,simInt associatedObjectHandle);
simInt simGetScript_internal(simInt index);
simInt simGetScriptAssociatedWithObject_internal(simInt objectHandle);
simInt simGetCustomizationScriptAssociatedWithObject_internal(simInt objectHandle);
simInt simGetObjectAssociatedWithScript_internal(simInt scriptHandle);
simChar* simGetScriptName_internal(simInt scriptHandle);
simInt simHandleMainScript_internal();
simInt simResetScript_internal(simInt scriptHandle);
simInt simAddScript_internal(simInt scriptProperty);
simInt simRemoveScript_internal(simInt scriptHandle);
simInt simRefreshDialogs_internal(simInt refreshDegree);
simInt simGetCollisionHandle_internal(const simChar* collisionObjectName);
simInt simGetDistanceHandle_internal(const simChar* distanceObjectName);
simInt simGetIkGroupHandle_internal(const simChar* ikGroupName);
simInt simResetCollision_internal(simInt collisionObjectHandle);
simInt simResetDistance_internal(simInt distanceObjectHandle);
simInt simResetProximitySensor_internal(simInt sensorHandle);
simInt simResetMill_internal(simInt millHandle);
simInt simCheckProximitySensor_internal(simInt sensorHandle,simInt entityHandle,simFloat* detectedPoint);
simInt simCheckProximitySensorEx_internal(simInt sensorHandle,simInt entityHandle,simInt detectionMode,simFloat detectionThreshold,simFloat maxAngle,simFloat* detectedPoint,simInt* detectedObjectHandle,simFloat* normalVector);
simInt simCheckProximitySensorEx2_internal(simInt sensorHandle,simFloat* vertexPointer,simInt itemType,simInt itemCount,simInt detectionMode,simFloat detectionThreshold,simFloat maxAngle,simFloat* detectedPoint,simFloat* normalVector);
simChar* simCreateBuffer_internal(simInt size);
simInt simReleaseBuffer_internal(const simChar* buffer);
simInt simCheckCollision_internal(simInt entity1Handle,simInt entity2Handle);
simInt simCheckCollisionEx_internal(simInt entity1Handle,simInt entity2Handle,simFloat** intersectionSegments);
simInt simCheckDistance_internal(simInt entity1Handle,simInt entity2Handle,simFloat threshold,simFloat* distanceData);
simChar* simGetObjectConfiguration_internal(simInt objectHandle);
simInt simSetObjectConfiguration_internal(const simChar* data);
simChar* simGetConfigurationTree_internal(simInt objectHandle);
simInt simSetConfigurationTree_internal(const simChar* data);
simInt simSetSimulationTimeStep_internal(simFloat timeStep);
simFloat simGetSimulationTimeStep_internal();
simInt simGetRealTimeSimulation_internal();
simInt simIsRealTimeSimulationStepNeeded_internal();
simInt simAdjustRealTimeTimer_internal(simInt instanceIndex,simFloat deltaTime);
simInt simGetSimulationPassesPerRenderingPass_internal();
simInt simAdvanceSimulationByOneStep_internal();
simInt simStartSimulation_internal();
simInt simStopSimulation_internal();
simInt simPauseSimulation_internal();
simInt simLoadModule_internal(const simChar* filenameAndPath,const simChar* pluginName);
simInt simUnloadModule_internal(simInt pluginhandle);
simVoid* simSendModuleMessage_internal(simInt message,simInt* auxiliaryData,simVoid* customData,simInt* replyData);
simVoid* simBroadcastMessage_internal(simInt* auxiliaryData,simVoid* customData,simInt* replyData);
simChar* simGetModuleName_internal(simInt index,simUChar* moduleVersion);
simChar* simGetScriptSimulationParameter_internal(simInt scriptHandle,const simChar* parameterName,simInt* parameterLength);
simInt simSetScriptSimulationParameter_internal(simInt scriptHandle,const simChar* parameterName,const simChar* parameterValue,simInt parameterLength);
simInt simFloatingViewAdd_internal(simFloat posX,simFloat posY,simFloat sizeX,simFloat sizeY,simInt options);
simInt simFloatingViewRemove_internal(simInt floatingViewHandle);
simInt simAdjustView_internal(simInt viewHandleOrIndex,simInt associatedViewableObjectHandle,simInt options,const simChar* viewLabel);
simInt simSetLastError_internal(const simChar* funcName,const simChar* errorMessage);
simInt simHandleGraph_internal(simInt graphHandle,simFloat simulationTime);
simInt simResetGraph_internal(simInt graphHandle);
simInt simSetNavigationMode_internal(simInt navigationMode);
simInt simGetNavigationMode_internal();
simInt simSetPage_internal(simInt index);
simInt simGetPage_internal();
simInt simDisplayDialog_internal(const simChar* titleText,const simChar* mainText,simInt dialogType,const simChar* initialText,const simFloat* titleColors,const simFloat* dialogColors,simInt* elementHandle);
simInt simGetDialogResult_internal(simInt genericDialogHandle);
simChar* simGetDialogInput_internal(simInt genericDialogHandle);
simInt simEndDialog_internal(simInt genericDialogHandle);
simInt simRegisterScriptCallbackFunction_internal(const simChar* funcNameAtPluginName,const simChar* callTips,simVoid(*callBack)(struct SScriptCallBack* cb));
simInt simRegisterScriptVariable_internal(const simChar* varNameAtPluginName,const simChar* varValue,simInt stackHandle);
simInt simSetJointTargetVelocity_internal(simInt objectHandle,simFloat targetVelocity);
simInt simGetJointTargetVelocity_internal(simInt objectHandle,simFloat* targetVelocity);
simInt simSetPathTargetNominalVelocity_internal(simInt objectHandle,simFloat targetNominalVelocity);
simChar* simGetScriptRawBuffer_internal(simInt scriptHandle,simInt bufferHandle);
simInt simSetScriptRawBuffer_internal(simInt scriptHandle,const simChar* buffer,simInt bufferSize);
simInt simReleaseScriptRawBuffer_internal(simInt scriptHandle,simInt bufferHandle);
simInt simCopyPasteObjects_internal(simInt* objectHandles,simInt objectCount,simInt options);
simInt simScaleSelectedObjects_internal(simFloat scalingFactor,simBool scalePositionsToo);
simInt simScaleObjects_internal(const simInt* objectHandles,simInt objectCount,simFloat scalingFactor,simBool scalePositionsToo);
simInt simDeleteSelectedObjects_internal();
simInt simGetObjectUniqueIdentifier_internal(simInt objectHandle,simInt* uniqueIdentifier);
simInt simGetNameSuffix_internal(const simChar* name);
simInt simSendData_internal(simInt targetID,simInt dataHeader,const simChar* dataName,const simChar* data,simInt dataLength,simInt antennaHandle,simFloat actionRadius,simFloat emissionAngle1,simFloat emissionAngle2,simFloat persistence);
simChar* simReceiveData_internal(simInt dataHeader,const simChar* dataName,simInt antennaHandle,simInt index,simInt* dataLength,simInt* senderID,simInt* dataHeaderR,simChar** dataNameR);
simInt simSetGraphUserData_internal(simInt graphHandle,const simChar* dataStreamName,simFloat data);
simInt simSetNameSuffix_internal(simInt nameSuffixNumber);
simInt simAddDrawingObject_internal(simInt objectType,simFloat size,simFloat duplicateTolerance,simInt parentObjectHandle,simInt maxItemCount,const simFloat* ambient_diffuse,const simFloat* setToNULL,const simFloat* specular,const simFloat* emission);
simInt simRemoveDrawingObject_internal(simInt objectHandle);
simInt simAddDrawingObjectItem_internal(simInt objectHandle,const simFloat* itemData);
simInt simAddParticleObject_internal(simInt objectType,simFloat size,simFloat density,const simVoid* params,simFloat lifeTime,simInt maxItemCount,const simFloat* ambient_diffuse,const simFloat* setToNULL,const simFloat* specular,const simFloat* emission);
simInt simRemoveParticleObject_internal(simInt objectHandle);
simInt simAddParticleObjectItem_internal(simInt objectHandle,const simFloat* itemData);
simFloat simGetObjectSizeFactor_internal(simInt objectHandle);
simInt simAnnounceSceneContentChange_internal();
simInt simResetMilling_internal(simInt objectHandle);
simInt simApplyMilling_internal(simInt objectHandle);
simInt simSetIntegerSignal_internal(const simChar* signalName,simInt signalValue);
simInt simGetIntegerSignal_internal(const simChar* signalName,simInt* signalValue);
simInt simClearIntegerSignal_internal(const simChar* signalName);
simInt simSetFloatSignal_internal(const simChar* signalName,simFloat signalValue);
simInt simGetFloatSignal_internal(const simChar* signalName,simFloat* signalValue);
simInt simClearFloatSignal_internal(const simChar* signalName);
simInt simSetDoubleSignal_internal(const simChar* signalName,simDouble signalValue);
simInt simGetDoubleSignal_internal(const simChar* signalName,simDouble* signalValue);
simInt simClearDoubleSignal_internal(const simChar* signalName);
simInt simSetStringSignal_internal(const simChar* signalName,const simChar* signalValue,simInt stringLength);
simChar* simGetStringSignal_internal(const simChar* signalName,simInt* stringLength);
simInt simClearStringSignal_internal(const simChar* signalName);
simChar* simGetSignalName_internal(simInt signalIndex,simInt signalType);
simInt simSetObjectProperty_internal(simInt objectHandle,simInt prop);
simInt simGetObjectProperty_internal(simInt objectHandle);
simInt simSetObjectSpecialProperty_internal(simInt objectHandle,simInt prop);
simInt simGetObjectSpecialProperty_internal(simInt objectHandle);
simInt simGetPositionOnPath_internal(simInt pathHandle,simFloat relativeDistance,simFloat* position);
simInt simGetOrientationOnPath_internal(simInt pathHandle,simFloat relativeDistance,simFloat* eulerAngles);
simInt simGetDataOnPath_internal(simInt pathHandle,simFloat relativeDistance,simInt dataType,simInt* intData,simFloat* floatData);
simInt simGetClosestPositionOnPath_internal(simInt pathHandle,simFloat* absolutePosition,simFloat* pathPosition);
simInt simReadForceSensor_internal(simInt objectHandle,simFloat* forceVector,simFloat* torqueVector);
simInt simBreakForceSensor_internal(simInt objectHandle);
simInt simGetShapeVertex_internal(simInt shapeHandle,simInt groupElementIndex,simInt vertexIndex,simFloat* relativePosition);
simInt simGetShapeTriangle_internal(simInt shapeHandle,simInt groupElementIndex,simInt triangleIndex,simInt* vertexIndices,simFloat* triangleNormals);
simInt simSetLightParameters_internal(simInt objectHandle,simInt state,const simFloat* setToNULL,const simFloat* diffusePart,const simFloat* specularPart);
simInt simGetLightParameters_internal(simInt objectHandle,simFloat* setToNULL,simFloat* diffusePart,simFloat* specularPart);
simInt simGetVelocity_internal(simInt shapeHandle,simFloat* linearVelocity,simFloat* angularVelocity);
simInt simGetObjectVelocity_internal(simInt objectHandle,simFloat* linearVelocity,simFloat* angularVelocity);
simInt simAddForceAndTorque_internal(simInt shapeHandle,const simFloat* force,const simFloat* torque);
simInt simAddForce_internal(simInt shapeHandle,const simFloat* position,const simFloat* force);
simInt simSetExplicitHandling_internal(simInt generalObjectHandle,int explicitFlags);
simInt simGetExplicitHandling_internal(simInt generalObjectHandle);
simInt simGetLinkDummy_internal(simInt dummyHandle);
simInt simSetLinkDummy_internal(simInt dummyHandle,simInt linkedDummyHandle);
simInt simSetModelProperty_internal(simInt objectHandle,simInt modelProperty);
simInt simGetModelProperty_internal(simInt objectHandle);
simInt simSetShapeColor_internal(simInt shapeHandle,const simChar* colorName,simInt colorComponent,const simFloat* rgbData);
simInt simGetShapeColor_internal(simInt shapeHandle,const simChar* colorName,simInt colorComponent,simFloat* rgbData);
simInt simResetDynamicObject_internal(simInt objectHandle);
simInt simSetJointMode_internal(simInt jointHandle,simInt jointMode,simInt options);
simInt simGetJointMode_internal(simInt jointHandle,simInt* options);
simInt simSerialOpen_internal(const simChar* portString,simInt baudRate,simVoid* reserved1,simVoid* reserved2);
simInt simSerialClose_internal(simInt portHandle);
simInt simSerialSend_internal(simInt portHandle,const simChar* data,simInt dataLength);
simInt simSerialRead_internal(simInt portHandle,simChar* buffer,simInt dataLengthToRead);
simInt simSerialCheck_internal(simInt portHandle);
simInt simGetContactInfo_internal(simInt dynamicPass,simInt objectHandle,simInt index,simInt* objectHandles,simFloat* contactInfo);
simInt simSetThreadIsFree_internal(simBool freeMode);
simInt simTubeOpen_internal(simInt dataHeader,const simChar* dataName,simInt readBufferSize,simBool notUsedButKeepZero);
simInt simTubeClose_internal(simInt tubeHandle);
simInt simTubeWrite_internal(simInt tubeHandle,const simChar* data,simInt dataLength);
simChar* simTubeRead_internal(simInt tubeHandle,simInt* dataLength);
simInt simTubeStatus_internal(simInt tubeHandle,simInt* readPacketsCount,simInt* writePacketsCount);
simInt simAuxiliaryConsoleOpen_internal(const simChar* title,simInt maxLines,simInt mode,const simInt* position,const simInt* size,const simFloat* textColor,const simFloat* backgroundColor);
simInt simAuxiliaryConsoleClose_internal(simInt consoleHandle);
simInt simAuxiliaryConsoleShow_internal(simInt consoleHandle,simBool showState);
simInt simAuxiliaryConsolePrint_internal(simInt consoleHandle,const simChar* text);
simInt simImportShape_internal(simInt fileformat,const simChar* pathAndFilename,simInt options,simFloat identicalVerticeTolerance,simFloat scalingFactor);
simInt simImportMesh_internal(simInt fileformat,const simChar* pathAndFilename,simInt options,simFloat identicalVerticeTolerance,simFloat scalingFactor,simFloat*** vertices,simInt** verticesSizes,simInt*** indices,simInt** indicesSizes,simFloat*** reserved,simChar*** names);
simInt simExportMesh_internal(simInt fileformat,const simChar* pathAndFilename,simInt options,simFloat scalingFactor,simInt elementCount,const simFloat** vertices,const simInt* verticesSizes,const simInt** indices,const simInt* indicesSizes,simFloat** reserved,const simChar** names);
simInt simCreateMeshShape_internal(simInt options,simFloat shadingAngle,const simFloat* vertices,simInt verticesSize,const simInt* indices,simInt indicesSize,simFloat* reserved);
simInt simCreatePureShape_internal(simInt primitiveType,simInt options,const simFloat* sizes,simFloat mass,const simInt* precision);
simInt simCreateHeightfieldShape_internal(simInt options,simFloat shadingAngle,simInt xPointCount,simInt yPointCount,simFloat xSize,const simFloat* heights);
simInt simGetShapeMesh_internal(simInt shapeHandle,simFloat** vertices,simInt* verticesSize,simInt** indices,simInt* indicesSize,simFloat** normals);
simInt simAddBanner_internal(const simChar* label,simFloat size,simInt options,const simFloat* positionAndEulerAngles,simInt parentObjectHandle,const simFloat* labelColors,const simFloat* backgroundColors);
simInt simRemoveBanner_internal(simInt bannerID);
simInt simCreateJoint_internal(simInt jointType,simInt jointMode,simInt options,const simFloat* sizes,const simFloat* colorA,const simFloat* colorB);
simInt simGetObjectInt32Parameter_internal(simInt objectHandle,simInt parameterID,simInt* parameter);
simInt simSetObjectInt32Parameter_internal(simInt objectHandle,simInt parameterID,simInt parameter);
simInt simGetObjectFloatParameter_internal(simInt objectHandle,simInt parameterID,simFloat* parameter);
simInt simSetObjectFloatParameter_internal(simInt objectHandle,simInt parameterID,simFloat parameter);
simChar* simGetObjectStringParameter_internal(simInt objectHandle,simInt parameterID,simInt* parameterLength);
simInt simSetObjectStringParameter_internal(simInt objectHandle,simInt parameterID,simChar* parameter,simInt parameterLength);
simInt simSetSimulationPassesPerRenderingPass_internal(simInt p);
simInt simGetRotationAxis_internal(const simFloat* matrixStart,const simFloat* matrixGoal,simFloat* axis,simFloat* angle);
simInt simRotateAroundAxis_internal(const simFloat* matrixIn,const simFloat* axis,const simFloat* axisPos,simFloat angle,simFloat* matrixOut);
simInt simGetJointForce_internal(simInt jointHandle,simFloat* forceOrTorque);
simInt simSetArrayParameter_internal(simInt parameter,const simVoid* arrayOfValues);
simInt simGetArrayParameter_internal(simInt parameter,simVoid* arrayOfValues);
simInt simSetIkGroupProperties_internal(simInt ikGroupHandle,simInt resolutionMethod,simInt maxIterations,simFloat damping,void* reserved);
simInt simSetIkElementProperties_internal(simInt ikGroupHandle,simInt tipDummyHandle,simInt constraints,const simFloat* precision,const simFloat* weight,void* reserved);
simInt simCameraFitToView_internal(simInt viewHandleOrIndex,simInt objectCount,const simInt* objectHandles,simInt options,simFloat scaling);
simInt simPersistentDataWrite_internal(const simChar* dataTag,const simChar* dataValue,simInt dataLength,simInt options);
simChar* simPersistentDataRead_internal(const simChar* dataTag,simInt* dataLength);
simInt simIsHandleValid_internal(simInt generalObjectHandle,simInt generalObjectType);
simInt simHandleVisionSensor_internal(simInt visionSensorHandle,simFloat** auxValues,simInt** auxValuesCount);
simInt simReadVisionSensor_internal(simInt visionSensorHandle,simFloat** auxValues,simInt** auxValuesCount);
simInt simResetVisionSensor_internal(simInt visionSensorHandle);
simInt simCheckVisionSensor_internal(simInt visionSensorHandle,simInt entityHandle,simFloat** auxValues,simInt** auxValuesCount);
simFloat* simCheckVisionSensorEx_internal(simInt visionSensorHandle,simInt entityHandle,simBool returnImage);
simInt simGetVisionSensorResolution_internal(simInt visionSensorHandle,simInt* resolution);
simFloat* simGetVisionSensorImage_internal(simInt visionSensorHandle);
simUChar* simGetVisionSensorCharImage_internal(simInt visionSensorHandle,simInt* resolutionX,simInt* resolutionY);
simInt simSetVisionSensorImage_internal(simInt visionSensorHandle,const simFloat* image);
simInt simSetVisionSensorCharImage_internal(simInt visionSensorHandle,const simUChar* image);
simFloat* simGetVisionSensorDepthBuffer_internal(simInt visionSensorHandle);
simInt simRMLPosition_internal(simInt dofs,simDouble timeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxVelAccelJerk,const simBool* selection,const simDouble* targetPosVel,simDouble* newPosVelAccel,simVoid* auxData);
simInt simRMLVelocity_internal(simInt dofs,simDouble timeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxAccelJerk,const simBool* selection,const simDouble* targetVel,simDouble* newPosVelAccel,simVoid* auxData);
simInt simRMLPos_internal(simInt dofs,simDouble smallestTimeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxVelAccelJerk,const simBool* selection,const simDouble* targetPosVel,simVoid* auxData);
simInt simRMLVel_internal(simInt dofs,simDouble smallestTimeStep,simInt flags,const simDouble* currentPosVelAccel,const simDouble* maxAccelJerk,const simBool* selection,const simDouble* targetVel,simVoid* auxData);
simInt simRMLStep_internal(simInt handle,simDouble timeStep,simDouble* newPosVelAccel,simVoid* auxData,simVoid* reserved);
simInt simRMLRemove_internal(simInt handle);
simChar* simFileDialog_internal(simInt mode,const simChar* title,const simChar* startPath,const simChar* initName,const simChar* extName,const simChar* ext);
simInt simMsgBox_internal(simInt dlgType,simInt buttons,const simChar* title,const simChar* message);
simInt simCreateDummy_internal(simFloat size,const simFloat* color);
simInt simSetShapeMassAndInertia_internal(simInt shapeHandle,simFloat mass,const simFloat* inertiaMatrix,const simFloat* centerOfMass,const simFloat* transformation);
simInt simGetShapeMassAndInertia_internal(simInt shapeHandle,simFloat* mass,simFloat* inertiaMatrix,simFloat* centerOfMass,const simFloat* transformation);
simInt simGroupShapes_internal(const simInt* shapeHandles,simInt shapeCount);
simInt* simUngroupShape_internal(simInt shapeHandle,simInt* shapeCount);
simInt simCreateProximitySensor_internal(simInt sensorType,simInt subType,simInt options,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
simInt simCreateForceSensor_internal(simInt options,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
simInt simCreateVisionSensor_internal(simInt options,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
simInt simConvexDecompose_internal(simInt shapeHandle,simInt options,const simInt* intParams,const simFloat* floatParams);
simInt simCreatePath_internal(simInt attributes,const simInt* intParams,const simFloat* floatParams,const simFloat* color);
simInt simInsertPathCtrlPoints_internal(simInt pathHandle,simInt options,simInt startIndex,simInt ptCnt,const simVoid* ptData);
simInt simCutPathCtrlPoints_internal(simInt pathHandle,simInt startIndex,simInt ptCnt);
simFloat* simGetIkGroupMatrix_internal(simInt ikGroupHandle,simInt options,simInt* matrixSize);
simInt simAddGhost_internal(simInt ghostGroup,simInt objectHandle,simInt options,simFloat startTime,simFloat endTime,const simFloat* color);
simInt simModifyGhost_internal(simInt ghostGroup,simInt ghostId,simInt operation,simFloat floatValue,simInt options,simInt optionsMask,const simFloat* colorOrTransformation);
simVoid simQuitSimulator_internal(simBool ignoredArgument);
simInt simGetThreadId_internal();
simInt simLockResources_internal(simInt lockType,simInt reserved);
simInt simUnlockResources_internal(simInt lockHandle);
simInt simEnableEventCallback_internal(simInt eventCallbackType,const simChar* plugin,simInt reserved);
simInt simSetShapeMaterial_internal(simInt shapeHandle,simInt materialIdOrShapeHandle);
simInt simGetTextureId_internal(const simChar* textureName,simInt* resolution);
simChar* simReadTexture_internal(simInt textureId,simInt options,simInt posX,simInt posY,simInt sizeX,simInt sizeY);
simInt simWriteTexture_internal(simInt textureId,simInt options,const simChar* data,simInt posX,simInt posY,simInt sizeX,simInt sizeY,simFloat interpol);
simInt simCreateTexture_internal(const simChar* fileName,simInt options,const simFloat* planeSizes,const simFloat* scalingUV,const simFloat* xy_g,simInt fixedResolution,simInt* textureId,simInt* resolution,const simVoid* reserved);
simInt simWriteCustomDataBlock_internal(simInt objectHandle,const simChar* tagName,const simChar* data,simInt dataSize);
simChar* simReadCustomDataBlock_internal(simInt objectHandle,const simChar* tagName,simInt* dataSize);
simChar* simReadCustomDataBlockTags_internal(simInt objectHandle,simInt* tagCount);
simInt simAddPointCloud_internal(simInt pageMask,simInt layerMask,simInt objectHandle,simInt options,simFloat pointSize,simInt ptCnt,const simFloat* pointCoordinates,const simChar* defaultColors,const simChar* pointColors,const simFloat* pointNormals);
simInt simModifyPointCloud_internal(simInt pointCloudHandle,simInt operation,const simInt* intParam,const simFloat* floatParam);
simInt simGetShapeGeomInfo_internal(simInt shapeHandle,simInt* intData,simFloat* floatData,simVoid* reserved);
simInt* simGetObjectsInTree_internal(simInt treeBaseHandle,simInt objectType,simInt options,simInt* objectCount);
simInt simSetObjectSizeValues_internal(simInt objectHandle,const simFloat* sizeValues);
simInt simGetObjectSizeValues_internal(simInt objectHandle,simFloat* sizeValues);
simInt simScaleObject_internal(simInt objectHandle,simFloat xScale,simFloat yScale,simFloat zScale,simInt options);
simInt simSetShapeTexture_internal(simInt shapeHandle,simInt textureId,simInt mappingMode,simInt options,const simFloat* uvScaling,const simFloat* position,const simFloat* orientation);
simInt simGetShapeTextureId_internal(simInt shapeHandle);
simInt* simGetCollectionObjects_internal(simInt collectionHandle,simInt* objectCount);
simInt simSetScriptAttribute_internal(simInt scriptHandle,simInt attributeID,simFloat floatVal,simInt intOrBoolVal);
simInt simGetScriptAttribute_internal(simInt scriptHandle,simInt attributeID,simFloat* floatVal,simInt* intOrBoolVal);
simInt simReorientShapeBoundingBox_internal(simInt shapeHandle,simInt relativeToHandle,simInt reservedSetToZero);
simInt simSwitchThread_internal();
simInt simCreateIkGroup_internal(simInt options,const simInt* intParams,const simFloat* floatParams,const simVoid* reserved);
simInt simRemoveIkGroup_internal(simInt ikGroupHandle);
simInt simCreateIkElement_internal(simInt ikGroupHandle,simInt options,const simInt* intParams,const simFloat* floatParams,const simVoid* reserved);
simInt simCreateCollection_internal(const simChar* collectionName,simInt options);
simInt simAddObjectToCollection_internal(simInt collectionHandle,simInt objectHandle,simInt what,simInt options);
simInt simSaveImage_internal(const simUChar* image,const simInt* resolution,simInt options,const simChar* filename,simInt quality,simVoid* reserved);
simUChar* simLoadImage_internal(simInt* resolution,simInt options,const simChar* filename,simVoid* reserved);
simUChar* simGetScaledImage_internal(const simUChar* imageIn,const simInt* resolutionIn,simInt* resolutionOut,simInt options,simVoid* reserved);
simInt simTransformImage_internal(simUChar* image,const simInt* resolution,simInt options,const simFloat* floatParams,const simInt* intParams,simVoid* reserved);
simInt simGetQHull_internal(const simFloat* inVertices,simInt inVerticesL,simFloat** verticesOut,simInt* verticesOutL,simInt** indicesOut,simInt* indicesOutL,simInt reserved1,const simFloat* reserved2);
simInt simGetDecimatedMesh_internal(const simFloat* inVertices,simInt inVerticesL,const simInt* inIndices,simInt inIndicesL,simFloat** verticesOut,simInt* verticesOutL,simInt** indicesOut,simInt* indicesOutL,simFloat decimationPercent,simInt reserved1,const simFloat* reserved2);
simInt simExportIk_internal(const simChar* pathAndFilename,simInt reserved1,simVoid* reserved2);
simInt simCallScriptFunctionEx_internal(simInt scriptHandleOrType,const simChar* functionNameAtScriptName,simInt stackId);
simInt simComputeJacobian_internal(simInt ikGroupHandle,simInt options,simVoid* reserved);
simInt simGetConfigForTipPose_internal(simInt ikGroupHandle,simInt jointCnt,const simInt* jointHandles,simFloat thresholdDist,simInt maxTimeInMs,simFloat* retConfig,const simFloat* metric,simInt collisionPairCnt,const simInt* collisionPairs,const simInt* jointOptions,const simFloat* lowLimits,const simFloat* ranges,simVoid* reserved);
simFloat* simGenerateIkPath_internal(simInt ikGroupHandle,simInt jointCnt,const simInt* jointHandles,simInt ptCnt,simInt collisionPairCnt,const simInt* collisionPairs,const simInt* jointOptions,simVoid* reserved);
simChar* simGetExtensionString_internal(simInt objectHandle,simInt index,const char* key);
simInt simComputeMassAndInertia_internal(simInt shapeHandle,simFloat density);
simInt simCreateStack_internal();
simInt simReleaseStack_internal(simInt stackHandle);
simInt simCopyStack_internal(simInt stackHandle);
simInt simPushNullOntoStack_internal(simInt stackHandle);
simInt simPushBoolOntoStack_internal(simInt stackHandle,simBool value);
simInt simPushInt32OntoStack_internal(simInt stackHandle,simInt value);
simInt simPushFloatOntoStack_internal(simInt stackHandle,simFloat value);
simInt simPushDoubleOntoStack_internal(simInt stackHandle,simDouble value);
simInt simPushStringOntoStack_internal(simInt stackHandle,const simChar* value,simInt stringSize);
simInt simPushUInt8TableOntoStack_internal(simInt stackHandle,const simUChar* values,simInt valueCnt);
simInt simPushInt32TableOntoStack_internal(simInt stackHandle,const simInt* values,simInt valueCnt);
simInt simPushFloatTableOntoStack_internal(simInt stackHandle,const simFloat* values,simInt valueCnt);
simInt simPushDoubleTableOntoStack_internal(simInt stackHandle,const simDouble* values,simInt valueCnt);
simInt simPushTableOntoStack_internal(simInt stackHandle);
simInt simInsertDataIntoStackTable_internal(simInt stackHandle);
simInt simGetStackSize_internal(simInt stackHandle);
simInt simPopStackItem_internal(simInt stackHandle,simInt count);
simInt simMoveStackItemToTop_internal(simInt stackHandle,simInt cIndex);
simInt simIsStackValueNull_internal(simInt stackHandle);
simInt simGetStackBoolValue_internal(simInt stackHandle,simBool* boolValue);
simInt simGetStackInt32Value_internal(simInt stackHandle,simInt* numberValue);
simInt simGetStackFloatValue_internal(simInt stackHandle,simFloat* numberValue);
simInt simGetStackDoubleValue_internal(simInt stackHandle,simDouble* numberValue);
simChar* simGetStackStringValue_internal(simInt stackHandle,simInt* stringSize);
simInt simGetStackTableInfo_internal(simInt stackHandle,simInt infoType);
simInt simGetStackUInt8Table_internal(simInt stackHandle,simUChar* array,simInt count);
simInt simGetStackInt32Table_internal(simInt stackHandle,simInt* array,simInt count);
simInt simGetStackFloatTable_internal(simInt stackHandle,simFloat* array,simInt count);
simInt simGetStackDoubleTable_internal(simInt stackHandle,simDouble* array,simInt count);
simInt simUnfoldStackTable_internal(simInt stackHandle);
simInt simDebugStack_internal(simInt stackHandle,simInt cIndex);
simInt simSetScriptVariable_internal(simInt scriptHandleOrType,const simChar* variableNameAtScriptName,simInt stackHandle);
simFloat simGetEngineFloatParameter_internal(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
simInt simGetEngineInt32Parameter_internal(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
simBool simGetEngineBoolParameter_internal(simInt paramId,simInt objectHandle,const simVoid* object,simBool* ok);
simInt simSetEngineFloatParameter_internal(simInt paramId,simInt objectHandle,const simVoid* object,simFloat val);
simInt simSetEngineInt32Parameter_internal(simInt paramId,simInt objectHandle,const simVoid* object,simInt val);
simInt simSetEngineBoolParameter_internal(simInt paramId,simInt objectHandle,const simVoid* object,simBool val);
simInt simCreateOctree_internal(simFloat voxelSize,simInt options,simFloat pointSize,simVoid* reserved);
simInt simCreatePointCloud_internal(simFloat maxVoxelSize,simInt maxPtCntPerVoxel,simInt options,simFloat pointSize,simVoid* reserved);
simInt simSetPointCloudOptions_internal(simInt pointCloudHandle,simFloat maxVoxelSize,simInt maxPtCntPerVoxel,simInt options,simFloat pointSize,simVoid* reserved);
simInt simGetPointCloudOptions_internal(simInt pointCloudHandle,simFloat* maxVoxelSize,simInt* maxPtCntPerVoxel,simInt* options,simFloat* pointSize,simVoid* reserved);
simInt simInsertVoxelsIntoOctree_internal(simInt octreeHandle,simInt options,const simFloat* pts,simInt ptCnt,const simUChar* color,const simUInt* tag,simVoid* reserved);
simInt simRemoveVoxelsFromOctree_internal(simInt octreeHandle,simInt options,const simFloat* pts,simInt ptCnt,simVoid* reserved);
simInt simInsertPointsIntoPointCloud_internal(simInt pointCloudHandle,simInt options,const simFloat* pts,simInt ptCnt,const simUChar* color,simVoid* optionalValues);
simInt simRemovePointsFromPointCloud_internal(simInt pointCloudHandle,simInt options,const simFloat* pts,simInt ptCnt,simFloat tolerance,simVoid* reserved);
simInt simIntersectPointsWithPointCloud_internal(simInt pointCloudHandle,simInt options,const simFloat* pts,simInt ptCnt,simFloat tolerance,simVoid* reserved);
const float* simGetOctreeVoxels_internal(simInt octreeHandle,simInt* ptCnt,simVoid* reserved);
const float* simGetPointCloudPoints_internal(simInt pointCloudHandle,simInt* ptCnt,simVoid* reserved);
simInt simInsertObjectIntoOctree_internal(simInt octreeHandle,simInt objectHandle,simInt options,const simUChar* color,simUInt tag,simVoid* reserved);
simInt simSubtractObjectFromOctree_internal(simInt octreeHandle,simInt objectHandle,simInt options,simVoid* reserved);
simInt simInsertObjectIntoPointCloud_internal(simInt pointCloudHandle,simInt objectHandle,simInt options,simFloat gridSize,const simUChar* color,simVoid* optionalValues);
simInt simSubtractObjectFromPointCloud_internal(simInt pointCloudHandle,simInt objectHandle,simInt options,simFloat tolerance,simVoid* reserved);
simInt simCheckOctreePointOccupancy_internal(simInt octreeHandle,simInt options,const simFloat* points,simInt ptCnt,simUInt* tag,simUInt64* location,simVoid* reserved);
simChar* simOpenTextEditor_internal(const simChar* initText,const simChar* xml,simInt* various);
simChar* simPackTable_internal(simInt stackHandle,simInt* bufferSize);
simInt simUnpackTable_internal(simInt stackHandle,const simChar* buffer,simInt bufferSize);
simInt simSetVisionSensorFilter_internal(simInt visionSensorHandle,simInt filterIndex,simInt options,const simInt* pSizes,const simUChar* bytes,const simInt* ints,const simFloat* floats,const simUChar* custom);
simInt simGetVisionSensorFilter_internal(simInt visionSensorHandle,simInt filterIndex,simInt* options,simInt* pSizes,simUChar** bytes,simInt** ints,simFloat** floats,simUChar** custom);
simInt simSetReferencedHandles_internal(simInt objectHandle,simInt count,const simInt* referencedHandles,const simInt* reserved1,const simInt* reserved2);
simInt simGetReferencedHandles_internal(simInt objectHandle,simInt** referencedHandles,simInt** reserved1,simInt** reserved2);
simInt simGetShapeViz_internal(simInt shapeHandle,simInt index,struct SShapeVizInfo* info);
simInt simExecuteScriptString_internal(simInt scriptHandleOrType,const simChar* stringAtScriptName,simInt stackHandle);
simChar* simGetApiFunc_internal(simInt scriptHandleOrType,const simChar* apiWord);
simChar* simGetApiInfo_internal(simInt scriptHandleOrType,const simChar* apiWord);
simInt simSetModuleInfo_internal(const simChar* moduleName,simInt infoType,const simChar* stringInfo,simInt intInfo);
simInt simGetModuleInfo_internal(const simChar* moduleName,simInt infoType,simChar** stringInfo,simInt* intInfo);
simInt simIsDeprecated_internal(const simChar* funcOrConst);
simChar* simGetPersistentDataTags_internal(simInt* tagCount);
simInt simEventNotification_internal(const simChar* event);
simInt simApplyTexture_internal(simInt shapeHandle,const simFloat* textureCoordinates,simInt textCoordSize,const simUChar* texture,const simInt* textureResolution,simInt options);
simInt simSetJointDependency_internal(simInt jointHandle,simInt masterJointHandle,simFloat offset,simFloat coeff);
simInt simSetStringNamedParam_internal(const simChar* paramName,const simChar* stringParam,simInt paramLength);
simChar* simGetStringNamedParam_internal(const simChar* paramName,simInt* paramLength);



simInt _simGetContactCallbackCount_internal();
const void* _simGetContactCallback_internal(simInt index);
simVoid _simSetDynamicSimulationIconCode_internal(simVoid* object,simInt code);
simVoid _simSetDynamicObjectFlagForVisualization_internal(simVoid* object,simInt flag);
simInt _simGetObjectListSize_internal(simInt objType);
const simVoid* _simGetObjectFromIndex_internal(simInt objType,simInt index);
simInt _simGetObjectID_internal(const simVoid* object);
simInt _simGetObjectType_internal(const simVoid* object);
const simVoid** _simGetObjectChildren_internal(const simVoid* object,simInt* count);
const simVoid* _simGetGeomProxyFromShape_internal(const simVoid* shape);
const simVoid* _simGetParentObject_internal(const simVoid* object);
const simVoid* _simGetObject_internal(int objID);
simVoid _simGetObjectLocalTransformation_internal(const simVoid* object,simFloat* pos,simFloat* quat,simBool excludeFirstJointTransformation);
simVoid _simSetObjectLocalTransformation_internal(simVoid* object,const simFloat* pos,const simFloat* quat);
simVoid _simSetObjectCumulativeTransformation_internal(simVoid* object,const simFloat* pos,const simFloat* quat,simBool keepChildrenInPlace);
simVoid _simGetObjectCumulativeTransformation_internal(const simVoid* object,simFloat* pos,simFloat* quat,simBool excludeFirstJointTransformation);
simBool _simIsShapeDynamicallyStatic_internal(const simVoid* shape);
simInt _simGetTreeDynamicProperty_internal(const simVoid* object);
simInt _simGetDummyLinkType_internal(const simVoid* dummy,simInt* linkedDummyID);
simInt _simGetJointMode_internal(const simVoid* joint);
simBool _simIsJointInHybridOperation_internal(const simVoid* joint);
simVoid _simDisableDynamicTreeForManipulation_internal(const simVoid* object,simBool disableFlag);
simBool _simIsShapeDynamicallyRespondable_internal(const simVoid* shape);
simInt _simGetDynamicCollisionMask_internal(const simVoid* shape);
const simVoid* _simGetLastParentForLocalGlobalCollidable_internal(const simVoid* shape);
simVoid _simSetShapeIsStaticAndNotRespondableButDynamicTag_internal(const simVoid* shape,simBool tag);
simBool _simGetShapeIsStaticAndNotRespondableButDynamicTag_internal(const simVoid* shape);
simVoid _simSetJointPosition_internal(const simVoid* joint,simFloat pos);
simFloat _simGetJointPosition_internal(const simVoid* joint);
simVoid _simSetDynamicMotorPositionControlTargetPosition_internal(const simVoid* joint,simFloat pos);
simVoid _simGetInitialDynamicVelocity_internal(const simVoid* shape,simFloat* vel);
simVoid _simSetInitialDynamicVelocity_internal(simVoid* shape,const simFloat* vel);
simVoid _simGetInitialDynamicAngVelocity_internal(const simVoid* shape,simFloat* angularVel);
simVoid _simSetInitialDynamicAngVelocity_internal(simVoid* shape,const simFloat* angularVel);
simBool _simGetStartSleeping_internal(const simVoid* shape);
simBool _simGetWasPutToSleepOnce_internal(const simVoid* shape);
simBool _simGetDynamicsFullRefreshFlag_internal(const simVoid* object);
simVoid _simSetDynamicsFullRefreshFlag_internal(const simVoid* object,simBool flag);
simVoid _simSetGeomProxyDynamicsFullRefreshFlag_internal(simVoid* geomData,simBool flag);
simBool _simGetGeomProxyDynamicsFullRefreshFlag_internal(const simVoid* geomData);
simBool _simGetParentFollowsDynamic_internal(const simVoid* shape);
simVoid _simSetShapeDynamicVelocity_internal(simVoid* shape,const simFloat* linear,const simFloat* angular);
simVoid _simGetAdditionalForceAndTorque_internal(const simVoid* shape,simFloat* force,simFloat* torque);
simVoid _simClearAdditionalForceAndTorque_internal(const simVoid* shape);
simBool _simGetJointPositionInterval_internal(const simVoid* joint,simFloat* minValue,simFloat* rangeValue);
simInt _simGetJointType_internal(const simVoid* joint);
simBool _simIsForceSensorBroken_internal(const simVoid* forceSensor);
simVoid _simGetDynamicForceSensorLocalTransformationPart2_internal(const simVoid* forceSensor,simFloat* pos,simFloat* quat);
simBool _simIsDynamicMotorEnabled_internal(const simVoid* joint);
simBool _simIsDynamicMotorPositionCtrlEnabled_internal(const simVoid* joint);
simBool _simIsDynamicMotorTorqueModulationEnabled_internal(const simVoid* joint);
simVoid _simGetMotorPid_internal(const simVoid* joint,simFloat* pParam,simFloat* iParam,simFloat* dParam);
simFloat _simGetDynamicMotorTargetPosition_internal(const simVoid* joint);
simFloat _simGetDynamicMotorTargetVelocity_internal(const simVoid* joint);
simFloat _simGetDynamicMotorMaxForce_internal(const simVoid* joint);
simFloat _simGetDynamicMotorUpperLimitVelocity_internal(const simVoid* joint);
simVoid _simSetDynamicMotorReflectedPositionFromDynamicEngine_internal(simVoid* joint,simFloat pos);
simVoid _simSetJointSphericalTransformation_internal(simVoid* joint,const simFloat* quat);
simVoid _simAddForceSensorCumulativeForcesAndTorques_internal(simVoid* forceSensor,const simFloat* force,const simFloat* torque,int totalPassesCount);
simVoid _simAddJointCumulativeForcesOrTorques_internal(simVoid* joint,simFloat forceOrTorque,int totalPassesCount);
simVoid _simSetDynamicJointLocalTransformationPart2_internal(simVoid* joint,const simFloat* pos,const simFloat* quat);
simVoid _simSetDynamicForceSensorLocalTransformationPart2_internal(simVoid* forceSensor,const simFloat* pos,const simFloat* quat);
simVoid _simSetDynamicJointLocalTransformationPart2IsValid_internal(simVoid* joint,simBool valid);
simVoid _simSetDynamicForceSensorLocalTransformationPart2IsValid_internal(simVoid* forceSensor,simBool valid);
const simVoid* _simGetGeomWrapFromGeomProxy_internal(const simVoid* geomData);
simVoid _simGetLocalInertiaFrame_internal(const simVoid* geomInfo,simFloat* pos,simFloat* quat);
simInt _simGetPurePrimitiveType_internal(const simVoid* geomInfo);
simBool _simIsGeomWrapGeometric_internal(const simVoid* geomInfo);
simBool _simIsGeomWrapConvex_internal(const simVoid* geomInfo);
simInt _simGetGeometricCount_internal(const simVoid* geomInfo);
simVoid _simGetAllGeometrics_internal(const simVoid* geomInfo,simVoid** allGeometrics);
simVoid _simGetPurePrimitiveSizes_internal(const simVoid* geometric,simFloat* sizes);
simVoid _simMakeDynamicAnnouncement_internal(int announceType);
simVoid _simGetVerticesLocalFrame_internal(const simVoid* geometric,simFloat* pos,simFloat* quat);
const simFloat* _simGetHeightfieldData_internal(const simVoid* geometric,simInt* xCount,simInt* yCount,simFloat* minHeight,simFloat* maxHeight);
simVoid _simGetCumulativeMeshes_internal(const simVoid* geomInfo,simFloat** vertices,simInt* verticesSize,simInt** indices,simInt* indicesSize);
simFloat _simGetMass_internal(const simVoid* geomInfo);
simVoid _simGetPrincipalMomentOfInertia_internal(const simVoid* geomInfo,simFloat* inertia);
simVoid _simGetGravity_internal(simFloat* gravity);
simInt _simGetTimeDiffInMs_internal(simInt previousTime);
simBool _simDoEntitiesCollide_internal(simInt entity1ID,simInt entity2ID,simInt* cacheBuffer,simBool overrideCollidableFlagIfShape1,simBool overrideCollidableFlagIfShape2,simBool pathOrMotionPlanningRoutineCalling);
simBool _simGetDistanceBetweenEntitiesIfSmaller_internal(simInt entity1ID,simInt entity2ID,simFloat* distance,simFloat* ray,simInt* cacheBuffer,simBool overrideMeasurableFlagIfNonCollection1,simBool overrideMeasurableFlagIfNonCollection2,simBool pathPlanningRoutineCalling);
simInt _simHandleJointControl_internal(const simVoid* joint,simInt auxV,const simInt* inputValuesInt,const simFloat* inputValuesFloat,simFloat* outputValues);
simInt _simHandleCustomContact_internal(simInt objHandle1,simInt objHandle2,simInt engine,simInt* dataInt,simFloat* dataFloat);
const simVoid* _simGetIkGroupObject_internal(int ikGroupID);
simInt _simMpHandleIkGroupObject_internal(const simVoid* ikGroup);
simFloat _simGetPureHollowScaling_internal(const simVoid* geometric);
simVoid _simDynCallback_internal(const simInt* intData,const simFloat* floatData);


// Following courtesy of Stephen James:
simInt simExtLaunchUIThread_internal(const simChar* applicationName,simInt options,const simChar* sceneOrModelToLoad_,const simChar* applicationDir_);
simInt simExtCanInitSimThread_internal();
simInt simExtSimThreadInit_internal();
simInt simExtSimThreadDestroy_internal();
simInt simExtPostExitRequest_internal();
simInt simExtGetExitRequest_internal();
simInt simExtStep_internal(simBool stepIfRunning);
simInt simExtCallScriptFunction_internal(simInt scriptHandleOrType, const simChar* functionNameAtScriptName,
                                         const simInt* inIntData, simInt inIntCnt,
                                         const simFloat* inFloatData, simInt inFloatCnt,
                                         const simChar** inStringData, simInt inStringCnt,
                                         const simChar* inBufferData, simInt inBufferCnt,
                                         simInt** outIntData, simInt* outIntCnt,
                                         simFloat** outFloatData, simInt* outFloatCnt,
                                         simChar*** outStringData, simInt* outStringCnt,
                                         simChar** outBufferData, simInt* outBufferSize);

// Deprecated
simInt simGetMaterialId_internal(const simChar* materialName);
simInt simGetShapeMaterial_internal(simInt shapeHandle);
simInt simHandleVarious_internal();
simInt simSerialPortOpen_internal(simInt portNumber,simInt baudRate,simVoid* reserved1,simVoid* reserved2);
simInt simSerialPortClose_internal(simInt portNumber);
simInt simSerialPortSend_internal(simInt portNumber,const simChar* data,simInt dataLength);
simInt simSerialPortRead_internal(simInt portNumber,simChar* buffer,simInt dataLengthToRead);
simInt simGetPathPlanningHandle_internal(const simChar* pathPlanningObjectName);
simInt simGetMotionPlanningHandle_internal(const simChar* motionPlanningObjectName);
simInt simGetMpConfigForTipPose_internal(simInt motionPlanningObjectHandle,simInt options,simFloat closeNodesDistance,simInt trialCount,const simFloat* tipPose,simInt maxTimeInMs,simFloat* outputJointPositions,const simFloat* referenceConfigs,simInt referenceConfigCount,const simFloat* jointWeights,const simInt* jointBehaviour,simInt correctionPasses);
simFloat* simFindMpPath_internal(simInt motionPlanningObjectHandle,const simFloat* startConfig,const simFloat* goalConfig,simInt options,simFloat stepSize,simInt* outputConfigsCnt,simInt maxTimeInMs,simFloat* reserved,const simInt* auxIntParams,const simFloat* auxFloatParams);
simFloat* simSimplifyMpPath_internal(simInt motionPlanningObjectHandle,const simFloat* pathBuffer,simInt configCnt,simInt options,simFloat stepSize,simInt increment,simInt* outputConfigsCnt,simInt maxTimeInMs,simFloat* reserved,const simInt* auxIntParams,const simFloat* auxFloatParams);
simFloat* simFindIkPath_internal(simInt motionPlanningObjectHandle,const simFloat* startConfig,const simFloat* goalPose,simInt options,simFloat stepSize,simInt* outputConfigsCnt,simFloat* reserved,const simInt* auxIntParams,const simFloat* auxFloatParams);
simFloat* simGetMpConfigTransition_internal(simInt motionPlanningObjectHandle,const simFloat* startConfig,const simFloat* goalConfig,simInt options,const simInt* select,simFloat calcStepSize,simFloat maxOutStepSize,simInt wayPointCnt,const simFloat* wayPoints,simInt* outputConfigsCnt,const simInt* auxIntParams,const simFloat* auxFloatParams);
simInt simCreateMotionPlanning_internal(simInt jointCnt,const simInt* jointHandles,const simInt* jointRangeSubdivisions,const simFloat* jointMetricWeights,simInt options,const simInt* intParams,const simFloat* floatParams,const simVoid* reserved);
simInt simRemoveMotionPlanning_internal(simInt motionPlanningHandle);
simInt simSearchPath_internal(simInt pathPlanningObjectHandle,simFloat maximumSearchTime);
simInt simInitializePathSearch_internal(simInt pathPlanningObjectHandle,simFloat maximumSearchTime,simFloat searchTimeStep);
simInt simPerformPathSearchStep_internal(simInt temporaryPathSearchObject,simBool abortSearch);
simInt simLockInterface_internal(simBool locked);
simInt simCopyPasteSelectedObjects_internal();
simInt simResetPath_internal(simInt pathHandle);
simInt simHandlePath_internal(simInt pathHandle,simFloat deltaTime);
simInt simResetJoint_internal(simInt jointHandle);
simInt simHandleJoint_internal(simInt jointHandle,simFloat deltaTime);
simInt simAppendScriptArrayEntry_internal(const simChar* reservedSetToNull,simInt scriptHandleOrType,const simChar* arrayNameAtScriptName,const simChar* keyName,const simChar* data,const simInt* what);
simInt simClearScriptVariable_internal(const simChar* reservedSetToNull,simInt scriptHandleOrType,const simChar* variableNameAtScriptName);
simVoid _simGetJointOdeParameters_internal(const simVoid* joint,simFloat* stopERP,simFloat* stopCFM,simFloat* bounce,simFloat* fudge,simFloat* normalCFM);
simVoid _simGetJointBulletParameters_internal(const simVoid* joint,simFloat* stopERP,simFloat* stopCFM,simFloat* normalCFM);
simVoid _simGetOdeMaxContactFrictionCFMandERP_internal(const simVoid* geomInfo,simInt* maxContacts,simFloat* friction,simFloat* cfm,simFloat* erp);
simBool _simGetBulletCollisionMargin_internal(const simVoid* geomInfo,simFloat* margin,simInt* otherProp);
simBool _simGetBulletStickyContact_internal(const simVoid* geomInfo);
simFloat _simGetBulletRestitution_internal(const simVoid* geomInfo);
simVoid _simGetVortexParameters_internal(const simVoid* object,simInt version,simFloat* floatParams,simInt* intParams);
simVoid _simGetNewtonParameters_internal(const simVoid* object,simInt* version,simFloat* floatParams,simInt* intParams);
simVoid _simGetDamping_internal(const simVoid* geomInfo,simFloat* linDamping,simFloat* angDamping);
simFloat _simGetFriction_internal(const simVoid* geomInfo);
simInt simAddSceneCustomData_internal(simInt header,const simChar* data,simInt dataLength);
simInt simGetSceneCustomDataLength_internal(simInt header);
simInt simGetSceneCustomData_internal(simInt header,simChar* data);
simInt simAddObjectCustomData_internal(simInt objectHandle,simInt header,const simChar* data,simInt dataLength);
simInt simGetObjectCustomDataLength_internal(simInt objectHandle,simInt header);
simInt simGetObjectCustomData_internal(simInt objectHandle,simInt header,simChar* data);
simInt simCreateUI_internal(const simChar* uiName,simInt menuAttributes,const simInt* clientSize,const simInt* cellSize,simInt* buttonHandles);
simInt simCreateUIButton_internal(simInt uiHandle,const simInt* position,const simInt* size,simInt buttonProperty);
simInt simGetUIHandle_internal(const simChar* uiName);
simInt simGetUIProperty_internal(simInt uiHandle);
simInt simGetUIEventButton_internal(simInt uiHandle,simInt* auxiliaryValues);
simInt simSetUIProperty_internal(simInt uiHandle,simInt elementProperty);
simInt simGetUIButtonProperty_internal(simInt uiHandle,simInt buttonHandle);
simInt simSetUIButtonProperty_internal(simInt uiHandle,simInt buttonHandle,simInt buttonProperty);
simInt simGetUIButtonSize_internal(simInt uiHandle,simInt buttonHandle,simInt* size);
simInt simSetUIButtonLabel_internal(simInt uiHandle,simInt buttonHandle,const simChar* upStateLabel,const simChar* downStateLabel);
simChar* simGetUIButtonLabel_internal(simInt uiHandle,simInt buttonHandle);
simInt simSetUISlider_internal(simInt uiHandle,simInt buttonHandle,simInt position);
simInt simGetUISlider_internal(simInt uiHandle,simInt buttonHandle);
simInt simSetUIButtonColor_internal(simInt uiHandle,simInt buttonHandle,const simFloat* upStateColor,const simFloat* downStateColor,const simFloat* labelColor);
simInt simSetUIButtonTexture_internal(simInt uiHandle,simInt buttonHandle,const simInt* size,const simChar* textureData);
simInt simCreateUIButtonArray_internal(simInt uiHandle,simInt buttonHandle);
simInt simSetUIButtonArrayColor_internal(simInt uiHandle,simInt buttonHandle,const simInt* position,const simFloat* color);
simInt simDeleteUIButtonArray_internal(simInt uiHandle,simInt buttonHandle);
simInt simRemoveUI_internal(simInt uiHandle);
simInt simSetUIPosition_internal(simInt uiHandle,const simInt* position);
simInt simGetUIPosition_internal(simInt uiHandle,simInt* position);
simInt simLoadUI_internal(const simChar* filename,int maxCount,int* uiHandles);
simInt simSaveUI_internal(int count,const int* uiHandles,const simChar* filename);
simInt simHandleGeneralCallbackScript_internal(simInt callbackId,simInt callbackTag,simVoid* additionalData);
simInt simRegisterCustomLuaFunction_internal(const simChar* funcName,const simChar* callTips,const simInt* inputArgumentTypes,simVoid(*callBack)(struct SLuaCallBack* p));
simInt simRegisterContactCallback_internal(simInt(*callBack)(simInt,simInt,simInt,simInt*,simFloat*));
simInt simRegisterJointCtrlCallback_internal(simInt(*callBack)(simInt,simInt,simInt,const simInt*,const simFloat*,simFloat*));
simInt simGetMechanismHandle_internal(const simChar* mechanismName);
simInt simHandleMechanism_internal(simInt mechanismHandle);
simInt simHandleCustomizationScripts_internal(simInt callType);
simInt simCallScriptFunction_internal(simInt scriptHandleOrType,const simChar* functionNameAtScriptName,SLuaCallBack* data,const simChar* reservedSetToNull);


#endif // !defined(V_REP_internal_INCLUDED_)
